OData/odata.net

- WCFDataService/Service/System/Data/Services/Serializers/Serializer.cs
This fixes the scenario described at https://social.msdn.microsoft.com/Forums/en-US/6cc0ef87-80ec-4331-8b41-efb22d8f1c60/odata-provider-with-wcf-40-paging-operations-with-null-parameters?forum=adodotnetdataservices.
We ran into it on building NuGet as well:
* https://github.com/NuGet/NuGetGallery/issues/1502
* https://github.com/NuGet/NuGetGallery/issues/1886
* https://github.com/NuGet/NuGetGallery/issues/1259
Long story short: when an OData service operation `Foo(string bar, string baz)` is called, but `baz` is not provided (`null`), the `GetNextPageQueryParametersForRootContainer()` method on `Serializer` was trying to escape a missing query string parameter, resulting in a `NullReferenceException`.
This pull request fixes this exception by not trying to escape non-existant query string …
> Only append parameter when it was provided in the first place

- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Debug.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
- src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Debug.nuspec
- src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec
- src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec
- src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Debug.nuspec
- src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec
- src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
Limit the impact scope of these two frameworks to ASP.NET 5 applications.
> Rename net45 to dnx451; portable-net45 to dnxcore50

- src/Microsoft.OData.Edm/ExtensionMethods/EnumHelper.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ParallelTests.cs
Lock the global static cache before modification operation.
> Issue#216 Fix race condition in EnumHellper.TryParseEnum

- src/Microsoft.OData.Client/ALinq/ResourceBinder.cs
- test/EndToEndTests/Services/ODataDefaultService/DefaultInMemoryModel.cs
- test/EndToEndTests/Services/ODataOperationService/OperationServiceOperationProvider.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/OperationTests/OperationClientTests.cs
This is to fix the issue https://github.com/OData/odata.net/issues/357. Reason is that VerifyKeyPredicates will check the source of the function expresion. Since function might bind to a collection of entity, so we should avode verifing the key predicates of the source.
> Fix VerifyKeyPredicates issue

- src/Microsoft.OData.Core/UriParser/Parsers/FunctionOverloadResolver.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Query.TDD.Tests/Metadata/OpenTypeExtensionTestBase.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Query.TDD.Tests/Metadata/OpenTypeUnqualifiedExtensionUnitTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Query.TDD.Tests/Microsoft.Test.OData.Query.TDD.Tests.csproj
Loose validation for non-default UriResolver according to https://github.com/OData/odata.net/issues/200#issuecomment-111011495.
For open types, each unqualified operation name should be followed with parenthesis (with or without parameters).
> Issue #200: Enable unqualified functions on open types.

- _posts/core libraries/2015-04-29-01-02-read-payload.md
Fix broken link to file `InMemoryMessage.cs` in the ODataLib documentation.
> Fix broken link to file InMemoryMessage.cs

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Uri/ExpressionConstants.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/AggregateExpression.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/AggregateExpressionToken.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/AggregationMethod.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/SyntacticAst/AggregateExpressionTokenTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriQueryExpressionParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Visitors/SyntacticTreeVisitorTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*Enhancing AggregationMethod class and modifying UriQueryExpressionParser to support Custom Aggregation Methods according to OData 4.0 spec. Right now only methods that return doubles are supported. This change addresses issue [#873](https://github.com/OData/WebApi/issues/873) of WebAPI project.*
*We need to find out the best way to address the TODOs in the code. In the return type of the aggregation methods: right now we are limited to methods that returns doubles, because the parsers don't have information about the methods registered.*
> Custom aggregation methods

- v6/_posts/tooling/2015-12-18-OData-Client-Code-Generation-Tool.md
Doc change: Remove extra ()s to generate correct url for tooling blog entry.
Currently, the doc points to: http://odata.github.io/odata.net/(http://blogs.msdn.com/b/odatateam/archive/2014/03/12/how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class.aspx)
After the change, the link points to: http://blogs.msdn.com/b/odatateam/archive/2014/03/12/how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class.aspx
> Remove extra ()s to generate correct url for tooling blog entry.

- src/Microsoft.OData.Core/Evaluation/ODataConventionalEntityMetadataBuilder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
*This pull request fixes issue #xxx.*  
*ODL currently assumes it can't read an operation response tied to a nested payload.  Enhancing code and tests to support.*
*No Docs Needed.*
> Fix tests and code for reading nested results from operations.

- src/Microsoft.OData.Edm/Build.Net35/Microsoft.OData.Edm.NetFX35.csproj
- src/Microsoft.OData.Edm/Csdl/CsdlConstants.cs
- src/Microsoft.OData.Edm/Csdl/Parsing/Ast/CsdlAnnotationPathExpression.cs
- src/Microsoft.OData.Edm/Csdl/Parsing/Ast/CsdlEntitySet.cs
- src/Microsoft.OData.Edm/Csdl/Parsing/CsdlDocumentParser.cs
- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsAnnotationPathExpression.cs
- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsEntitySet.cs
- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsModel.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
- src/Microsoft.OData.Edm/Schema/AmbiguousEntitySetBinding.cs
- src/Microsoft.OData.Edm/Schema/BadEntitySet.cs
- src/Microsoft.OData.Edm/Schema/EdmEntityContainer.cs
- src/Microsoft.OData.Edm/Schema/EdmEntitySet.cs
- src/Microsoft.OData.Edm/Schema/Interfaces/IEdmEntitySet.cs
- src/Microsoft.OData.Edm/Schema/Interfaces/IEdmExpression.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
- test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmEntitySet.cs
- test/FunctionalTests/Taupo/Source/Taupo.Edmlib/StubEdm/StubEdmEntitySet.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/CsdlParsingTests.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalUtilities/InterfaceCriticalModelBuilder.cs
- test/FunctionalTests/Tests/DataEdmLib/StubEdm/StubEdmEntitySet.cs
This pull request fixes issue #525 and #526
Added parsing of AnnotationPath attribute as an Expression and parsing of IncludeInServiceDocument attribute for EntitySet in CsdlDocumentParser
Updated classes and interfaces for supporting the new attributes
Added a functional test with a sample metadata document
> Add support for parsng attributes AnnotationPath (#525) and IncludeInServiceDocument (#526)

- src/Microsoft.OData.Core/DuplicatePropertyNamesChecker.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Annotation/ClientAnnotationTests.cs
This pull request fixes issue #739.
The `DuplicatePropertyNamesChecker` calls the function `ThrowIfPropertyIsProcessed` when it tries to add a property annotation. Unfortunately, when an entity annotation has been processed, annotations on properties with the same name are considered to be equal (erroneously).
However, a comment was saying that this call should not be needed with a new implementation of the Json Light deserializer, and I think this new deserializer has been correctly implemented because the test scenarios pass as expected without this call. So this commit simply removes the call to this function.
> Prevent the OData Client to throw on annotations that were misintepreted as duplicate

- src/Microsoft.OData.Edm/Csdl/CsdlReader.cs
- src/Microsoft.OData.Edm/Csdl/Parsing/Common/EdmXmlDocumentParser.cs
- src/Microsoft.OData.Edm/Validation/ValidationHelper.cs
- src/Microsoft.OData.Edm/Vocabularies/AlternateKeysVocabularyModel.cs
- src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularyModel.cs
- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyModel.cs
The XmlResolver property no longer exists in .NET portable framework. Now that the code compile
using VS2015 and uses the Code Analysis and FxCop rule associated with VS2015, add an exclusion 
for this rule in code that compiles under .Net portable framework.
> Adding FxCop exclusion for CA3053:UseXmlSecureResolver in code that compiles under .Net portable framework.

- src/Microsoft.OData.Edm/Build.NetStandard/Microsoft.OData.Edm.NetStandard.csproj
- src/Microsoft.OData.Edm/Vocabularies/AlternateKeysVocabularyModel.cs
- src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularyModel.cs
- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyModel.cs
This pull request fixes issue #789   
The EdmModel constructor was failing with System.TypeInitializationException:“The type initializer
for 'Microsoft.OData.Edm.Vocabularies.V1.CoreVocabularyModel' threw an exception.”
This was caused by the construction of the CoreVocabularyModel looking for embedded resources
that are not present in the .NetStandard version of Edm.
In addition to adding the embedded resources, the resource name are fully qualified
in NetStandard so addition code is added to find the proper name for the resource before
loading it.
The fix was tested by temporarily adding a unit test to validate the EdmModel constructor
as well as the unit test validation for CoreVocabularyModel …
> Fix for "The type initializer for 'CoreVocabularyModel' threw an exception.

- test/EndToEndTests/Services/Astoria/Microsoft.Test.OData.Services.Astoria.csproj
- test/EndToEndTests/Services/Astoria/PublicProvider/DatabaseHelper.cs
- test/FunctionalTests/Framework/AstoriaTestFramework.csproj
- test/FunctionalTests/Framework/TestExecutionLayer/AstoriaDatabase.cs
- test/FunctionalTests/Framework/Util/DataUtil.cs
- test/FunctionalTests/Tests/DataServices/Models/EFFK/Astoria.EFFKModel.csproj
- test/FunctionalTests/Tests/DataServices/Models/EFFK/PopulateData.cs
- test/FunctionalTests/Tests/DataServices/ddbasics/Microsoft.Test.Data.Services.DDBasics.csproj
- test/FunctionalTests/Tests/DataServices/ddbasics/Util/DataUtil.cs
- tools/Scripts/artdbclean.js
This change fixes test failures in both local machine and in the lab
because of the switch to VS2015. Switching to VS2015 changed the testing
database engine from SQL Express to LocalDb. Since VS2015 installs LocalDb,
this is a change that make sense to keep.
For local tests, some client tests were failing due to a failure to
clean up local database entries in LocalDB. The change to artdbclean.js
uses SQL Native Client for LocalDB to fix a connection issue, allowing the
script to properly clean up after the tests.
For lab tests, the machine configuration is a bit different and LocalDb is not
available; therefore, use SQL Express when building the lab. Since the current
VS2015 symbol was only used for test DB selection, I renamed the symbol to
reflect its usage.
- …
> Fix client test failures

- v7/_posts/release notes/2017-05-02-ODL-7.2.0.md
N/A
This PR corresponds to the release of OData libraries 7.2.0. Release summary: "7.2.0 re-introduces .NET Standard 1.1 libraries of ODataLib (OData.Core, OData.Edm, and Microsoft.Spatial). The PCL versions remain in the packages and are shipped alongside the new .NET Standard libraries. Bug fixes and additional test validations are also included in this release."
N/A
N/A
> Adding ODL 7.2.0 release notes

- src/Microsoft.OData.Core/UriParser/Aggregation/AggregateExpression.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataContextUriBuilderTests.cs
*This pull request fixes issue #760 for 7.X.*  
*Dynamic properties don't have type. Relaxed null check in AggregateExpression and related changes in ApplyBinder to allow usage of dynamic properties in groupby clause.*
*Changes in WebApi repo is needed to finalize. PR for 6.X https://github.com/OData/odata.net/pull/798 *
> Support dynamic properties in $apply

- build.ps1
- sln/.nuget/packages.config
- sln/Microsoft.Test.OData.Tests.Client.Portable.WindowsStore.sln
*This pull request fixes issue #810.*  
- Updating build.ps1 to skip building the Microsoft.Test.OData.Tests.Client.Portable.WindowsStore.sln if VS2013 is not installed. This is due to the fact that Windows 8.0 apps are not supported with VS2015. We will not force users to install multiple versions of Visual Studio, but if they happen to have VS2013 installed, we'll build the solution as it provides additional local validation of code changes. We will have automation that will build the solution.
- Updating Microsoft.Test.OData.Tests.Client.Portable.WindowsStore.sln to build the projects in order in the event of race conditions during build.
- Adding .NET Core packages to nuget for the .NET Standard solution.
- [ x ] Test cases added (N/A)
- [ x ] Build and test with one-click build and …
> Updating build script regarding Windows Store test solution

- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- src/Microsoft.OData.Edm/ExtensionMethods/EdmTypeSemantics.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataContextUriBuilderTests.cs
*This pull request fixes issue #760.*  
Dynamic properties don't have type. PR https://github.com/OData/odata.net/pull/798 added support, but average aggregation method wasn't supported. 
Changes in WebApi repo is needed to finalize. Related changes are part of https://github.com/OData/WebApi/pull/973
> Support average for dynamic properties

- src/Microsoft.OData.Core/ODataCollectionReaderCore.cs
- src/Microsoft.OData.Core/ODataCollectionReaderCoreAsync.cs
*Improve test code coverage.*  
*ReadImplmentation() or ReadAsynchronously() has some unreachable code blocked by ODataCollectionReaderCore.VerifyCanRead() processing. Approach here is to remove the unreachable code from the src; another alternative is to add test along with src code change to circumvent internal processing of VerifyCanReader so that ReadImplementation/ReadAsynchronously can be unblocked.*
*The first approach is preferred, since the second approach also needs src code change which is hacky. I can share the second approach as needed.*
> Remove unreachable code block for collection reader.

- test/EndToEndTests/Tests/Client/Build.Desktop/SingletonTests/SingletonQueryTests.cs
This will make the test pass even on systems configured with a non-US culture
> Assert DateTimeOffset equality on DateTimeOffset object

- src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj
- src/Microsoft.OData.Core/Build.NetStandard/Microsoft.OData.Core.NetStandard.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/UriParser/Binders/DottedIdentifierBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/InnerPathTokenBinder.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/SingleValueCastNode.cs
- src/Microsoft.OData.Core/UriParser/TreeNodeKinds/QueryNodeKind.cs
- src/Microsoft.OData.Core/UriParser/Visitors/QueryNodeVisitor.cs
- src/Microsoft.OData.Core/UriParser/Visitors/SelectPropertyVisitor.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/NodeAssertions.cs
- test/FunctionalTests/Service/Microsoft/OData/Service/Parsing/NodeToExpressionTranslator.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
This pull request fixes issue #801 and #747 
Modify the binding operations so that type casts and dynamic properties on dynamic complex properties can be successfully bound to Nodes during the parsing process.
No documentation changes needed.
> Add Support for PrimitiveType casts

- src/Microsoft.OData.Client/AtomMaterializerLog.cs
- src/Microsoft.OData.Client/BaseAsyncResult.cs
- src/Microsoft.OData.Client/BaseSaveResult.cs
- src/Microsoft.OData.Client/BatchSaveResult.cs
- src/Microsoft.OData.Client/Binding/DataServiceCollectionOfT.cs
- src/Microsoft.OData.Client/Common.cs
- src/Microsoft.OData.Client/DataServiceQueryContinuation.cs
- src/Microsoft.OData.Client/DataServiceQueryOfT.cs
- src/Microsoft.OData.Client/DataServiceRequestOfT.cs
- src/Microsoft.OData.Client/GetReadStreamResult.cs
- src/Microsoft.OData.Client/GlobalSuppressions.cs
- src/Microsoft.OData.Client/Materialization/HttpWebResponseMessage.cs
- src/Microsoft.OData.Client/Materialization/ODataMaterializer.cs
- src/Microsoft.OData.Client/QueryResult.cs
- src/Microsoft.OData.Client/SaveResult.cs
- src/Microsoft.OData.Client/Serialization/DataStringEscapeBuilder.cs
- src/Microsoft.OData.Client/Serialization/HttpWebRequestMessage.cs
- src/Microsoft.OData.Client/Serialization/Serializer.cs
- src/Microsoft.OData.Client/UriUtil.cs
- src/Microsoft.OData.Edm/Csdl/EdmValueWriter.cs
- src/Microsoft.Spatial/ForwardingSegment.cs
- src/Microsoft.Spatial/SpatialReader.cs
…ssions.
*This pull request is for cleaning up AC00xx (DataUsage) warning category that has become obsoleted.*
*Remove the AC warnings.*
> ODL-Spatial, ODL-Edm, ODL-Client: cleanup obsolete AC warnings suppresion

- src/Microsoft.OData.Client/ALinq/ReflectionUtil.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/ODataBatchReader.cs
- src/Microsoft.OData.Core/ODataCollectionReader.cs
- src/Microsoft.OData.Core/ODataCollectionReaderCore.cs
- src/Microsoft.OData.Core/ODataCollectionReaderCoreAsync.cs
- src/Microsoft.OData.Core/ODataDeltaReader.cs
- src/Microsoft.OData.Core/ODataParameterReader.cs
- src/Microsoft.OData.Core/ODataParameterReaderCore.cs
- src/Microsoft.OData.Core/ODataParameterReaderCoreAsync.cs
- src/Microsoft.OData.Core/ODataReader.cs
- src/Microsoft.OData.Core/ODataReaderCore.cs
- src/Microsoft.OData.Core/ODataReaderCoreAsync.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/KeySegment.cs
- src/Microsoft.OData.Core/Utils.cs
- src/Microsoft.Spatial/CoordinateSystem.cs
*This pull request is for cleaning up CA9xx(MSInternal) warning category.*
*Remove CA908 warnings.*
> CA exclusion analysis: MSInternal warnings: removing CA908.

- build.ps1
- sln/.nuget/packages.config
- test/EndToEndTests/Services/Astoria/Microsoft.Test.OData.Services.Astoria.csproj
- test/EndToEndTests/Tests/Client/Build.Desktop/CodeGenerationTests/T4CodeGenerationTests.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/Microsoft.Test.OData.Tests.Client.csproj
- test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTestsBase.cs
- test/EndToEndTests/Tests/Client/EndToEndTestBase.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/Microsoft.Data.WebClientCSharp.UnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/Microsoft.Data.WebClient.UnitTests.vbproj
- test/FunctionalTests/Tests/DataServices/UnitTests/MetadataObjectModelTests/Microsoft.Data.MetadataObjectModel.UnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/NamedStreamTests/Microsoft.Data.NamedStream.UnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/RegressionUnitTests/Microsoft.Data.Web.RegressionUnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Microsoft.Data.Web.UnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Stubs/DataServiceProvider/DSPUnitTestServiceDefinition.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests1/Microsoft.Data.ServerUnitTests1.UnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests2/Microsoft.Data.ServerUnitTests2.UnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests2/Tests/DbContextTest.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/TDDUnitTests/Microsoft.OData.Service.TDDUnitTests.csproj
Standardize on EntityFramework 5.0 for tests to reduce race conditions
for EntityFramework dependent tests.
> Standardize on EntityFramework 5.0 for tests to reduce race conditions

- build.ps1
- sln/Microsoft.OData.Full.sln
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Annotation/ClientAnnotationTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/HttpContextServiceHostTest.cs
- tools/Scripts/TestStartup.cmd
By default, make build.cmd run all tests as to ensure nothing is missed.
Optionally, run build.cmd quick to run only the unit tests.
Add TestStartup.cmd to prepare for test runs in the build environment.
Remove TestCategoryAttributeCheck.csproj from the solution as it provides little value.
Changed HttpContextServiceHostRequestNameTest to run against localhost.
Rename a misspelled test.
> By default, make build.cmd run all tests as to ensure nothing is missed.

- src/Microsoft.OData.Client/ClientEdmModel.cs
- src/Microsoft.OData.Client/DictionaryExtensions.cs
- src/Microsoft.OData.Client/TypeResolver.cs
This pull request cherry picked from #902 fixes issue #898.
Change structure of `ClientEdmModel.EdmStructuredSchemaElements` from `List<IEdmSchemaElement>` to `ConcurrentDictionary<string,IEdmSchemaElement>` where the key is the `Name` property.
This should make the property thread-safe while at the same time improve performance for large number of schema elements.
The reason this property should be made thread-safe is because the `ClientEdmModel` instances are shared through the [ClientEdmModelCache](https://github.com/OData/odata.net/blob/c0389b23b383cf9f6b9009b23b9c2bff98fa660f/src/Microsoft.OData.Client/DataServiceContext.cs#L3462) while the property gets updated by `TypeResolver` when sending requests / processing responses.
> change EdmStructuredSchemaElements to a ConcurrentDictionary

- src/Microsoft.OData.Client/ClientEdmModel.cs
- src/Microsoft.OData.Client/DictionaryExtensions.cs
- src/Microsoft.OData.Client/TypeResolver.cs
This pull request fixes issue #898 
Change structure of `ClientEdmModel.EdmStructuredSchemaElements` from `List<IEdmSchemaElement>` to `ConcurrentDictionary<string,IEdmSchemaElement>` where the key is the `Name` property.
This should make the property thread-safe while at the same time improve performance for large number of schema elements.
The reason this property should be made thread-safe is because the `ClientEdmModel` instances are shared through the [ClientEdmModelCache](https://github.com/OData/odata.net/blob/c0389b23b383cf9f6b9009b23b9c2bff98fa660f/src/Microsoft.OData.Client/DataServiceContext.cs#L3462) while the property gets updated by `TypeResolver` when sending requests / processing responses.
> Make ClientEdmModel.EdmStructuredSchemaElements thread-safe

- src/Microsoft.OData.Core/Uri/ODataUri.cs
- src/Microsoft.OData.Core/UriParser/ODataUriParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FullUriFunctionalTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
Need to give some added exposure of the $compute option within the parser by adding it to the ODataUri general parse method.
> Add Compute to ParseUri.

- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/RequestUriProcessorTest.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Utils/LocalWebServerHelper.cs
*This pull request fixes test instability issue due to local IIS WebServer are not properly cleaned up between test runs.*
*Remove the local IIS Webserver from list of server types in the two test cases affected. *
> remove IIS Local server test cases due to timing issue

- src/Microsoft.OData.Core/UriParser/Parsers/LiteralParsers/CustomUriLiteralParsers.cs
This pull request fixes a performance issue where a global lock was being taken inside of CustomUriLiteralParsers when parsing, causing a high degree of contention when multiple threads were trying to parse URIs at the same time.
Makes the parser collections immutable arrays and acquires the lock only when acquiring a reference to the current collection, or when replacing the collection.
No new test cases were added because the change does not impact functional correctness. Existing tests should have sufficient coverage.
Needs to be ported to the maintenance-6.x branch after commit to master.
> Port PR 937to ODL 6.x

- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/HttpContextServiceHostTest.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/RequestUriProcessorTest.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Tests/SecurityTest.cs
For build machine for code coverage debug run:
- SecurityPartialTrustTest
- HttpContextServiceHostTunnelingTest
- RequestUriCaseInsensitive
*This pull request fixes issue of test instability due to local IIS server data racing
For build machine for code coverage debug run
- SecurityPartialTrustTest
- HttpContextServiceHostTunnelingTest
- RequestUriCaseInsensitive*
*All the test cases disabled are confirmed to be related using IIS Local server, along with other server types. Only data related to IIS Local server part is disabled.*
> Disable additional test case data subjected to IIS local server instance racing

- src/Microsoft.OData.Client/DataServiceQuerySingleOfT.cs
*This pull request fixes issue #698.*
Use `SingleOrDefault()` instead of `Single()` to get the consistent behavior in DataServiceQuerySingle.GetValueAsync and DataServiceQuerySingle.GetValue.
A test should be added, but this project is too huge for me to find where the test for this fix belongs.
> Make DataServiceQuerySingle.GetValueAsync consistent with GetValue

- src/Microsoft.OData.Client/ClientEdmModel.cs
- src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
- src/Microsoft.OData.Core/Evaluation/LiteralFormatter.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientEdmModelTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/TDDUnitTests/Tests/Server/LiteralConversionTests.cs
Do not know if there is an issue open for this.
Currently only simple keys are supported. Adding ability to support Enum keys.
- [ X ] Test cases added
- [  ] Build and test with one-click build and test script passed
No
> Add support for ENUM keys

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightContextUriParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightContextUriParserTests.cs
*This pull request fixes issue #965 * for 6.x branch
*This pull request ported from #969
Parsing the tokens of a context url in ODataJsonLightContextUriParser.TokenizeContextUri now use UriFormat.SafeUnescaped instead of UriFormat.Unescaped
None
> Escaped special meaning characters remain escaped 

- src/Microsoft.OData.Client/ClientEdmModel.cs
*This pull request fixes issue #990 .*
* Generic Dictionary does not support multi thread read and write. .Net Standard 1.1 does support ConcurrentDictionary, which makes this a easy fix.
> Use ConcurrentDictionary in all platforms to make client edm model thread safe

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
- src/Microsoft.OData.Core/PropertyCache.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/JsonLight/ODataJsonLightWriterIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/FullPayloadValidateTests.cs
*This pull request fixes issue #1008*
*This pull request fixes issue #1009*
*Supports V6 capability of:
1) Writing special characters in property names if Validations.None is specified, and
2) Writing undefined untyped properties to open types*
*None.*
> Fix property validation issues

- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/JsonBatchRoundTripTests.cs
*This pull request fixes test error message string in BatchJsonLightAtomicGroupCannotCreateGroupIdWithNullValue.*
*Updated the error message string to the last API prolog change.*
> Updating test's error message to align with previous API prolog chagnes.

- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue in Public API bsl.*
*Align the changed parameter name in PublicAPI.bsl since it checks param name as well.*
> Align PublicApi.bsl with preceding API prolog changes.

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
*This pull request fixes FxCop error related to using ToLowerInvariant().*
*Replacing ToLower() with ToLowerInvariant() in ODataJsonLightBatchWriter.*
> FxCopFixes: use ToLowerInvariant

- src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec
- src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec
Adding back the OData Client binary for Net45 framework per feedback from community. For reference, the PR that removed the binaries was #981.
#731, #1011
A few users depended on particular code patterns found only in the non-portable versions of OData Client (i.e. Net45 framework), so this PR is to add back that Client version based on the feedback.
None
> Adding OData Client Net45 binary

- src/Microsoft.OData.Core/HttpUtils.cs
- src/Microsoft.OData.Core/Json/JsonLightInstanceAnnotationWriter.cs
- src/Microsoft.OData.Core/JsonLight/JsonLightMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonLightODataAnnotationWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightSerializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
- src/Microsoft.OData.Core/MediaTypeUtils.cs
- src/Microsoft.OData.Core/MimeConstants.cs
- src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
- src/Microsoft.OData.Core/ODataObjectModelExtensions.cs
- src/Microsoft.OData.Core/ODataSimplifiedOptions.cs
- src/Microsoft.OData.Core/ODataUtils.cs
- src/Microsoft.OData.Core/WriterUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/MediaTypeUtilsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageReaderSettingsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/PrimitiveValuesRoundtripJsonLightTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/ODataJsonLightPropertyTypeSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/WriterUtilsTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1037.*
In PR #989 we added support for writing the new 4.01 delta format by specifying ODataVersion.401 in WriterSettings. This PR supports additional requirements when writing, or reading, a 4.01 payload.
> 401 format fixes

- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchReader.cs
- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriterUtils.cs
*This pull request fixes issue #1040.*
*Update changeset id to use whole boundary value, so that WebAPI test using latest ODL-7.4 can pass.*
- [] *Test cases added*
> Update changeset id to use whole boundary value.

- src/Microsoft.OData.Edm/Validation/ValidationRuleSet.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRuleSetTests.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/NavigationValidationTests.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/SemanticValidationTests.cs
* Issue from the Graph beta validation. It shows: 
Problem 3: NavigationPropertyEntityMustNotIndirectlyContainItself:The navigation property 'events' is invalid because it indirectly contains itself. 
When we validate the Graph beta CSDL, it gives us the following error messages:
```C#
The navigation property 'drive' is invalid because it indirectly contains itself.
The navigation property 'driveItem' is invalid because it indirectly contains itself.
The navigation property 'site' is invalid because it indirectly contains itself.
The navigation property 'worksheet' is invalid because it indirectly contains itself.
The navigation property 'worksheet' is invalid because it indirectly contains itself.
The navigation property 'charts' is invalid because it indirectly contains itself.
```
As …
> Remove the NavigationPropertyEntityMustNotIndirectlyContainItself rule

- src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularyModel.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CapabilitiesVocabularyTests.cs
See issue at: https://issues.oasis-open.org/browse/ODATA-1134
In OData 4.01 we introduced semantics around supporting the popular key-as-segment URL syntax, but we have no generic way for clients to know whether or not the service supports this sytnax. 
This PR is to add a new boolean term to the capabilities vocabulary, `KeyAsSegmentSupported`
> Add KeyAsSegmentSupported annotation term to Capabiliites vocabulary

- src/Microsoft.OData.Core/UriParser/ODataUriParserConfiguration.cs
- src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SemanticTreeFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
Enable public API for DI in
* ODataUriResolver
* ODataUriParserConfiguration
*This pull request provides support for using optionalDollarSign from WebAPI.*
*small test update and expose API for option EnableOptionalDollarSign.*
> OptionalDollarSign: Small test update and expose API for DI option setter/getter

- src/Microsoft.OData.Edm/Validation/ValidationRules.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
* https://github.com/OData/odata.net/issues/1046
When we do some validation on Graph beta, we get the following error messages:
**DuplicateAnnotation:The annotated element 'microsoft.graph.managedAppProtection' has multiple annotations with the term 'Org.OData.Core.V1.Description' and the qualifier ''.**
That's because DuplicateAnnotation validation rule verifies the base and derived type's annotation together. Once it finds a duplicated annotation applied, no matter on base or derived, it outputs an error message.
> Modify the duplicated annotation validation issue

- src/Microsoft.OData.Client/ALinq/TypeSystem.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DateTimeClientSupportTest.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/LinqIntegrationTests.cs
*This pull request fixes issue #530.*
*The DateTimeOffset.Date method was added to the TypeSystem class.*
*Also corresponding methods were added for the DateTime class to make work expressions like this `dateTimeOffsetProperty.Date.Hour`*
> Odata v4 6.x - Fix #530 LINQ query generation with Date functions produces weird urls

- src/Microsoft.OData.Client/ALinq/TypeSystem.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/LinqIntegrationTests.cs
*This pull request fixes issue #530.*
*The DateTimeOffset.Date method was added to the TypeSystem class.*
*Also corresponding methods were added for the DateTime class to make work expressions like this `dateTimeOffsetProperty.Date.Hour`*
> Odata v4 7.x - Fix #530 LINQ query generation with Date functions produces weird urls

- v7/_posts/release notes/2017-05-02-ODL-7.2.0.md
- v7/_posts/release notes/2018-02-13-ODL-7.4.1.md
Adding release notes for ODL 7.4.1
> Adding release notes for ODL 7.4.1

- src/CodeGen/ODataT4ItemTemplate/source.extension.vsixmanifest
The ID in the new VS2017 Client Code Gen package is different from the ID of the current VSIX package on the [VS marketplace](https://marketplace.visualstudio.com/items?itemName=bingl.ODatav4ClientCodeGenerator).
This PR changes the ID to the existing ID.
N/A
> Updating package ID to match the existing VSIX ID in the marketplace

- src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ExpressionLexerTests.cs
*This pull request fixes ODL 7.4.1 issue of parameter alias parsing in dotted expression.*
*ExpressionLexer gets confused when trying to parse ParameterAlias token from expression containing ".", which is intended for annotation, in parts outside of the identifier token *
Example stack trace (from WebAPI test):
Microsoft.OData.ODataException : Could not find a property named '@p' on type 'System.Web.OData.Query.Expressions.DataTypes'.
c:\github\WebApi-master\myWebApi\tools\WebStack.xunit.targets(12,9): error :    at Microsoft.OData.UriParser.EndPathBinder.GeneratePropertyAccessQueryForOpenType(EndPathToken endPathToken, SingleValueNode parentNode)
c:\github\WebApi-master\myWebApi\tools\WebStack.xunit.targets(12,9): error :    at Microsoft.OData.UriParser.EndPathBinder.BindEndPath(EndPathTo …
> ExpressionLexer fix for parameter alias token in dotted expression

- src/Microsoft.OData.Core/UriParser/Binders/MetadataBindingUtils.cs
When we added support for casting strings to enum values in URLs, we didn't validate that the string was a valid member of the enum type.  This means that using a prefixed enum value would throw an exception if the value was not a member of the enum, but using the string form would not.
> Fix for not throwing and exception for an invalid enum value

- src/Microsoft.OData.Edm/Schema/EdmContainedEntitySet.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
EdmContainedEntitySet.Path should include the navProp. Currently, the path returned is the path of the parent.
> Fix path for EdmContainedEntitySet

- src/Microsoft.OData.Edm/Schema/EdmContainedEntitySet.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
Fix issue introduced in 7.4.2 that returned the incorrect path for a contained entity set.
> Fix path for EdmContainedEntitySet (#1118)

- src/Microsoft.OData.Client/BatchSaveResult.cs
- src/Microsoft.OData.Core/Json/JsonReader.cs
- src/Microsoft.OData.Core/Uri/NodeToStringBuilder.cs
- src/Microsoft.OData.Core/UriParser/Binders/EnumBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredAnnotationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserInjectionTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/CustomUriLiteralPrefixesTests.cs
* similar issue at: https://github.com/OData/WebApi/issues/1215
* Add StringComparison in String.Equal() method call.*
> Add StringComparison in String.Equal() method call

- src/Microsoft.OData.Core/Uri/ApplyClauseToStringBuilder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/ApplyBuilderTest.cs
```cs
[InlineData("http://gobbledygook/People?$apply=groupby((MyDog/Color,MyDog/Breed))")]
public void BuildUrlWithApply(string query)
{
var parser = new ODataUriParser(HardCodedTestModel.TestModel, ServiceRoot, new Uri(query));
ODataUri odataUri = parser.ParseUri();
Uri result = odataUri.BuildUri(ODataUrlKeyDelimiter.Parentheses);
Assert.Equal(query, Uri.UnescapeDataString(result.OriginalString));
}
```
Expected result http://gobbledygook/People?$apply=groupby((MyDog/Color,MyDog/Breed))
Actual result  http://gobbledygook/People?$apply=groupby((MyDog/Color/MyDog/Breed))
> fix build uri from groupby navigation property with many child structural proeprties

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Reader/ComplexValueReaderTests.cs
... is set to ensure that any metadata related checks are done if the flag is set, otherwise ignored.
*This pull request fixes issue #1157 .*
Fixes an issue where metadata related checks on null was done even if the validation settings explicit states that such checks should be done.
> Added check if the MessageReaderSettings.ThrowIfTypeConflictsWithMetadata

- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
This pull request adds test coverage to confirm that this issue has been fixed: https://github.com/OData/odata.net/issues/513
This change adds new test coverage for the scenario of selecting a property of a complex collection. For example: `$select=PreviousAddresses/City` where `PreviousAddress` is of type `Collection(Address)` and `Address` is a complex type.
Originally I thought this scenario was still broken, but it looks like it was fixed by an unrelated change almost two years ago. I think it would be prudent to add test coverage for this case to prevent future regressions.
> Adding test coverage for selecting complex collection properties

- src/Microsoft.OData.Core/UriParser/Parsers/SegmentArgumentParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SegmentKeyHandler.cs
- src/Microsoft.OData.Core/UriParser/Resolver/AlternateKeysODataUriResolver.cs
- src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/UnqualifiedODataUriResolverTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
*This pull request fixes issue #1153.*
*Include UnqualifiedODataUriResolve type when checking for mismatched keys count.*
> Fix SegmentKeyHandler to include UnqualifiedODataUriResolver proccessing

- src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs
- src/Microsoft.OData.Core/UriParser/CustomUriFunctions.cs
- src/Microsoft.OData.Core/UriParser/TypePromotionUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/CustomUriFunctionsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/FunctionCallBinderTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Scenario.Tests/UriParser/Filter/FilterTests.cs
*This pull request fixes issue #1155.*
*Update the FunctionCallBinder.GetUriFunctionSignatures() function accommodate enableCaseInsensitive logic. First scan by exact match for custom Uri functions, followed by case-insensitive match if case-insensitive is enabled. Ensure function name is correctly set in the message when exception is thrown. Updated related logic to make case-insensitive search work along with looking for best signature matched for overloaded functions.*
> Fix case insensitive search for custom URI functions.

- v7/_posts/odata features/2017-12-26-06-00-JsonBatch.md
JSON batch doc was missing due to the way the index.html parses for posts.
> Fixing missing JSON batch doc

- src/Microsoft.OData.Core/PropertyCacheHandler.cs
This pull request fixes issue #1172 .
Instead of using string builder moving everything to string concat.
> Avoid use of string builder in GetProperty to reduce string allocations.

- src/Microsoft.OData.Client/ODataAnnotatableExtensions.cs
*This pull request fixes issue #1145.*
the memory leak occurs because the Annotatable object can never be GC'd once an annotation is attached.
There is a change in semantics here, if SetAnnotation is called twice, the second will exception, rather than updating.
This was previously a condition which would cause an error anyway, as it would orphan the previously set annotation inside CreateLink()
At the moment the only codepath to SetAnnotation is 
Microsoft.OData.Client.Materialization.MaterializerNavigationLink.CreateLink(...) 
create link is only called by FeedAndEntryMaterializerAdapter, which has an existence guard, so this should never trigger the double-insert.
There is a possible change in behaviour as replaceing  Dictionary[annotatable] = annotation; with …
> fix memory leak #1145

- src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ExpressionLexerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
*This pull request fixes an issue for annotation parsing in ODL 7.4.2.*
*Annotation such as "@NS.myAnnotation" are not parsed correctly as Identifier token because lexer stops at the dot char during the traversing. This can be fixed by allowing to include dot chars for paring string token starting with "@", which could be either an parameter alias (w/o dots) or an annotation.*
> Include dots in parseIdentifier for annotation parsing

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/ODataBatchUtils.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/MultipartMixedBatchDependsOnIdsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/SingletonBatchRoundtripJsonLightTests.cs
*This pull request fixes issue #1187.*
*Skip reference url validation when it is in absolute url form and it is different from the baseUri.*
> Skip validation of reference uri that is different from base uri.

- src/Microsoft.OData.Client/DictionaryExtensions.cs
- src/Microsoft.OData.Client/EntityTracker.cs
Issues
This pull request fixes issue #1043 and is a resubmit of PR #1054 with CR comments addressed.
Description
Replaces EntityTracker's internal Dictionary<> objects with thread-safe ConcurrentDictionary<> ones.
Checklist (Uncheck if it is not completed)
>   Fix threadsafety in DataServiceClient EntityTracker's internal dictionary 

- index.html
*This pull request updates the odata.net gh-page doc root index to serve V7 content.*
*Updates for using V7 categories & content.*
> use V7 ODL content as the default site for on odata.github.io

- src/Microsoft.OData.Core/ODataParameterReaderCore.cs
- src/Microsoft.OData.Edm/Schema/Interfaces/IEdmOptionalParameter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs
* OData parameter reader should not throw exception if missing the optional parameter.
> Fix issue #1216, parameter reader should not throw exception if missing optional parameter

- src/CodeGen/ODataT4CodeGenerator.cs
- src/CodeGen/ODataT4CodeGenerator.tt
- src/CodeGen/ODataT4CodeGenerator.ttinclude
- test/FunctionalTests/Tests/DataServices/UnitTests/DesignT4UnitTests/ODataT4CodeGeneratorTestDescriptors.cs
Add another field to the configuration class to specify the filepath.
This pull request fixes issue #1220.
This pull request introduces another parameter to the client code generator that specifies a temporary file path where the metadata can be stored for the client proxy classes. Alternatively, if nothing is specified, it gets stored in a string literal. 
Previous unit tests passed with nothing specified in the parameter.
> Add an optional file path for large metadata files

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Uri/ODataUri.cs
- src/Microsoft.OData.Core/Uri/ODataUriExtensions.cs
- src/Microsoft.OData.Core/UriParser/ODataQueryOptionParser.cs
- src/Microsoft.OData.Core/UriParser/ODataUriParser.cs
- src/Microsoft.OData.Core/UriParser/UriQueryConstants.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/TopAndSkipBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FullUriFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/TopAndSkipFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/CaseInsensitiveBuiltinIdentifierTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataQueryOptionParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1272.*
* Add supporting for the $index query option.
> Support $index  query option in OData v4.01

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsModel.cs
- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsOperation.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
* Issue #855: enable out of line optional parameter works
If we create a non-optional (general) parameter, and apply the “OptionalParameter” term on it, we also can get the similar result:
```C#
var requiredParam = new EdmOperationParameter(function, "requiredParam", stringTypeReference);
IEdmRecordExpression optionalParameterRecord = new EdmRecordExpression(.., new EdmPropertyConstructor("DefaultValue", new EdmStringConstant("Smith")));
EdmVocabularyAnnotation annotation = new EdmVocabularyAnnotation(requiredParam, CoreVocabularyModel.OptionalParameterTerm, optionalParameterRecord);
annotation.SetSerializationLocation(model, EdmVocabularyAnnotationSerializationLocation.OutOfLine);
model.SetVocabularyAnnotation(annotation);
```
The above will get the result same as the following codes: …
> Issue #855: enable out of line optional parameter works

- src/CodeGen/ODataT4CodeGenerator.cs
* Pass the policheck for auto code gen string
* The auto code gen string separate "function" to "Fu" and "nction" in different link.
* "FU" can't pass the policheck.
* This PR is to adjust it.
> Modify the codegen auto code string to pass policheck

- src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
*This pull request update the DerivedTypeConstraint Term in validation vocabulary.*
* OData TC has a update for DerivedTypeConstraint Term, see: https://github.com/oasis-tcs/odata-vocabularies/pull/27
This PR is to update the term defined in the Edm library.
> Update the DerivedTypeConstraint term in Validation vocabulary

- src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
*This pull request updates the validation vocabulary based on oasis tc odata vocabulary:
https://issues.oasis-open.org/browse/ODATA-1222 
* OASIS has added two new terms to the OData Validation vocabulary to specify the minimum or maximum number of items in a collection.
We should add those to the Validation Vocabulary exposed by ODL:
```xml
<Term Name="MaxItems" Type="Edm.Int64" Nullable="false" AppliesTo="Collection">
<Annotation Term="Core.Description" String="The annotated collection must have at most the specified number of items." />
</Term>
<Term Name="MinItems" Type="Edm.Int64" Nullable="false" AppliesTo="Collection">
<Annotation Term="Core.Description" String="The annotated collection must have at least the specified number of items." />
</Term>
```
This PR is also add the Term …
> Add AllowedTerms/MinItems/MaxItems to Validation vocabulary

- test/PerformanceTests/ComponentTests/Microsoft.OData.Performance.ComponentTests.csproj
*This pull request fixes issue the build issue for performance.
With the PR https://github.com/OData/odata.net/pull/1309 merged, it will make the performance build failure as:
* 
That's because the office performance build reference to the Microsoft.Spatial nuget package which doesn't include new added files.
This PR is to re-add the files into the performance office build.
> Add the spatial factory and related files into office performance build

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
This pull request fixes the following issues related to IN operator:
- https://github.com/OData/odata.net/issues/1313: Invalid Json due to single quotes.
- https://github.com/OData/WebApi/issues/1596: Invalid Json due to Guid literals.
*Fix the escaped single quote for collection of strings for IN operator*
*Fix for collection of Guid literals for IN operator*
> IN operator fixes for escaped single-quote and Guid literals

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularyModel.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/ODataPathParserTypeCastTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request is part of Union type supporting.*
* To parse the type cast on a property (structural or navigation property), the allowed type case segment should within the Validation vocabulary [DerivedTypeConstraint](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml#L91-L94) annotation if it applied on such property, otherwise the Uri parse should throw exception.
> Uri parsing on type cast on property allowed in validation vocabulary

- src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj
- src/Microsoft.OData.Core/Build.NetStandard/Microsoft.OData.Core.NetStandard.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Uri/ApplyClauseToStringBuilder.cs
- src/Microsoft.OData.Core/Uri/ExpressionConstants.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ExpandTransformationNode.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/TransformationNodeKind.cs
- src/Microsoft.OData.Core/UriParser/ODataQueryOptionParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/ApplyBuilderTest.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriQueryExpressionParserTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1344.*
Added parsing and binding for expand inside $apply.
For example $apply=expand(Sales, filter(Amount gt 10), expand(Customers))
> expand transformation in $apply

- src/Microsoft.OData.Core/UriParser/Binders/DottedIdentifierBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/EnumBinder.cs
- src/Microsoft.OData.Core/UriParser/UriEdmHelpers.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Thrown exception ODataException : 'The string 'Fully.Qualified.Namespace.ColorPattern'Red'' is not a valid enumeration type constant.' when use custom ODataUriResolver.
Pass resolver parameter in method parse enum type.
> fix parse fully qualified enum with resolver

- src/Microsoft.OData.Core/IWriterValidator.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataWriterCore.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/PropertyCache.cs
- src/Microsoft.OData.Core/PropertyCacheHandler.cs
- src/Microsoft.OData.Core/PropertyMetadataTypeInfo.cs
- src/Microsoft.OData.Core/PropertySerializationInfo.cs
- src/Microsoft.OData.Core/WriterValidationUtils.cs
- src/Microsoft.OData.Core/WriterValidator.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriterDerivedTypeConstraintTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/PropertyCacheHandlerTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request continues on Union type feature.
Enable writing derived type constraint validation on:
1. Resource
2. Nested resource info
3. Edm.PrimitiveType property
> Add the writing derived type constraint validation

- src/Microsoft.OData.Core/SelectedPropertiesNode.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/ExpandAndSelectPathExtractingTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/SelectedPropertiesNodeTests.cs
PR #1286 fixed a number of issues related to how non-selected expanded navigation properties were represented in the ContextUrl. However, in the new code that attempts to determine if the entire subtree is selected, it looks only at direct children to see if they are navigation properties and not deeper.  
For example, prior to this fix the following URL would return a SelectExpandNode with SelectionType=PartialSubtree.
Employees?$expand=ns.Manager/DirectReports
After the PR, this is correctly returned as EntireSubtree
The primary purpose of this PR is to set whether the SelectNode is entiresubtree based on a deep traverse of child paths, rather than only looking at direct children.
Other changes, in addition to new tests, include some test clean-up as well as code optimizations around …
> Fix SelectExpandNode for navigation properties on derived/complex types

- src/Microsoft.OData.Core/UriParser/SemanticAst/CollectionConstantNode.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/CollectionConstantNodeTests.cs
*This pull request fixes issue #1373 .*
CollectionConstantNode did not account for null values in the collection even if the item type is nullable. 
I would like to test the nightly build against a sample WebAPI service to ensure that the filter works correctly all the way through for constant collections with null values in it.
> Allow null values in constant collections

- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyClause.cs
- src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/ExapndOptionFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriQueryExpressionParserTests.cs
*This pull request fixes issue #1368 * also adds a few tests for ApplyBinder (it wasn't covered in original implementation)
Collecting aliases generated in compute() transformation to make them visible for following transformations and/or query options ($orderby, $filter)
> Make aliases created in compute() transformation visible for following transforms/query options

- src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj
- src/Microsoft.OData.Core/Build.NetStandard/Microsoft.OData.Core.NetStandard.csproj
- src/Microsoft.OData.Core/DerivedTypeValidator.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataReaderCore.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/PropertyAndAnnotationCollector.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataReaderDerivedTypeConstraintTests.cs
*This pull request fixes enable the resource reading derived type constraint annotation validation.*
*Enable the resource reading derived type constraint annotation validation.*
> Enable reading validation for derived type constraint annotation

- src/Microsoft.OData.Core/UriParser/Binders/MetadataBindingUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
ConstantNode ODataEnumValue not valid property LitralText without quotes.
Therefore ODataUriExtensions.BuildUri produce not valid odata query.
> fix build uri with filter by enum

- src/Microsoft.OData.Core/UriParser/Binders/LiteralBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/MetadataBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes issue #1385 and #1164 .*
This pull request modifies the bind method for the InNode to handle collection constants with a special method to support for both parentheses and brackets for a collection constant. 
Previously, bracketed collection constants were parsed as constant nodes but the In operator is only compatible with collection constant nodes.  Now, we use a different method to bind literals for the InNode that parses bracketed collection as collection nodes as well.
The downside is that previously we allowed custom implementations to bind literals by overriding the bind method but that will not be possible for the In operator.
For the generation, we always returned the literal's text. Therefore, we will support both parentheses and brackets for the …
> Support parantheses and brackets in a CollectionConstantNode for IN operator

- src/Microsoft.OData.Core/Buffers/BufferUtils.cs
- src/Microsoft.OData.Core/Buffers/ICharArrayPool.cs
- src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj
- src/Microsoft.OData.Core/Build.NetStandard/Microsoft.OData.Core.NetStandard.csproj
- src/Microsoft.OData.Core/Json/JsonReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightInputContext.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue https://github.com/OData/odata.net/issues/1024.*
* Introduce the array pool
* Fix the buffer double problem for large object JSON payload
> Improve Json reader buffer logic

- src/Microsoft.OData.Core/Evaluation/ODataMetadataContext.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataWriterCore.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/ReaderValidationUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataMissingOperationGeneratorTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
ODL supports reading/writing response payloads, but not request payloads.
OData 4.01 adds support for delta updates, which requires reading/writing delta request payloads.
When writing a request:
-writing links (navlink, deltalink) are not allowed
When reading a request:
-navlinks/delta links should be ignored
-conventional metadata should not be materialized
- [ x] *Test cases added*
> Support reading/writing delta request payloads

- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyClause.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes one more edge case from issue #1368.*
Collecting aliases generated in compute() transformation followed by groupby to make them visible for following transformations and/or query options ($orderby, $filter)
> Ensure that we could use aliases created in compute() in groupby

- src/Microsoft.OData.Core/Uri/NodeToStringBuilder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
*This pull request fixes issue #1415 .*
The problem in the `NodeToStringBuilder` appears when the filter query contains a condition of type `nullable boolean` such as `any` as a part of `BinaryOperatorNode` with another `BinaryOperatorNode` as another part. The latter `BinaryOperatorNode` is converted into `ConvertNode` in that case, and it's not tested for the priority of the internal binary operator.
> Fix issue #1415, keep conditions priority for queries with Convert node in NodeToStringBuilder

- src/Microsoft.OData.Core/Buffers/BufferUtils.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/BufferUtilsTests.cs
*This pull request fixes issue #1410.*
* Enable to validate the buffer size returned from the array pool.
> Validate the buffer returned from the pool

- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/JsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonValueUtilsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/NonIndentedTextWriterTests.cs
* Improve the json writer process for the binary/byte[].
* Improve the json writer process for the binary/byte[].
> Change to use buffer when writing binary/byte[]

- src/Microsoft.OData.Core/Buffers/BufferUtils.cs
- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/JsonWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
- test/FunctionalTests/Tests/DataOData/Tests/OData.Writer.Tests/Json/JsonValueUtilsTests.cs
* Use the array pool in Json writer
* Use the array pool in Json writer
> Use the array pool in Json writer

- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyClause.cs
- src/Microsoft.OData.Core/UriParser/Binders/BindingState.cs
- src/Microsoft.OData.Core/UriParser/Binders/EndPathBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectExpandSemanticBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectPathSegmentTokenBinder.cs
- src/Microsoft.OData.Core/UriParser/ODataQueryOptionParser.cs
- src/Microsoft.OData.Core/UriParser/SyntacticAst/PathToken.cs
- src/Microsoft.OData.Core/UriParser/SyntacticAst/RangeVariableToken.cs
- src/Microsoft.OData.Core/UriParser/Visitors/SelectPropertyVisitor.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/EndPathBinderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/ExpandBinderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/SelectBinderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1426.*
*Makes dynamic properties generated in $apply and $compute visible for query options evaluated after them ($select, $filter, $expand, $orderby etc.)*
Also, current implementation doesn't block queries like
`$apply=groupby((Field1))&$filter=Fiield2 eq 1` during parsing and binding that leads to cryptic exceptions during IQueryable building
> Properties defined in $compute and $apply can be used in a following query options ($select, $compute, $filter or $orderby)

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReaderNestedResourceInfo.cs
- src/Microsoft.OData.Core/ODataReaderCore.cs
- src/Microsoft.OData.Core/ReaderValidationUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/PropertyAndValueJsonLightReaderIntegrationTests.cs
*This pull request fixes issue #1260 *
Previously, OData 7.x would not throw an exception during serializing a null value for a collection of non-nullable complex type. Now, OData rightly throws an exception.
> Throw error when null value passed for collection of non-nullable complex type

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
*This pull request fixes issue #1465.*
*We weren't handling resolving members of an enumType when resolving target. Now we do.*
None.
> Fix #1465: Support validating out-of-line annotations targeting enumMember

- src/Microsoft.OData.Edm/Csdl/CsdlConstants.cs
- src/Microsoft.OData.Edm/Csdl/CsdlReader.cs
- src/Microsoft.OData.Edm/Csdl/CsdlWriter.cs
- src/Microsoft.OData.Edm/Csdl/SchemaWriter.cs
- src/Microsoft.OData.Edm/Schema/EdmConstants.cs
- src/Microsoft.OData.Edm/Validation/EdmValidator.cs
- src/Microsoft.OData.Edm/Validation/ValidationRuleSet.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/EdmVersionTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1470.*
Support reading and writing Version=4.01 in Edmx
> Support reading/writing Edmx with Version=4.01

- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandOptionParser.cs
- src/Microsoft.OData.Core/UriParser/SyntacticAst/ExpandTermToken.cs
- src/Microsoft.OData.Core/UriParser/SyntacticAst/SelectExpandTermToken.cs
- src/Microsoft.OData.Core/UriParser/SyntacticAst/SelectTermToken.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SelectExpandOptionParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SelectExpandParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SyntacticAst/SelectTermTokenTests.cs
Reason: 
* Because 
`$select=1($expand=2)` can use `$select=1&$expand=1/2` to replace. 
So far, the meaning to support $expand in $select is not clear.
to avoid ambiguous, this PR is to remove $expand in $select from Syntactic part.
> Remove the nested expand supporting in $select

- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchReader.cs
- src/Microsoft.OData.Core/ODataBatchReader.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/MultipartMixedBatchDependsOnIdsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/ODataJsonBatchAtomicityGroupTests.cs
Prior to the changes for JSON Batch merged in 7.4, we did not enforce uniqueness of ContentID outside of a changeset in MultipartMixed batch format.
The OData 4.0 spec states that, within a changeset, each entry must have a ContentID and that content-id MUST be unique across the batch (not just the changeset). It doesn't mention ContentIds outside of the changeset, but the previous statement implies that the scope of uniqueness is the entire batch.  In OData 4.01 we tightened the wording to clarify that all ContentIds within the batch must be unique across the batch. This is especially important for JSON Batch responses, which can come back in any order so the ContentId is required to associated a response with a request, but the statement is made as a format-independent statement in the …
> Dont Enforce ContentID Uniqueness outside ChangeSet in MultipartMixed

- src/Microsoft.OData.Core/MessageStreamWrapper.cs
Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead #1514
Invoke Stream.FlushAsync redirect to MessageStreamWrappingStream.Flush
> fix async message write

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandOptionParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SelectExpandParserTests.cs
*This pull request fixes issue #1493.*
* Enable $expand=* after the complex type.
> Fix #1493: Enable the $expand=* after the complex type

- src/Microsoft.OData.Core/ODataContextUrlInfo.cs
- src/Microsoft.OData.Core/SelectedPropertiesNode.cs
- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyClause.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/SelectExpandClauseExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataContextUriBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/FullPayloadValidateTests.cs
Fixes to @odata.context when $select/$expand/$apply/$compute work together:
* Support for $apply inside $expand
For `$expand=Sales($apply=aggregate(Amount with sum as Total))` @odata.context will be `$metadata#Products(Sales(Total))` (https://issues.oasis-open.org/browse/ODATA-1307)
* $select after $apply and $compute keeps only fields in $select
> Correct @odata.context for combination of $select/$apply/$compute/$expand

- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterSettingsTests.cs
This pull request fixes metadata selector feature if the message writer is used to create an odata writer. 
The copy method for the message writer settings was not copying over the metadata selector property.
> Copy over metadata selector when creating a copy of messagewritersetting

- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
As part of bringing OData 4.01 to committee specification and on towards publication as an OASIS standard, the OASIS TC updated the Core vocabulary to renamed:
"ModificationException"=>"DataModificationException"
"ModificationExceptionType"=>"DataModificationExceptionType"
"ModificationOperationKind"=>"DataModificationOperationKind"
This change updates our vocabulary to align with the new naming.
> Fix naming of DataModification* terms and types in vocabulary.

- src/Microsoft.Spatial/GmlWriter.cs
- test/FunctionalTests/Microsoft.Spatial.Tests/Build.NetFramework/Microsoft.Spatial.Tests.csproj
- test/FunctionalTests/Microsoft.Spatial.Tests/GmlWriterTests.cs
- test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.NetCore.csproj
* [GML - Geography Markup Language](https://gdal.org/drivers/vector/gml.html)
The GmlFormatter Write method is appending the "gml" prefix to the "srsName" attribute.
The "srsName" attribute should not have the "gml" prefix based on  [GML - Geography Markup Language](https://gdal.org/drivers/vector/gml.html)
* remove the unused package reference to "FluentAssertions"
> Fix issue #1547: Remove the prefix for SrsName in GmlWriter

- tools/CustomMSBuild/After.Common.targets
* Fix #1540
MSDN says:
- AssemblyVersion:
Specifies the version of the assembly being attributed.
- AssemblyFileVersion:
Instructs a compiler to use a specific version number for the Win32 file version resource. The Win32 file version is not required to be the same as the assembly's version number.
- AssemblyInformationalVersion:
Defines additional version information for an assembly manifest.
---
Before 7.6.1-beta, the OData library version has the following pattern for all above three version:
` *Version = {Major}.{Minor}.{BuildNumber}.{ Now.Year - 2017 + 1}{MM}{DD} `
From the issue #1540, the AssemblyVersion should  stop changing between minor releases. So, this PR is changing ‘AssemblyVersion’ as
`AssemblyVersion = {Major}.{Minor}.{BuildNumber}`
Meanwhile, leave other two unchanged. …
> Change AssemblyVersionAttribute without revision

- test/PackageTests/Microsoft.OData.Tests.Nuget.Core/HttpWebRequestMessage.cs
This fixes the build failure that was happening for package testing for OData.
> Update HttpWebRequestMessage.cs to enable TLS 1.2

- src/Microsoft.OData.Client/ALinq/UriWriter.cs
- src/Microsoft.OData.Client/ProjectionPlanCompiler.cs
- src/Microsoft.OData.Core/ODataBatchReaderStreamBuffer.cs
- src/Microsoft.OData.Edm/Validation/ValidationRules.cs
- src/Microsoft.Spatial/CoordinateSystem.cs
- src/Microsoft.Spatial/LexerToken.cs
It's currently not possible to build the OData.Net45 solution due to the error below.
> Because the behavior of 'int.ToString()' could vary based on the current user's locale settings, replace this call in 'UriWriter.VisitOperationInvocation(QueryableResourceExpression)' with a call to 'int.ToString(IFormatProvider)'. If the result of 'int.ToString(IFormatProvider)' will be displayed to the user, specify 'CultureInfo.CurrentCulture' as the 'IFormatProvider' parameter. Otherwise, if the result will be stored and accessed by software, such as when it is persisted to disk or to a database, specify 'CultureInfo.InvariantCulture'.
> Fix build errors by adding IFormatProvider

- src/Microsoft.OData.Edm/Csdl/SerializationExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
This pull request fixes issue #1587 .
- GetNamespace now returns null if the namespace doesn't have an alias, as advertised in the documentation (the actual behavior was to throw a KeyNotFoundException instead, as it was calling VersioningDictionary.Get).
- GetNamespace now returns null if the model doesn't define any alias (the actual behavior was to throw NullReferenceException, as GetAnnotationValue returned null and it wasn't checked).
> Fixes for Csdl.GetNamespaceAlias extension method.

- src/Microsoft.OData.Core/Evaluation/ODataMetadataSelector.cs
- src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
- src/Microsoft.OData.Core/JsonLight/JsonLightMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonMinimalMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonNoMetadataLevel.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectTreeNormalizer.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/PathSelectItem.cs
- src/Microsoft.OData.Core/UriParser/SyntacticAst/SelectTermToken.cs
- src/Microsoft.OData.Core/UriParser/TypePromotionUtils.cs
- src/Microsoft.Spatial/Microsoft.Spatial.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/ExpandAndSelectPathExtractingTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/SelectTreeNormalizerTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
This PR allows multiple select paths to the same property if there are no query options
When we implemented select options, we disallowed multiple select paths in the select list to the same property. This was a breaking change. This change allows multiple select paths to the same property as long as none of the instances of that property contain any select options.
Four added tests are disabled due to a known issue--selecting properties of a complex type include that complex type in the select list.  Once that issue is resolved, the two disabled tests can be re-enabled.
> Allow duplicate properties in $select with no select options

- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/ODataPathParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/ODataPathParserTypeCastTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
This PR is related to issue #1594. Thanks.
This PR is to enable the namespace alias for operation in the Uri parser.
> Support the namespace alias for operation in Uri parser

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/NodeAssertions.cs
…n the string value
*This pull request fixes issue #1623. #1636 *
* a filter clause like `?$filter=propertyName in ('a','x,y,z')` can't work because the old codes simply split the literal using ','.
* backslash in single quote string should escape to double backslash
* backslash in double quote string should un-escape
This PR fix this issue
> Fix issue #1623: In operators fails on string collection with commas in the string value

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes issue #1651.*
Enable In operator to work with "null" value.
For example: $filter=SSN in (null).
> Fix issue#1651, In operator with null not working

- src/Microsoft.OData.Client/Serialization/Serializer.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1643 .*
Allow OData Client's Serializer.GetKeyString to receive a DataServiceContext Object and an IDictionary instead of a concrete Dictionary. Since Dictionary implements IDictionary, I have updated the method as follows
public static string GetKeyString(DataServiceContext context, IDictionary<string, object> keys)
{
// Implementation
}
> Replace Dictionary with IDictionary

- src/Microsoft.OData.Core/Json/JsonWriter.cs
Two separate but simultaneous PRs added Dispose functionality to JsonWriter. One used an explicit method interface implementation (IDisposable.Dispose) and the other a direct implementation (Dispose), so there wasn't a conflict when merging, but it means that a caller directly calling Dispose() will get a different set of resources freed than if called through the interface (i.e., in a Using statement). Neither method cleans up all of the resources.
This PR merges the two definitions so that all resources will be freed regardless of how Dispose is called.
> Combine Dispose methods on JsonWriter

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/UriPathParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriPathParserTests.cs
This pull request fixes the escape function uri. 
The previous implementation of escape function uri was not able to distinguish if a request intended to use an escape function or a key-value began with a  ':' when the key is expressed as a segment. Therefore, the parsing would fail for the requests with key as segment with value starting with ':' with an error that no escape function was found for the type. 
Now, we change how we parse segments and give precedence to an escape function if one exists for the type otherwise treat it as a key-value. 
This pull requests 
Release notes need to mention these changes when merged.
> One drive escape function for key as segment staring with colon

- src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectPathSegmentTokenBinder.cs
- src/Microsoft.OData.Core/UriParser/Parsers/FunctionOverloadResolver.cs
- src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
This pull request fixes issue #1392 
This PR removes some of the expensive LINQ calls without breaking the public interface. 
HasAny previous for enumerables - 0.3372341
HasAny now for enumerables - 0.2167854
I would like to add tests for the changes once the initial work is reviewed. More performance improvement related data should be attached with this PR.
> Perf improvements in FunctionOverloadResolver

- src/Microsoft.OData.Client/BaseSaveResult.cs
- src/Microsoft.OData.Client/DataServiceRequest.cs
- src/Microsoft.OData.Client/Materialization/HttpWebResponseMessage.cs
- src/Microsoft.OData.Client/Util.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs
*This pull request fixes issue #843.*
*Improving `DataServiceClientException` messages. Currently `DataServiceClientException.Message` property is set to a serialized Odata response error which means the consumer has to parse it before use. Since changing the property `DataServiceClientException.Message`  is a breaking change we would not like to do that at this point in time. Instead, `DataServiceClientException.InnerException` has been set with `Microsoft.OData.ODataErrorException`. This makes it easier to get `Microsoft.OData.ODataError` object which can be useful in getting the error message *
> Fixing issue #843

- src/Microsoft.OData.Client/DataServiceClientFormat.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/packages.config
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/DataServiceContextUtil.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientPropertyTrackingTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientSerializerTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/CustomizedHttpWebRequestMessage.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceClientFormatTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceContextTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceRequestTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ODataMessageReadingHelperTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ODataMessageWritingHelperTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Serialization/ODataWriterWrapperUnitTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/T4/ODataT4CamelCaseTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientCSharpRegressionTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientErrorHandlingShortIntegrationTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientShortIntegrationRegressionTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/ClientRegressionTests.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/EntitySetResolverTests.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateManagementTests.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/UpdateTests.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/VersionedRequests.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/medialinkentries.vb
*This pull request fixes issue #1003 *
*Introduces a new action to load the metadata from the metadata Url and set the ServiceModel. The new action runs to load the metadata if the metadata had not been set before (directly by calling `context.Format.UseJson(ServiceModel)` or using a user provided Hook `context.Format.LoadServiceModel`.
This would allow people to use the syntax below to use this method in their code when not using the code generation tools or when they want to use the latest model in their code. E.g when developing new API's or when working on API's that do not publish breaking changes. 
This *does not negatively impact client code generated using the tools* (codegen and connected service) as they provide  the ServiceModel directly or provide a Hook using the exposed …
> Fix DataServiceContext can't work with POCO's due to Missing IEdmModel

- src/Microsoft.OData.Client/Build.NetStandard/project.json
- src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
- src/Microsoft.OData.Client/Microsoft.OData.Client.NetStandard.VS2017.csproj
- src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
- test/FunctionalTests/Microsoft.OData.Client.Tests/Metadata/ClientTypeUtilTests.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.Netcore.csproj
- test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
*This pull request fixes issue #1332 and #543*
OData client supports 3 ways of defining an entity key:
1. ID
2. type+ID
3. KeyAttribute
Currently, the client does not support the use of the Key  attribute annotation on a type property when using POCO classes.  Like below: 
<pre>
//POCO class
public class ProductDetails
{
[Key]
public string NonStandardId { get; set; }
public string OtherField { get; set; }
}</pre>
This PR adds support for the use of the Key attribute on a primary key field. 
> Key attribute support on Primary Key field when using POCO classes with the client

- src/Microsoft.OData.Client/BatchSaveResult.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/ODataMessageWritingHelper.cs
- src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
- src/Microsoft.OData.Client/SaveChangesOptions.cs
- src/Microsoft.OData.Client/Util.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsyncMethodTests.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/EntitySetResolverTests.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MaterializationTest.vb
*This pull request fixes issue #1446 .*
OData Client exclusively supports Absolute URIs in batched requests. We currently don’t have a way to ask the Client to create the batch requests with RelativeURIs instead of Absolute URIs.
This PR allows the customer to create batch requests with relative URIs as follows
```
dsc.SaveChangesAsync(SaveChangesOptions.BatchWithIndependentOperations | SaveChangesOptions.UseRelativeUri);
dsc.ExecuteBatchAsync( SaveChangesOptions.UseRelativeUri | SaveChangesOptions.BatchWithIndependentOperations, batchRequests); 
dsc.ExecuteBatchAsync( SaveChangesOptions.UseRelativeUri | SaveChangesOptions.BatchWithSingleChangeset, batchRequests); 
```
Also we can invoke synchronous operations
```
dsc.SaveChanges(SaveChangesOptions.BatchWithIndependentOperations | …
```
> Allow Batch relative URIs in OData Client

- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
*This pull request fixes issue #1671 .*
Based on the docstring for `FindDeclaredOperationImports` function, an empty enumerable should be returned if no operation imports are found.
```<returns>All operation imports that can be found by the specified name, returns an empty enumerable if no operation import exists.</returns>```
In a scenario where the method is invoked against an Edm model that has no entity container, a `null` is returned instead. This PR addresses that issue such that all execution paths for the method always return a non-null enumerable.
> Return empty enumerable from FindDeclaredOperationImports instead of null 

- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
Reverts OData/odata.net#1696 to first troubleshoot why rolling build broke after I merged to master
> Revert "Return empty enumerable from FindDeclaredOperationImports instead of null "

- src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
*This pull request fixes issue #1671 .*
Based on the docstring for `FindDeclaredOperationImports` and `ResolveOperationImports` functions, an empty enumerable should be returned if no operation imports are found.
```<returns>All operation imports that can be found by the specified name, returns an empty enumerable if no operation import exists.</returns>```
In a scenario where the method is invoked against an Edm model that has no entity container, a `null` is returned instead. This PR addresses that issue such that all execution paths for the method always return a non-null enumerable.
Previous [PR](https://github.com/OData/odata.net/pull/1699) did not include a fix for `ResolveOperationImports` and that caused the build to fail after merge to master
> Return empty enumerable from FindDeclaredOperationImports and ResolveOperationImports

- src/Microsoft.OData.Edm/Build.Net35/Microsoft.OData.Edm.NetFX35.csproj
- src/Microsoft.OData.Edm/Build.NetStandard/Microsoft.OData.Edm.NetStandard.csproj
- src/Microsoft.OData.Edm/Csdl/CsdlConstants.cs
- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaWriter.cs
- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSerializationVisitor.cs
- src/Microsoft.OData.Edm/EdmModelVisitor.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
- src/Microsoft.OData.Edm/Validation/ExpressionTypeChecker.cs
- src/Microsoft.OData.Edm/Validation/InterfaceValidator.cs
- src/Microsoft.OData.Edm/Vocabularies/EdmExpressionEvaluator.cs
- src/Microsoft.OData.Edm/Vocabularies/Expressions/EdmAnnotationPathExpression.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
…cases
We have CsdlSemanticAnnotationPathExpression, but without "EdmAnnotationPathExpression"
* Add the EdmAnnotationPathExpression class
1) So, now, we can annotation an element using AnnotationPath
2) we can read the AnnotationPath (It's already supported).
> Add EdmAnnotationPathExpression class and related verification, test case

- src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectPathSegmentTokenBinder.cs
- src/Microsoft.OData.Core/UriParser/Parsers/FunctionOverloadResolver.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ModelBuildingHelpers.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/FunctionOverloadResolverTests.cs
This pull request fixes issue reported by Microsoft Graph
This is an experiment. The nuget package from this build will be used to verify if the problem stops from happening.
> Fix null reference error when matching binding type

- src/Microsoft.OData.Core/ODataMessageWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
Exchange reports an issue that:
**Looks like there are certain conditions under which ODataMessageWriter is not disposing the stream returned by IODataResponseMessage.GetStream. Are there any known bugs in this area?**
After investigation, we found this edge case. This is an edge case only happens when customer creates the message writer without writing anything. However, if there's some control to prevent the
message writer from writing anything, the outside stream still needs to
dispose. This PR is to resolve this edge problem.
> ODataMessageWriter can't dispose the stream if there's no write method called

- src/Microsoft.OData.Client/DataServiceClientFormat.cs
- src/Microsoft.OData.Client/TypeResolver.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientOpenTypeUpdateTests.cs
*This pull request fixes issue #1726.*
This PR fixes a bug  in OData client library where open types `IsOpen` property get initialized to `false` specifically in a Post scenario where no query operation to the service has been done prior. This later causes an exception to be thrown during serialization since the owning type isn't recognized as open and the undeclared property won't also be interpreted as an open property.
The fix involved moving the code for populating the `EdmStructuredSchemaElements` property of `ClientEdmModel` to a position right after the service model has been loaded
Bug was inadvertently introduced in this [PR](https://github.com/OData/odata.net/pull/161) and only occurs if query operation is done prior to a post operation.
Another user dissected and raised the …
> Fix bug where open types are not identified as such during serialization

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/AsyncBatchRoundtripJsonLightTests.cs
*This pull request fixes #1737 *
the `ODataJsonLightBatchWriter`  always uses absolute uris in batch requests as if the payload uri option was set to `AbsoluteUri`, even when the uri option is set to `RelativeUri` or `AbsoluteUriUsingHostHeader`. This PR correctly handles the two latter options and makes it consistent with the `ODataMultipartMixedBatchWriter`
I would like to get a confirmation on how the different uri options should be handled (in particular the `AbsoluteUriUsingHostHeader` option).
Given the URI `https://host:1234/path/service/People(1)` and method `GET`, this PR implement the following behavior:
- `BatchPayloadUriOption.AbsoluteUri`:
```js
{
"method": "GET",
"url": "https://host:1234/path/service/People(1)"
}
```
- `BatchPayloadUriOption.AbsoluteUriWithHostHeader`: …
> Add support for relative and absolute uris in json batch requests

- src/Microsoft.OData.Client/BaseSaveResult.cs
*This pull request fixes #1756.*
*Fix error while reading error response that do not conform to OData spec.*
*Recently we enable `OData Client` to deserialize OData `Error response` on behalf of the users into `ODataError `object. Before this change some users were sending back error response which can not be deserialized into `ODataError `object. To take care of this case, this fix ensures that this change do not break their code and instead send back the string response as is as it was the case initially*
> Fix #1756 - Reading OData Error Response in OData Client

- src/Microsoft.OData.Core/UriParser/SemanticAst/SelectExpandClause.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/SelectExpandClauseExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Build.NetFramework/SelectExpandClauseExtensionsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/NavigationPropertyOnComplexTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandClauseExtensionsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/SelectedPropertiesNodeTests.cs
Fix Select expand and odata context issue
*This pull request fixes issue #1574 and #1580 
Fixed the select and expand list 
Fixed odata context which uses select and expand
> Fix Select Expand Issue of selecting all navigation properties for Full Metadata request and fixing Odata Context

- src/Microsoft.OData.Client/ClientEdmModel.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ClientEdmModelTests.cs
*This pull request fixes issue #1581.*
Since Web API OData V5.5-beta, it is allowed to:
1. define abstract type (entity & complex) without any properties.
But in this case, when you define an abstract complex type without any properties  an exception is thrown. 
> Support for abstract complex types with no properties

- src/Microsoft.OData.Client/BatchSaveResult.cs
- src/Microsoft.OData.Client/DataServiceClientFormat.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/SaveChangesOptions.cs
- src/Microsoft.OData.Client/Util.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsyncMethodTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DataServiceClientFormatTests.cs
Currently Odata Client only supports multipart/mixed batch requests while ODL has support for both json batch requests and multipart/mixed batch requests. We are adding support for OData Json Batch Requests in OData Client.
We are adding a new `SaveChangesOption` flag named `UseJsonBatch`. When you add the flag in batch requests when calling SaveChangesAsync, the request and response will have Content-Type as `application/json`
> Add support for Json Batch Requests in Odata Client

- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/DataServiceQuery.cs
- src/Microsoft.OData.Client/DataServiceQueryOfT.cs
- src/Microsoft.OData.Client/DataServiceQuerySingleOfT.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1250.*
The DataServiceContext, DataServiceQuery, DataServiceQueryOfT and DataServiceQuerySingleOfT classes cannot be mocked as they are. In this PR, I have made these classes' public methods and properties virtual to support mocking. 
Virtual methods can be mocked using any Mock Framework. Example, using the Moq Framework
You can mock the <code>AddObject() </code> method in the <code> Microsoft.OData.Client.DataServiceContext </code> class like below: 
<pre>
using Moq; 
using Xunit
namespace SampleMock
{
/// How to mock the DataServiceContext class methods using moq framework example. 
public class DataServiceContextMockTests 
{ 
[Fact] 
public void VerifyIfDataServiceContextAddObjectMethodIsMockable() 
{ 
string str = "user"; 
Mock<DataServiceContext> …
> Support Mocking in OData Client.

- src/Microsoft.OData.Core/ODataMessageWriter.cs
- src/Microsoft.OData.Core/ODataWriter.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/ODataJsonLightInheritComplexCollectionWriterTests.cs
*This pull request fixes issue #1604.*
*This pull request fixes issue #1776.*
*Some of the async fluent APIs incorrectly call lower level APIs.*
> Fix how composite async methods invoke lower level methods.

- src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/ParameterAliasFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
*This pull request fixes issue reported on OData Web API project https://github.com/OData/WebApi/issues/2051.*
Fixes decoding of single quote within a double-quoted string in action/function parameter alias, e.g. `http://ServiceRoot/UnboundFunction(param=@p)?@p={"@odata.type":"%23NS.Film","Id":1,"Title":"The Ogre's Lair"}`
> Fix decoding single quote within double-quoted string in action/function parameter alias

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchBodyContentReaderStream.cs
*This pull request fixes #1640 .*
*Set IEEE754Compatible parameter from the batch request.*
*ODataJsonLightBatchBodyContentReaderStream assumes that batch part body is IEEE754Compatible. This pull request ensures IEEE754Compatible parameter is set from the batch request sent from the client*
> Fix #1640 - Set IEEE754Compatible parameter from the batch request

- src/Microsoft.OData.Client/ClientEdmModel.cs
- src/Microsoft.OData.Client/Microsoft.OData.Client.cs
- src/Microsoft.OData.Client/Parameterized.Microsoft.OData.Client.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs
- src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs
- src/Microsoft.OData.Edm/Schema/EdmNavigationProperty.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ComplexNavigations/ComplexNavigationTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientCSharpUnitTests/DataWebClientCSharp/ClientCSharpRegressionTests.cs
*This pull request fixes issue #1678.*
<pre>
//EntityType
public class Person 
{ 
[Key]
public string UserName { get; set; } 
public Address Address { get; set; } 
public List<Address> Addresses { get; set; } 
} 
//EntityType
public class City 
{ 
[Key]
public string Name { get; set; } 
} 
//ComplexType
public class Address 
{ 
public string Road { get; set; } 
public City City { get; set; } 
} 
}
</pre>
Currently, if you have such kind of a model where a complex type has an entity type navigation, you'll not be able to create a new entity using <code> Microsoft.OData.Client </code>. This is because
<code> Microsoft.OData.Client </code>  does not support entity navigations in complex types.
However, according to the following link, it is supported in OData Core Lib V7: …
> entity navigation property support in complex types

- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/InternalODataRequestMessage.cs
- src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
- src/Microsoft.OData.Client/RequestInfo.cs
- src/Microsoft.OData.Client/Serialization/DataServiceClientRequestMessage.cs
- src/Microsoft.OData.Client/Serialization/HttpWebRequestMessage.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests/HttpClientRequestMessage.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientExtensions/TestDataServiceClientRequestMessage.cs
*This pull request fixes issue #1753.*
Currently, It is not possible to set the ReadWriteTimeout property of a request in <code> Microsoft.OData.Client </code> but you can set the Timeout property. This means that each request uses the default <code>HttpWebRequest ReadWriteTimeout </code> property which is 300seconds or 5 minutes. 
If an endpoint takes more than 5 minutes to return a response to <code> Microsoft.OData.Client </code> that response will not be received and processed by <code> Microsoft.OData.Client</code>. This is because the ReadWriteTimeout property times out after 5 mins hence the ReadWrite connection times out. 
> update read write timeout value when timeout value is set

- sln/OData.sln
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
- test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
- test/PublicApiTests/Properties/AssemblyInfo.cs
- test/PublicApiTests/PublicApiHelper.cs
- test/PublicApiTests/PublicApiTests.cs
* Add the public API test cases into Unit test solution.
Owing that our products build outputs the assembly as:
1) Microsoft.Spatial  (.net45, .netstandard1.1, .netstandard2.0)
2) Microsoft.OData.Edm  (.net45, .netstandard1.1, .netstandard2.0)
3) Microsoft.OData.Core (.net45, .netstandard1.1, .netstandard2.0)
4)  Microsoft.OData.Client (.net45, ~~.netstandard1.1~~, .netstandard2.0) 
So, there are two test cases, 
a) test .net45 and .netstandard2.0 for all 4 packages.
b) test .netstandard1.1 for the first three packages.
> Add the PublicApi test project into the Unit test solution

- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/FakeBindMethods.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
*This pull request fixes issue #1809.*
Fixes a bug where `ApplyBinder` does not cater for float/single for the average aggregate method. This causes the following **average** expression to be rejected:
```
$apply=aggregate(SingleProp with average as AverageSingleProp)
```
while related **sum**, **min**, and **max** are accepted
```
$apply=aggregate(SingleProp with sum as SumSingleProp)
$apply=aggregate(SingleProp with min as MinSingleProp)
$apply=aggregate(SingleProp with min as MaxSingleProp)
```
**Note**: The return value from averaging floats should be a float
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.average?view=netcore-3.1#System_Linq_Enumerable_Average__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Single__ …
> Fix parsing of floats in $apply/aggregate/average expression

- src/Microsoft.OData.Edm/Validation/Severity.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/EdmErrorTests.cs
*After some back-and-forth on the names of the Severity enum members, decided to align
with the severity defined for the MessageType in the Core vocabulary by renaming "Message" to "Info". Made similar change to severity enum used for urlvalidation.*
> Rename "Message" to "Info" to align with Core.Message vocabulary term

- src/Microsoft.OData.Core/UrlValidation/ODataUrlValidationContext.cs
- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/ODataUrlValidator.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/DeprecationTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
When I renamed validation "errors" to validation "warnings" i missed renaming the AddError method in ODataUrlValidationContext.
This fixes that.
> Rename AddError to AddMessage

- src/Microsoft.OData.Client/DataServiceClientException.cs
- src/Microsoft.OData.Client/DataServiceWebException.cs
*This pull request fixes issue #1833*
<code> Microsoft.OData.Client</code> uses <code> Exception.SerializeObjectState </code> to serialize/deserealize request exceptions. 
<code>Exception.SerializeObjectState </code> is not supported in <code>.NET CORE</code> as per this document https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis. 
Leveraging custom serialization in this PR. 
> fix platform not supported exception

- src/Microsoft.OData.Core/Json/JsonReader.cs
This PR resolves #1845 
Directly copy characters from source string to the StringBuilder without an extra allocation.
> Removed the unnecessary string allocations from hot path in JsonReader.

- src/Microsoft.OData.Core/UrlValidation/Rules/DeprecationRules.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/DeprecationTests.cs
Add support for "RemovalDate" property to Revisions annotation for deprecated properties.
Also add to deprecation tests to validate extended properties.
> Add "RemovalDate" property to deprecation annotation.

- src/Microsoft.OData.Core/UrlValidation/ODataUrlValidationContext.cs
- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/ODataUrlValidator.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/DeprecationTests.cs
The Url validation will go into Infinite loop if a structured type has the property which type is the declaring type.
Below is the call stack.
```C#
0000009d`e1986640 00007ffe`1300edc0 System_Core_ni!System.Collections.Generic.HashSet_1[[System.__Canon,_mscorlib]].SetCapacity+0x40
0000009d`e19866b0 00007ffe`1300eb72 System_Core_ni!System.Collections.Generic.HashSet_1[[System.__Canon,_mscorlib]].AddIfNotPresent+0x152
0000009d`e1986730 00007ffd`b90e99b0 Microsoft_OData_Core!Microsoft.OData.UriParser.Validation.ODataUrlValidator.ValidateTypeHierarchy+0xf0
0000009d`e19867c0 00007ffd`b90eb837 Microsoft_OData_Core!Microsoft.OData.UriParser.Validation.ODataUrlValidator.ValidateProperties+0x1a7
0000009d`e1986840 00007ffd`b90eb871 …
```
> Hotfix for the infinite loop if structured type has property which type is the declaring type

- src/Microsoft.OData.Client/ALinq/ResourceBinder.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- test/EndToEndTests/Microsoft.OData.E2E.Portable/AsynchronousTests/AsynchronousQueryTests.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
*This pull request fixes issue #851 .*
The `Where` clause generates a Uri with a $filter where we have a non-key predicate e.g
`var books = dsc.Books.Where(b => b.Title == "B1");` creates the Uri below
`https://serviceRoot/Books?$filter=Title eq 'B1'`
In this case, if the `Title` is not found, the query will return an empty collection.
When we have a key in the predicate, the `Where` clause generates a Uri with a ByKey resource path e.g 
`var books = dsc.Books.Where(b => b.Id == 1);` creates the Uri below
`https://serviceRoot/Books(1)`
In this case, if the `Id` is not found, the query will throw an exception.
By design `Where` should not throw an exception whenever the predicate does not match any value/element in the source collection.
Changing the current behavior will be a breaking …
> Enable Where clause to generate $filter query options for key predicates

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/ReaderValidationUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/NavigationPropertyOnComplexTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/CollectionValueReaderJsonLightTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/PropertyReaderJsonLightTests.cs
*This pull request fixes issue #1715.*
The error message returned by the null validation of a collection of primitive values and a collection of complex values is different. The expected result is for the error message for the null validation of both collections to be the same. 
A null collection of primitive values returns this error message: 
<pre>
A null value was found for the property named 'XXX', 
which has the expected type 'Collection(Edm.String)[Nullable=False]'.
The expected type 'Collection(Edm.String)[Nullable=False]' 
does not allow null values.
</pre>
while a null collections of complex values returns: 
<pre>
A node of type 'PrimitiveValue' was read from the JSON reader
when trying to read the contents of the property 'XXX';
however, a 'StartArray' node was expected
</pre> …
> different null validation messages for complex and primitive collections

- src/Microsoft.OData.Core/UrlValidation/Rules/DeprecationRules.cs
- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/ODataUrlValidator.cs
- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/PathSegmentValidator.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/DeprecationTests.cs
*This pull request fixes issue #1890.*
When validating a segment, we also validate the type. However, if the type of the segment is a collection, we pass the typereference, rather than the type.
Because this resulted in not validating the type for a collection-valued navigation property in the path, the DeprecationRule had logic to explicitly validate the type of the segment being validated.
For navigation property segments, the validator validates both the navigation property and the navigation source, so the deprecation rule gets called twice (once for the navigation property and once for the navigation source).
Which is fine, except that the deprecation rule had explicit logic to also validate the type, which is the same for the navigation property and the navigation source, so the …
> Fix logic to validate URL segment by type

- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
*This pull request fixes issue #1878.*
> downgrade the System.Text.Json package reference version

- src/Microsoft.OData.Core/MediaTypeUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/MediaTypeUtilsTests.cs
This pull request fixes issue #1883
The process of matching a formatter to a media type can be expensive, so we cache the results of a lookup in our MediaTypeCache.  Unfortunately, since the key for this cache is the content type, each new content type is a separate entry in the cache.
The multipart/mixed mime type, used for batch, has a required boundary parameter, expressed as part of the media type in the content-type header, which may be set to any random value.
Some clients have fixed values for these, but it's not uncommon to use a guid.
Because a guid makes each content-type unique, the cache size grows unbounded.
The boundary isn't needed to look up the formatter, so can safely be removed from the cache lookup key.
Also fixed apparent misunderstanding in the code of the size …
> Fix issue #1883, MultipartMixed grows cache indefinitely

- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- src/Microsoft.OData.Core/RawValueWriter.cs
This pull request fixes issue https://github.com/OData/odata.net/issues/1842 .
By default RawValueWriter create a TextWriter with the standard line ending which is OS specific.
RFC2064 requires this to be CRLF  https://tools.ietf.org/html/rfc2046#section-5.1.1
Added setting to ODataMessageWriterSettings to control how RawValueWriter creates the underlying TextWriter.
none
> Add setting to control RawValueWriter's line ending

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes issue #1907.*
*Single backslashes within an In clause should be handled the same as within a equals expression and not require doubling.*
> Apply same backslash escaping to string literal within "IN" clause as Equals

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
Reverts OData/odata.net#1916
Merged too early; missing 2 commits.
> Revert "Apply same backslash escaping to string literal within "IN" clause as Equals"

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataInputContext.cs
- src/Microsoft.OData.Core/ODataMediaTypeResolver.cs
- src/Microsoft.OData.Core/ODataMessageReader.cs
- src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
- src/Microsoft.OData.Core/ODataMetadataFormat.cs
- src/Microsoft.OData.Core/ODataMetadataInputContext.cs
- src/Microsoft.OData.Core/ODataMetadataJsonInputContext.cs
- src/Microsoft.OData.Core/ODataMetadataJsonOutputContext.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/StreamExtensions.cs
- src/Microsoft.OData.Edm/Csdl/CsdlJsonReaderSettings.cs
- src/Microsoft.OData.Edm/Csdl/CsdlReaderSettings.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMediaTypeResolverTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
*This pull request fixes issue #1911*
OData.Edm lib supports to read/write JSON metadata.
This PR is to enable read/write JSON metadata in OData.Core lib.
So, if a request like:
*  `~/odata/$metadata `  => return XML CSDL
* `~/odata/$metadata?$format=application/json`  => return JSON CSDL
> Enable JSON metadata reader, writer in OData Core

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes issue #1907.*
*Single backslashes within an In clause should be handled the same as within a equals expression and not require doubling.*
This is the same as PR #1916 (which was previously approved), but with some added tests.
> Backslash in in clause

- src/Microsoft.OData.Core/ODataPayloadValueConverter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/PrimitiveValuesRoundtripJsonLightTests.cs
*This pull request fixes OData/WebApi#2125.*
Fix deserialization of untyped values in exponential notation into decimals
> Fix deserialization of decimal in exponential notation

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Query/ODataUriUtilsTests.cs
*This pull request fixes issue #262 *
* For example:  `ConvertFromUriLiteral("2", V4, model, Edm.Int16)`  throws exception.
This PR makes it working.
> ConvertFromUriLiteral can't work for short data type

- src/Microsoft.OData.Client/Materialization/StructuralValueMaterializationPolicy.cs
- src/Microsoft.OData.Client/Serialization/ODataPropertyConverter.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ODataDynamicPropertyTests.cs
*This pull request fixes issue #1943.*
If an OData service returns an open entity type when a dynamic property is returned with a value of null, attempt to materialize that value into the dynamic properties container property results into an error. This pull request fixes that.
> Fix null dynamic property materialization

- src/Microsoft.OData.Client/ALinq/ApplyQueryOptionExpression.cs
- src/Microsoft.OData.Client/ALinq/DataServiceQueryProvider.cs
- src/Microsoft.OData.Client/ALinq/QueryableResourceExpression.cs
- src/Microsoft.OData.Client/ALinq/ReflectionUtil.cs
- src/Microsoft.OData.Client/ALinq/ResourceBinder.cs
- src/Microsoft.OData.Client/ALinq/ResourceExpressionType.cs
- src/Microsoft.OData.Client/ALinq/TypeSystem.cs
- src/Microsoft.OData.Client/ALinq/UriHelper.cs
- src/Microsoft.OData.Client/ALinq/UriWriter.cs
- src/Microsoft.OData.Client/DataServiceExtensions.cs
- src/Microsoft.OData.Client/DataServiceQueryOfT.cs
- src/Microsoft.OData.Client/DataServiceRequest.cs
- src/Microsoft.OData.Client/Microsoft.OData.Client.Common.txt
- src/Microsoft.OData.Client/Microsoft.OData.Client.Desktop.txt
- src/Microsoft.OData.Client/Microsoft.OData.Client.cs
- src/Microsoft.OData.Client/Microsoft.OData.Client.txt
- src/Microsoft.OData.Client/Parameterized.Microsoft.OData.Client.cs
- src/Microsoft.OData.Client/XmlConstants.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/CountDistinctTests.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarApplyAggregateTests.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarApplyTestsBase.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/TestHttpWebRequestMessage.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request is 1 of 3 from splitting [this](https://github.com/OData/odata.net/pull/1810) huge pull request to make it easier to review.*
The simple aggregations below are covered. The scope of this PR is aggregations that return a single scalar result.
```csharp
// EntitySet?$apply=aggregate(Prop with average as AverageProp)
EntitySet.Average(d1 => d1.Prop)
// EntitySet?$apply=aggregate(Prop with sum as SumProp)
EntitySet.Sum(d1 => d1.Prop)
// EntitySet?$apply=aggregate(Prop with min as MinProp)
EntitySet.Min(d1 => d1.Prop)
// EntitySet?$apply=aggregate(Prop with max as MaxProp)
EntitySet.Max(d1 => d1.Prop)
// EntitySet?$apply=aggregate(Prop with countdistinct as CountDistinctProp)
EntitySet.CountDistinct(d1 => d1.Prop)
// EntitySet?$apply=aggregate(NavProp/Prop with average as …
```
> Support for $apply/aggregate

- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyModel.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
*This pull request fixes issue #1951.*
*Adds CoreVocabularyModel.RevisonsTerm to make it easy and efficient (since the lookup only happens once) for applications to reference the RevisionsTerm in the Core Vocabulary.*
> Add CoreVocabularyModel.RevisionsTerm

- src/Microsoft.OData.Core/JsonLight/JsonLightMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonNoMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightInputContext.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/JsonLightMetadataLevelTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/JsonNoMetadataLevelTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/WriterTypeNameEndToEndTests.cs
*This pull request fixes issue #1945.*
* Added 'AlwaysAddTypeAnnotationsForDerivedTypes' to ODataMessageWriterSettings
* Chagned JsonNoMetadataLevel to use 'JsonMinimalMetadataTypeNameOracle' when 'AlwaysAddTypeAnnotationsForDerivedTypes' is setting
* Updated unit tests
> Added writer setting to add type annotations

- src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Metadata/ClientTypeUtilTests.cs
If I have such a  POCO class with only one property when working with <code> Microsoft.OData.Client </code> 
An exception will always be thrown because this condition will always be true  as the <code> Microsoft.OData.Client.KeyAttribute </code> is null. 
<code> if (newKeyKind == KeyKind.AttributedKey && keyProperties.Count != dataServiceKeyAttribute?.KeyNames.Count) </code> 
> key attribute with one property throws exception

- src/Microsoft.OData.Core/Evaluation/ODataConventionalEntityMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataConventionalIdMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataMetadataContext.cs
- src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataWriterCore.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Edm/Csdl/EdmEnumValueParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
- test/FunctionalTests/Taupo/Source/Taupo.Astoria/OData/ODataPayloadElementComparer.cs
… supplying key properties.
*This pull request fixes issue #1910.*
If an id is not supplied when writing an OData V4.0 Deleted entry, uses key values instead if provided
> Support reading/writing OData V4 deleted entries with only key values

- src/Microsoft.OData.Edm/EdmModelVisitor.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderJsonTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
*This pull request fixes issue https://github.com/OData/odata.net/issues/1979.*
* Enable the CsdlWriter to write the model with Untyped property
* Add test cases to cover the write and read
> Enable serialize and deseriaze the property with Untyped type

- src/Microsoft.OData.Core/Evaluation/IODataResourceMetadataContext.cs
- src/Microsoft.OData.Core/Evaluation/ODataConventionalEntityMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataConventionalResourceMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
- src/Microsoft.OData.Edm/Vocabularies/VocabularyAnnotationExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataConventionalEntityMetadataBuilderTests.cs
…ion by default
OData spec says:
6.4 Media Entity Type
An entity type that does not specify a base type MAY specify that it is a media entity type. Media entities are entities that represent a media stream, such as a photo. Use a media entity if the out-of-band stream is the main topic of interest and the media entity is just additional structured information attached to the stream. Use a normal entity with one or more properties of type Edm.Stream if the structured data of the entity is the main topic of interest and the stream data is just additional information attached to the structured data. For more information on media entities see [OData‑Protocol].
An entity type derived from a media entity type MUST indicate that it is also a media entity type.
**Media entity types MAY specify a …
> Retrieve the content type for stream property from vocabulary annotation by convention

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
- src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs
- src/Microsoft.OData.Core/ODataReaderCore.cs
- src/Microsoft.OData.Core/ReaderValidationUtils.cs
- src/Microsoft.OData.Core/ValidationUtils.cs
- src/Microsoft.OData.Edm/Schema/EdmUntypedStructuredType.cs
- src/Microsoft.OData.Edm/Schema/EdmUntypedStructuredTypeReference.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Streaming/ODataJsonLightStreamReadingTests.cs
*When ODL reads an untyped value (for example, in a collection of untyped) that has a type specified, it fails because it doesn't understand that untyped can be cast to any type.  This PR adds support for specifying the type for an untyped value.*
> Fix reading untyped collections containing values with @type specified.

- src/Microsoft.OData.Core/Metadata/ODataMetadataWriterUtils.cs
- src/Microsoft.OData.Core/ODataMessageWriter.cs
- src/Microsoft.OData.Core/ODataMetadataFormat.cs
- src/Microsoft.OData.Core/ODataMetadataJsonOutputContext.cs
- src/Microsoft.OData.Core/ODataMetadataOutputContext.cs
- src/Microsoft.OData.Core/ODataOutputContext.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/InMemoryMessage.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
*This pull request fixes issue #https://github.com/OData/odata.net/issues/1889.*
* Add `WriteMetadataDocumentAsync` public API.
> Add WriteMetadataAsync API to enable write CSDL async

- src/Microsoft.OData.Core/Uri/NodeToStringBuilder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
*This pull request fixes issue #1974 .*
> Add Dollar it in BuildUri response

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsModel.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
Fix #1936 
Includes annotations referenced in the `edmx:IncludeAnnotations` tag of the `edmx:Reference` to be included when loading external referenced models.
This makes the vocabulary annotations imported from referenced models available through:
```c#
IEnumerable<IEdmVocabularyAnnotation> annotations = model.FindVocabularyAnnotations(element);
```
or
```c#
IEnumerable<IEdmVocabularyAnnotation> annotations = element.VocabularyAnnotations(model);
```
**Note**, these external vocabulary annotations will not appear in `model.FindDeclaredVocabularyAnnotations(element)`  or `model.VocabularyAnnotations` since they only return the annotations declared directly in the current model.
This PR attempts to restrict the imported annotations based on the `TermNamespace`, `TargetNamespace` and …
> Import vocabulary annotations declared in external referenced models

- src/Microsoft.OData.Core/Json/JsonSharedUtils.cs
- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
- src/Microsoft.OData.Core/Json/NonIndentedTextWriter.cs
- src/Microsoft.OData.Core/Json/TextWriterWrapper.cs
- src/Microsoft.OData.Core/RefOfT.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonValueUtilsAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/NonIndentedTextWriterAsyncTests.cs
*This pull request is a partial fulfilment of issue #2019*
Expand `TextWriterWrapper` internal abstract class with equivalent async method and provide the implementation in the derived `NonIndentedTextWriter` internal class and `JsonValueUtils` internal static class
> Expand TextWriterWrapper abstract class with equivalent async method

- src/Microsoft.OData.Core/Json/DefaultJsonWriterFactory.cs
- src/Microsoft.OData.Core/Json/IJsonStreamWriterAsync.cs
- src/Microsoft.OData.Core/Json/IJsonWriterAsync.cs
- src/Microsoft.OData.Core/Json/IJsonWriterFactoryAsync.cs
- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
- src/Microsoft.OData.Core/Json/JsonWriter.cs
- src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
- src/Microsoft.OData.Core/Json/JsonWriterAsyncExtensions.cs
- src/Microsoft.OData.Core/Json/ODataJsonTextWriter.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
- src/Microsoft.OData.Core/ODataBinaryStreamWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonValueUtilsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/NonIndentedTextWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonTextWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataBinaryStreamWriterTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Writer.Tests/Json/JsonValueUtilsTests.cs
*This pull request is a partial fulfilment of issue #2019.*
Implement asynchronous support in JsonWriter
- Added `IJsonWriterAsync` interface.
- Added `IJsonStreamWriterAsync` interface.
- Added `IJsonWriterFactoryAsync` interface.
- Implemented `IJsonStreamWriterAsync` asynchronous methods in `JsonWriter` class.
- Implemented `IJsonWriterFactoryAsync` methods in `DefaultJsonWriterFactory` class.
- Implemented asynchronous methods in `ODataJsonTextWriter` class.
- Implemented asynchronous methods in `ODataBinaryStreamWriter` class.
- Added test for `JsonWriter`, `ODataJsonTextWriter` and `ODataBinaryStreamWriter` classes asynchronous methods.
- Passing around a `char` array reference in the synchronous workflow to support use of char array pool and a `char` array wrapped in an object in …
> Implement asynchronous support in JsonWriter

- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandSyntacticParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SelectExpandParserTests.cs
The following does not work when "no dollar" is enabled:
```
select=foo(select=bar) 
```
`SelectExpandSyntacticParser` creates two instances of `SelectExpandParser` internally... one for parsing `select` and one for parsing `expand`. Unfortunately, while `EnableNoDollarQueryOptions` is passed through for the `expand` case it is NOT for the `select` case.
N/A
> Make sure we pass the nodollar flag through

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionSerializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionSerializerTests.cs
Implement asynchronous support in **`ODataJsonLightCollectionSerializer`**
> Implement asynchronous support in ODataJsonLightCollectionSerializer

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightEntityReferenceLinkSerializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntityReferenceLinkSerializerTests.cs
Implement asynchronous support in **`ODataJsonLightServiceDocumentSerializer`**
> Implement asynchronous support in ODataJsonLightEntityReferenceLinkSerializer

- src/Microsoft.OData.Client/BatchSaveResult.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/Descriptor.cs
- src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsyncMethodTests.cs
Individual requests can be executed in a specified order by using the dependsOn property. 
The value of dependsOn is an array of strings whose values MUST be values of either id or atomicityGroup of preceding request objects; forward references are not allowed. https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_BatchRequest
This PR introduces a `dependsOnIds` property in the `Descriptor` and an overload of the `DataServiceContext.UpdateObject` method.
`UpdateObject(object entity, params object[] dependsOnIds)`
From the client, one make the calls as shown in the sample below
```csharp
Container context = new Container(uri);
var book1 = context.Books.Where(b => b.Id == 1).First();
var book2 = context.Books.Where(b => b.Id == 2).First();
book1.Year = …
```
> Sequencing Json Batch requests with the dependsOn property

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
- src/Microsoft.OData.Edm/Validation/ValidationRules.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
*This pull request fixes issue #2054.*
Adds support for singletons as targets in VocabularyAnnotationInaccessible target rule.
> Add support for Singleton's in VocabularyAnnotationInaccessibleTarget

- src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
- src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
- src/Microsoft.OData.Core/Json/NonIndentedTextWriter.cs
- src/Microsoft.OData.Core/Json/ODataJsonTextWriter.cs
- src/Microsoft.OData.Core/Json/TextWriterWrapper.cs
- src/Microsoft.OData.Core/ODataBinaryStreamWriter.cs
*This pull request fixes issue #2019.*
Elide async and await in pass-through asynchronous methods
Affects:
- **`TextWriterWrapper`** abstract class
- **`NonIndentedTextWriter`** internal class
- **`JsonWriter`** internal class
- **`JsonValueUtils`** internal static class
- **`ODataJsonTextWriter`** internal class
- **`ODataBinaryStreamWriter`** internal class
> Elide async and await in pass-through asynchronous methods

- src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceQueryProviderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SelectExpandParserTests.cs
This pull request fixes #2016.
This pull request fixes #1447.
This PR lowers the parsing of the `in` and `has` operators to just before the other "primary" operators per [the precedence table listed in the OData 4.01 spec](https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#_Toc31361036).
~_NOTE:_ I'm having issues building the E2E project locally and will keep this as a Draft PR until I work that out.~
There is an open issue with this fix in that it introduces a new recursion depth to the code. This could be considered a breaking change for services which use OData.Net with queries that work today but tomorrow will not because they exist right _at_ the recursion limit.
I see two paths forward:
1. Leave this PR as-is and make a …
> Issues #2016, #1447: In-operator precedence

- src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
Firing performance issue in case of odata exception being swallowed. Trying to get keys in case we intend to follow without any exception
> Perf Fix for swallowed exception in AppendKeySegment

- src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CapabilitiesVocabularyTests.cs
*Update to latest OASIS Capability vocabulary to include new UpdateMethod*
*OASIS Added UpdateMethod to enable specifying support for PUT versus PATCH in updating a resource.  Updated the included CapabilitiesVocabulary.xml to include that definition.*
> Update Capabilities Vocabulary.

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes issue #1997 .*
For a sample model like the one shown below
```csharp
public class TestEntity
{
public guid? NullableProperty { get; set; }
}
```
Running the following sample query throws an error. 
It is also been clear that a null GUID should not be equated to an empty GUID. 
```url
http://host/service/TestEntity?$filter=NullableProperty in (null)
```
Guid literals are converted to single-quoted form, so that they are  compatible with the Json reader used for deserialization.
``` 
Sample: [D01663CF-EB21-4A0E-88E0-361C10ACE7FD, 492CF54A-84C9-490C-A7A4-B5010FAD8104]
==>  ['D01663CF-EB21-4A0E-88E0-361C10ACE7FD', '492CF54A-84C9-490C-A7A4-B5010FAD8104']
```
This means that even null GUIDS will be converted to the …
> in operator not working with null Guid values

- src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
- src/Microsoft.OData.Core/IODataOutputInStreamErrorListener.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaWriter.cs
- src/Microsoft.OData.Core/ODataAsynchronousWriter.cs
- src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
- src/Microsoft.OData.Core/ODataParameterWriterCore.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
Modify **`IODataOutputInStreamErrorListener`** interface to support asynchronous notifications when an in-stream error is to be written
When an error occurs when writing a payload to the stream, a notification is sent to any subscribed listener to notify it that an in-stream error is to be written. The listener implements the `IODataOutputInStreamErrorListener` interface that contains a single synchronous method `OnInStreamError`. **This interface is `internal`**.
To support similar functionality in asynchronous scenarios, we need to modify the interface to support an asynchronous equivalent method - `OnInStreamErrorAsync`.
`ODataBatchWriter` is a `public abstract` class that implements the `IODataOutputInStreamErrorListener` …
> Modify IODataOutputInStreamErrorListener interface to support asynchronous notifications when an in-stream error is to be written

- src/Microsoft.OData.Core/Batch/ODataBatchReader.cs
- src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
- src/Microsoft.OData.Core/IODataStreamListener.cs
- src/Microsoft.OData.Core/ODataReaderCore.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
Modify **`IODataStreamListener`** interface to support asynchronous notifications when the content stream of an operation has been disposed.
**`IODataStreamListener`** interface allows the creators of a stream to listen for status changes of the operation stream. The `StreamDisposed` method notified the implementer of this interface that the content stream of the operation has been disposed. To support similar functionality in asynchronous scenarios, we need to modify the interface to support an equivalent method - `OnStreamDisposedAsync`.
The actual implemented will be provided when implementing asynchronous support in the following 3 classes that implement the interface:
- `ODataWriterCore`
- `ODataBatchWriter`
- …
> Modify IODataStreamListener interface to support asynchronous notifications when the content stream of an operation has been disposed

- src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec
- src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec
See detail at: https://github.com/dotnet/aspnetcore/issues/31725
v2.1.27 nuget package pins a number of libraries to 4.6.0 not inclusive. This breaks downstream dependencies when combined with the OData libraries.
It's better to add "System.Runtime.CompilerServices.Unsafe and System.Text.Encodings.web" dependency to unblock customer to use latest .net core 2.1.27
> Add System.Runtime.CompilerServices.Unsafe and System.Text.Encodings.web dependency for OData.Edm

- src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
- src/Microsoft.OData.Core/UriParser/Visitors/SelectItemTranslator.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
*This pull request fixes issue #2084 .*
When you call `ODataUriParser.ParseUri()`, we create an `ODataUri`.
`BuildUri` extension method creates a `Uri` from an `ODataUri`. The result Uri's query options are URL encoded.
```csharp
ODataUriParser odataUriParser = new ODataUriParser(EdmModel, ServiceRoot, queryUri);
odataUriParser.UrlKeyDelimiter = urlKeyDelimiter;
ODataUri odataUri = odataUriParser.ParseUri();
Uri uri = odataUri.BuildUri(urlKeyDelimiter);
```
> Translate ExpandedCountSelectItem in BuildUri

- src/Microsoft.OData.Core/ODataNotificationWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationWriterTests.cs
Support asynchronous invocation of **`IODataStreamListener.StreamDisposedAsync`** method from `Dispose`/`DisposeAsync` methods of **`ODataNotificationWriter`** class.
- In .NET Core 3.1 or later, we're able to ride on asynchronous `DisposeAsync` method defined in `IAsyncDisposable` interface to avoid blocking.
- In platforms below .NET Core 3.1, we're forced to `.Wait()` on the asynchronous method.
> Support asynchronous invocation of IODataStreamListener.StreamDisposedAsync method from ODataNotificationWriter class

- src/Microsoft.OData.Core/ODataNotificationStream.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationStreamTests.cs
Support asynchronous invocation of **`IODataStreamListener.StreamDisposedAsync`** method from `Dispose`/`DisposeAsync` methods of **`ODataNotificationStream`** class.
- In .NET Core 3.1 or later, we're able to ride on asynchronous `DisposeAsync` method defined in `IAsyncDisposable` interface to avoid blocking.
- In platforms below .NET Core 3.1, we're forced to `.Wait()` on the asynchronous method.
> Support asynchronous invocation of IODataStreamListener.StreamDisposedAsync method from ODataNotificationStream class

- src/Microsoft.OData.Core/Json/JsonWriter.cs
- src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockCharArrayPool.cs
*This pull request fixes issue #2074.*
Consistently use `CharArrayPool` in `JsonWriter` to cut cost of initializing char arrays
**Notes:**
- `CharArrayPool` is already used in `JsonWriter` class. It was just not being passed along in some instances.
- There's no real value in passing the `CharArrayPool` parameter for the methods listed below because we only use it if the input has special characters. I decided to still pass the parameter just to keep things consistent and avoid confusion.
- `WriteName(string)`/`WriteNameAsync(string)` - name _should_ not contain special chars
- `WriteValue(long)`/`WriteValueAsync(long)` - - special chars not expected when the value is converted to string (IEEE 754 compatible)
- `WriteValue(decimal)`/`WriteValueAsync(decimal)` - special chars not expected …
> Consistently use CharArrayPool in JsonWriter to cut cost of initializing char arrays

- src/Microsoft.OData.Client/EntityTracker.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/ClientEntityTrackerTests.cs
*This pull request fixes issue #1531 *.
Having such a POCO class when working with <code> OData Client </code> leads to errors when you try to perform save or update operations. 
```csharp
public class ExampleObject
{
[Key]
public int Id { get; set; }
public string Name { get; set; }
public bool Equals(ExampleObject other)
{
if (ReferenceEquals(other, null))
{
return false;
}
return other.Id == Id;
}
public override bool Equals(object obj)
{
var other = obj as ExampleObject;
if (ReferenceEquals(other, null))
{
return false;
}
return other.Id == Id;
}
public override int GetHashCode()
{
return Id.GetHashCode();
}
}
```
The reason for the exceptions is because the <code> EntityTracker </code> uses the default EqualityComparer. 
*If …
> entity tracker equality comparer

- src/Microsoft.OData.Client/DataServiceActionQuery.cs
- src/Microsoft.OData.Client/DataServiceActionQueryOfT.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/CancellationTokenTests.cs
*This pull request fixes issue #2094 .*
> Fix/2094 Add cancellation token to ExecuteAsync in DataServiceActionQuery and DataServiceActionQueryofT 

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterWriter.cs
- src/Microsoft.OData.Core/ODataParameterWriterCore.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
Implement asynchronous support in **`ODataJsonLightParameterWriter`**
> Implement asynchronous support for ODataJsonLightParameterWriter

- src/Microsoft.OData.Core/ODataNotificationStream.cs
- src/Microsoft.OData.Core/ODataNotificationWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationStreamTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationWriterTests.cs
`ODataNotificationWriter` and `ODataNotificationStream` wrapper classes should not dispose the passed `TextWriter` and `Stream` respectively.
Reference to merged PRs [2079](https://github.com/OData/odata.net/pull/2079) and [2080](https://github.com/OData/odata.net/pull/2080) implementing support for asynchronous invocation of `IODataStreamListener.StreamDisposedAsync` from `ODataNotificationWriter` and `ODataNotificationStream` wrapper classes, a line was added such that the passed `TextWriter` and `Stream` respectively are disposed when the `Dispose` method is called.
This can cause a problem if the owner of `TextWriter` or `Stream` chose to use it after - _though that does not happen currently_. This pull request addresses that loop hole, leaving the owner to do the disposing.
**NOTE:** …
> ODataNotificationWriter and ODataNotificationStream wrapper classes should not dispose the passed TextWriter and Stream respectively

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
Implement asynchronous support in **`ODataJsonLightDeltaWriter`**
> Implement asynchronous support in ODataJsonLightDeltaWriter

- src/Microsoft.OData.Core/ODataStream.cs
- src/Microsoft.OData.Core/ODataWriteStream.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriteStreamTests.cs
Implement asynchronous support in `ODataWriteStream`
- Ensures that if `Dispose` method of `ODataWriteStream` is fired when writing asynchronously, `StreamDisposedAsync` method of `IODataStreamListener` instance is fired instead of the synchronous `StreamDisposed` method.
- Implements `IAsyncDisposable` interface in `ODataWriteStream` such that its possible to use `await using` for frameworks that implement NETSTANDARD2_0
> Implement asynchronous support in ODataWriteStream

- src/Microsoft.OData.Core/Batch/ODataBatchUtils.cs
- src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
- src/Microsoft.OData.Core/GlobalSuppressions.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
Implement asynchronous support in **`ODataJsonLightBatchWriter`**
To prevent a breaking change, I added the following 6 `protected virtual` asynchronous methods to the `public abstract ODataBatchWriter` class as asynchronous wrappers over the synchronous methods.
- `WriteStartBatchImplementationAsync`
- `WriteEndBatchImplementationAsync`
- `WriteStartChangesetImplementationAsync`
- `WriteEndChangesetImplementationAsync`
- `CreateOperationRequestMessageImplementationAsync`
- `CreateOperationResponseMessageImplementationAsync`
These virtual asynchronous methods are then invoked from the public asynchronous methods. For example;
```csharp
public Task WriteStartBatchAsync()
{
// ...
return …
```
> Implement asynchronous support in ODataJsonLightBatchWriter

- src/Microsoft.OData.Core/RawValueWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/RawValueWriterTests.cs
Implement asynchronous support in **`RawValueWriter`**.
> Implement asynchronous support in RawValueWriter

- src/Microsoft.OData.Client/Serialization/HttpClientRequestMessage.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/HttpClientRequestMessageTests.cs
UnwrapAggregateException of HttpClientRequestMessage can currently either re-throw incomplete exception informations (by skipping an exception layer) or cause a NPE.
UnwrapAggregateException tries to unwrap an exception two layers deep. This is wrong. I got here a NPE because the exception that was wrapped in the AggregateException had no InnerException. This PR fixes this simple mistake.
none
> HttpClientRequestMessage: Fix UnwrapAggregateException.

- src/Microsoft.OData.Core/ODataAsynchronousResponseMessage.cs
- src/Microsoft.OData.Core/ODataAsynchronousWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataAsynchronousWriterTests.cs
Implement asynchronous support in **`ODataAsynchronousWriter`**.
Firstly, they are all private.
Secondly, I introduced 2 new constructors.
The first new constructor doesn't take a delegate parameter to write the envelop for the inner message. I made the change such that its called from `CreateMessageForReading` method that was previously passing a `null` for `writeEnvelope` `Action` delegate parameter.
The other new constructor takes a `Func` delegate of `ODataAsynchronousResponseMessage` and `Task`. It is applied in asynchronous scenarios such that its possible to `await`. The constructor is called from `CreateMessageForWritingAsync` method.
Finally I cleaned everything up such that the 2 constructors that accept 6 parameters …
> Implement asynchronous support in ODataAsynchronousWriter

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextTests.cs
Implement asynchronous support in **`ODataJsonLightOutputContext`**.
**What:**
Asynchronous support is not implemented in `Microsoft.Spatial` library. To write spatial data, we rely on the synchronous `PrimitiveConverter.Instance.WriteJsonLight(object, IJsonWriter)` method. When writing asynchronously we wrap this method in a task. The `WriteJsonLight` method takes an `IJsonWriter` parameter while the asynchronous writer is declared as `IJsonWriterAsync`. Luckily, `JsonWriter` sealed internal class implements both `IJsonWriter` and `IJsonWriterAsync`. To guarantee that when the synchronous writer is called to write spatial data it shares the same scope(s) as the asynchronous writer, we initialize them to the same concrete …
> Implement asynchronous support in ODataJsonLightOutputContext

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsElement.cs
- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsModel.cs
3% of all allocations in AGS, come from this method, allocating string for full qualified name. This also represents 16% of all string allocations for AGS.
This fix attempts to reduce string allocations by caching the annotation full qualified name in CsdlSemanticsElement the first time it is evaluated.
- [X ] *Test cases already covering this code path*
> Cache annotation full qualified name in FindDeclaredVocabularyAnnotations

- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataRawOutputContextApiTests.cs
Tests to verify congruence between synchronous and asynchronous APIs exposed by **`RawOutputContext`** class.
Synchronous and asynchronous APIs are executed and the results compared to verify that the outcome is the same.
> Tests to verify congruence between synchronous and asynchronous APIs exposed by RawOutputContext class

- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMultipartMixedBatchOutputContextApiTests.cs
Tests to verify congruence between synchronous and asynchronous APIs exposed by `ODataMultipartMixedBatchOutputContext` class
Synchronous and asynchronous APIs are executed and the results compared to verify that the outcome is the same.
> Tests to verify congruence between synchronous and asynchronous APIs exposed by ODataMultipartMixedBatchOutputContext class

- src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
- src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
- src/Microsoft.OData.Core/ODataParameterWriterCore.cs
- src/Microsoft.OData.Core/ODataRawOutputContext.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Fix `AggregateException` thrown by OData writers async API
As indicated in [this TODO](https://github.com/OData/odata.net/blob/d49b8b9d9a77816b2cf6664be6493ae71906fc0b/test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs#L1703), there was a scenario causing an `AggregateException` to be thrown instead of the expected `ODataException`. This PR fixes that by avoiding the use of `TaskUtils.FollowSuccessWithTask` that was responsible for that behaviour.
In the process added a bunch of tests to verify behaviour in scenarios where exceptions are thrown.
> Fix AggregateException thrown by OData writers async API

- src/Microsoft.OData.Core/PropertyCache.cs
- src/Microsoft.OData.Core/PropertyCacheHandler.cs
2.5% of all allocations in AGS come from concatenating strings to compose keys used to lookup the PropertyCache. This also represents 13.5% of all string allocations for AGS, and it is the second largest hotspot when it comes to allocations according to CPR.
This code is present in the hot path while writing the OData response payload back to the client.
Changing the type of the key from string to a struct that is composed by the relevant properties: depth, name, fullTypeName. Thus avoiding the string allocation to compose the key. Furthermore, struct is a value type and therefore it is only stored in the stack and does not require any heap allocation overhead.
> Skip string allocation for keys of PropertyCache

- src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Currently the binding type constraint for escape functions comes from `TargetEdmType`, but when the escape function is rooted on a contained navigation the chosen type ends up being the collection instead of the entity.
Consider the following request (where `items` is a contained navigation from `oneDrive.drive` to `Collection(oneDrive.item)`):
`/drive/items/32:/path`
The expectation is that, if `oneDrive.getByPath` is bound to `oneDrive.item`, the escape function mechanism will translate the path to:
`/drive/items/32/oneDrive.getByPath(path='path')`
However, the current logic is trying to find a function bound to `Collection(oneDrive.item)` and so the escape logic is not translating at all. The fix is to use `EdmType` which appears to be the expected value for all scenarios.
> Fix escape function binding type constraint

- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextApiTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/TestODataJsonLightWriterResourceState.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/TestODataResourceMetadataBuilder.cs
Tests to verify congruence between synchronous and asynchronous APIs exposed by `ODataJsonLightOutputContext` class
Synchronous and asynchronous APIs are executed and the results compared to verify that the outcome is the same.
**About the seemingly unrelated changes:**
I had created 2 private classes (`TestODataJsonLightWriterResourceState`, `TestODataResourceMetadataBuilder`) when writing unit tests for the `ODataJsonLightResourceSerializer` asynchronous API. To make it possible to reuse them, I refactored them out into their own files. I also made a few changes to their implementation so they'd be more general and applicable in varying scenarios.
*If documentation update is needed, please add "Docs Needed" label to the issue …
> Tests to verify congruence between synchronous and asynchronous APIs exposed by ODataJsonLightOutputContext class

- src/Microsoft.OData.Edm/GlobalSuppressions.cs
- src/Microsoft.OData.Edm/VersioningList.cs
- src/Microsoft.OData.Edm/Vocabularies/Annotations/EdmDirectValueAnnotationsManager.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/VersioningListTests.cs
Total allocation of this method is at 3.09%: 
- 1% for delegate
- 1.61% for enumerator
- 0.48% for closure.
This change replaces the usage of Linq in this method, with manual implementation, avoiding lambda allocation. Every time we invoke Any, it allocates a lambda. This is normally meaningless, when not present in the hot path. Since this is present in AGS hot path, it is costing 1% of allocations just in this lambda. This is a lot.
Also removes the usage of enumerator, replacing with O(1) random access for loop. The ArrayVersioningList is better for search scenarios because we can save the enumerator allocation all together, and use O(1) random access. The LinkedVersioningList would only be useful if this data structure is changing very often at runtime, which I don't think is the …
> Skip lambda allocation in FindTransientAnnotation

- .github/PULL_REQUEST_TEMPLATE.md
Fix pull request template such that referenced issue is linked and closed after pull request is merged
Change ***This pull request fixes issue #xxx.*** to ***This pull request fixes #xxx.***
When you use the first form, the reference issue in not automatically linked such that when you merge the pull request, it's not auto-closed. The reason for that is the word "issue" between "fixes" and the issue #. [GitHub guideline on link a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> Fix pull request template such that referenced issue is linked and closed after pull request is merged

- src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
* Web API OData typically re-set the BaseUri in the ReaderSetting.
* When retrieves the ReaderSetting from DI , in the same request, since it's scoped, the only singleton reader setting returns.
* So, It's better to clone the reader setting any time to use the reader setting.
* That's a fix for BingAds.
> Clone the reader setting when creating reader setting

- src/Microsoft.OData.Client/ClientEdmModel.cs
- src/Microsoft.OData.Client/Common.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
- src/Microsoft.OData.Client/TypeResolver.cs
- src/Microsoft.OData.Client/Util.cs
- src/Microsoft.OData.Client/WebUtil.cs
- src/Microsoft.OData.Edm/EdmUtil.cs
- src/Microsoft.Spatial/Util.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextNoTrackingStreamsTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/CamelCasedTypeMaterializationTests.cs
*This pull request fixes #2119.*
When an OData service metadata and payload is camel-cased and an entity bound to base entity type collection is returned, the value for `@odata.type` property is not in the expected form leading to a `NullReferenceException` during materialization.
Consider the following service metadata for a contrived sample service comprising of two open entity types `Rectangle` and `Shape` where `Rectangle` derives from `Shape`.
```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="NS.Models">
<EntityType Name="shape" OpenType="true">
<Key>
<PropertyRef Name="id" />
</Key>
<Property Name="id" Type="Edm.Int32" …
```
> Fix NullReferenceException thrown during materialization of lower-camel-cased payload

- src/Microsoft.OData.Core/Uri/ODataUri.cs
*This pull request (partially) addresses #2163 .* 
`ODataUri.Clone()` creates a new instance of `ODataUri` using `new ODataUri()` then shallow copies the properties (references) from the "old" `ODataUri` to the new one. However, the default `ODataUri` constructor creates a new instance of `Dictionary<string, string>` and a new instance of `ParameterAliasValueAccessor`. The  `ODataUri.ParameterAliasValueaAccessor` property is immediately replaced by `ODataUri.Clone()` with the reference from the old uri. So the instances created in the default constructor are a waste of memory and unnecessary allocation/GC overhead.
I fixed this issue by creating the `ParameterAliasValueAccessor` instance lazily in the property getter. I thought this to be the safest solution, below are other solutions …
> Avoid creating unused objects when calling ODataUri.Clone()

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
- test/FunctionalTests/Microsoft.OData.TestCommon/Microsoft.OData.TestCommon.csproj
- test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
*This pull request fixes https://github.com/OData/odata.net/issues/2165
* If we have a nested resource whose property name is wrong case or its undeclared property,
* When we put that property in to the request body, ODL can't read it as Untyped even we set the ReadUntypedAsString=false.
* Since we understand it's undeclared property, can we directly read it as normal untyped value.
* This is a simple fix for this issue
> Fix the issue when read nested resource untyped in the request

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/ODataExpandPath.cs
- src/Microsoft.OData.Core/UriParser/UriEdmHelpers.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/ExpandBinderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataExpandPathTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathExtensionsTests.cs
*This pull request fixes #1870 .*
> Expand fully qualified type

- src/Microsoft.OData.Core/ODataWriterCore.cs
This addresses one of the issues pointed out in [2192](https://github.com/OData/odata.net/issues/2192).
These is an issue inadvertently missed in this [PR](https://github.com/OData/odata.net/pull/2158).
Going forward I think we should consider using static code analyzers to detect these issues at compile time, in OData critical code path/assemblies. That will avoid missing such issues, inadvertently. This is already done in AGS.
@habbes
> Remove delegate allocation in ODataWriterCore.CheckForNestedResourceInfoWithContent()

- src/Microsoft.OData.Client/BaseSaveResult.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/DeleteLinkUriOption.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeleteLinkTests.cs
*This pull request fixes #2201.*
Provide option for form of delete link request Uri.
According to the OData spec, a delete link request should have a Uri like:
```
{ServiceUri}/{EntitySet}/{Key}/{NavigationProperty}/$ref?$id={ServiceUri}/{RelatedEntitySet}/{RelatedKey}
```
But in V3 and V4.01, the following alternative form is supported:
```
{ServiceUri}/{EntitySet}/{Key}/{NavigationProperty}/{RelatedKey}/$ref
```
> Provide option for alternative form of delete link request Uri

- src/Microsoft.OData.Core/ExceptionUtils.cs
- src/Microsoft.OData.Core/Json/JsonReader.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
*This pull request is a partial fulfilment of #2019 .*
Implement asynchronous support in **`JsonReader`**
> Implement asynchronous support in JsonReader

- src/Microsoft.OData.Edm/Csdl/CsdlXmlWriter.cs
- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelReferenceElementsXmlVisitor.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
OData spec says:
5.1 Alias
A schema MAY specify an alias which MUST be a simple identifier.
If a schema specifies an alias, the alias MUST be used instead of the namespace within qualified names throughout the document to identify model elements of that schema. A mixed use of namespace-qualified names and alias-qualified names is not allowed.
https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_Alias
*Currently the issue is with using aliases for referenced models if they are set instead of using fully qualified names when writing the csdl.*
> update namespaces to use aliases if aliases for the namespaces are set

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- src/Microsoft.OData.Core/ODataMessageReaderSettings.cs
- src/Microsoft.OData.Core/ReaderValidationUtils.cs
- src/Microsoft.OData.Core/ReaderValidator.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.txt
- src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/PropertyAndValueJsonLightReaderIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs
* This PR enables to read the property with the different cases as its property type.
```json
{
"name": "ABC"
}
```
1) If customer enable "reading property case-insensitive", ODL reads the property value as string value.
2) if customer doesn't enable the setting, ODL reads the property value as untyped value.
> Enable property case insensitive reading

- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
*This pull request fixes #2181.*
Add direct reference to `Microsoft.Bcl.AsyncInterfaces` package to fix missing reference issue observed in dependent libraries.
Particular features of the library were introduced to support async disposal when the target framework is .netstandard2.0. However, when Microsoft.OData.Core library is added as a dependency in some other libraries (particularly Microsoft.AspNetCore.OData), it has been observed in some cases that the dependency cannot be found. To mitigate this, the reference is added directly (instead of relying on .netstandard2.0 framework)
> Add direct reference to Microsoft.Bcl.AsyncInterfaces package to fix missing reference issue observed in dependent libraries

- src/Microsoft.OData.Client/DataServiceContext.cs
*This pull request fixes #2234 .*
*Current problem*
`CancellationTokenRegistration` is a callback delegate that has been registered with a `CancellationToken`. https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokenregistration?view=net-5.0
We are not calling `CancellationTokenRegistration.Dispose()` to release all resources used by the current instance of the `CancellationTokenRegistration`.
In this case, what happens is that the callback is not unregistered.
It's also important to note, the cancellation callback is registered with the CancellationTokenSource (see https://referencesource.microsoft.com/#mscorlib/system/threading/CancellationToken.cs,31a5196df8e4df6d), not with CancellationToken. So, if CancellationTokenRegistration.Dispose() is not correctly scoped, …
> Fix memory leak

- src/Microsoft.OData.Core/InstanceAnnotationWriteTracker.cs
- src/Microsoft.OData.Core/Json/JsonLightInstanceAnnotationWriter.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
- src/Microsoft.OData.Core/ODataAnnotatable.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsAsyncTests.cs
- test/PerformanceTests/ComponentTests/ODataWriter/ODataWriterFeedTests.cs
*This pull request fixes #2190.*
- initialize `ODataAnnotatable` `instanceAnnotations` with a `List<T>` instead of `Collection<T>`
- cast annotations `IEnumerable` to a `List<T>` if possible when running `foreach` loop
- lazy initialization of the `instanceAnnotations` collection in `ODataAnnotatable`
- Lazy initialization of the `writeStatus` hash set in `InstanceAnnotationWriterTracker`
- Implement `ScopeStack` using `List<Scope>` instead of `Stack<Scope>` so we can access parents cheaply using index
The optimizations in `WriteInstanceAnnotations` have 2 versions of a foreach loop, one against a `List<T>` instance and the other against the `IEnumerable<T>` instance. When performing the foreach loop against a `List<T>`, the …
> Perf: Optimize collections and enumerators

- src/Microsoft.OData.Core/Json/IJsonReaderAsync.cs
- src/Microsoft.OData.Core/Json/JsonReaderExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
*This pull request partially fulfills #2019.*
Implement asynchronous support in **`JsonReaderExtensions`**.
**About `IJsonReaderAsync` inheriting from `IJsonReader`**
To anchor support for asynchronous reading of OData message payloads, the `JsonReader` class implements both `IJsonStreamReader` (`IJsonReader` is the base type) and `IJsonStreamReaderAsync` (`IJsonReaderAsync` is the base type). Two properties of `IJsonReader`, `NodeType` and `IsIeee754Compatible`, that expose the data/state of the reader need to be shared across both the synchronous and asynchronous APIs. I considered moving them from `IJsonReader` to a base interface (`IJsonReaderBase`) and have both `IJsonReader` and `IJsonReaderAsync` inherit from it but realized that would be a breaking change if someone was explicitly …
> Implement asynchronous support in JsonReaderExtensions

- test/PerformanceTests/ComponentTests/ODataReader/ODataReaderFeedTests.cs
- test/PerformanceTests/ComponentTests/ODataWriter/ODataWriterFeedTests.cs
- test/PerformanceTests/SerializationBaselineTests/SerializationBenchmarks.cs
Some performance tests were failing or not returning results. In most cases the issue was related to incorrect usage of `[IterationSetup]`. This attribute is meant to be used on a method that should execute before each invocation of a benchmark method (it's actually not recommended to use unless for benchmarks that run for 100ms+ per invocation because it can spoil the results). However the issue was because I had multiple methods with `[IterationSetup]` and `[IterationSetup(Target=...)]` expecting each to be executed for the same benchmark method. But only one gets executed, and so some benchmarks were executing with some values not being properly initialized.
In some of these cases, I realized that the setup code didn't need to run for each invocation of …
> Fix issues with performance tests

- src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/OpenPropertiesFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/FunctionCallBinderTests.cs
This pull request fixes #2241
Related to
OData/WebApi#1180
OData/WebApi#2173
OData/AspNetCoreOData#325
In the `FunctionCallBinder`, the function signature's return type was checked before processing the arguments nodes. There is no apparent reason for this check which leads to some arguments being mistyped. 
The check has been removed, allowing the arguments to be `promoted` as they should.
Unfortunately, I'm not able to launch the tests. If anybody could double check this commit and maybe add some tests, it would be very much appreciated! ❤️
> FunctionCallBinder promotes arguments without checking return type

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/UriParser/Binders/CountSegmentBinder.cs
- src/Microsoft.OData.Core/UriParser/Parsers/CountSegmentParser.cs
- src/Microsoft.OData.Core/UriParser/Resolver/AlternateKeysODataUriResolver.cs
- src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs
- test/EndToEndTests/Framework/Core/Verification/StringResourceUtil.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/CaseInsensitiveResolverTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ExtensionTestBase.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/UnqualifiedODataUriResolverTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/CustomUriLiteralParserTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/CustomUriLiteralPrefixesTests.cs
*This pull request fixes #2221 .*
The `AlternateKeyODataUriResolver.ResolveKeys` first calls the `base.ResolveKeys()` to attempt to resolve the keys, and if it fails (exception thrown), it tries to resolve alternate keys. Relying on the exception being thrown adds "noise" when debugging due to first chance exceptions causing the debugger to break (as mentioned in the issue). We are also paying the price of try-catch when we don't need to.
> Refactor alternate key resolver to avoid relying on exceptions

- src/Microsoft.OData.Core/Json/BufferingJsonReader.cs
- src/Microsoft.OData.Core/Json/IJsonStreamReaderAsync.cs
- src/Microsoft.OData.Core/Json/JsonReader.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/BufferingJsonReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonReaderTests.cs
Implement asynchronous support in **`BufferingJsonReader`**
> Implement asynchronous support in BufferingJsonReader

- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
*This pull request fixes #2276.*
A structural property is a property of a structured type that has one of the following types:
·         Primitive type
·         Complex type
·         Enumeration type
·         A collection of one of the above
A structural property MUST specify a unique name as well as a type.
The property’s name MUST be a simple identifier. It is used when referencing, serializing or deserializing the property. It MUST be unique within the set of structural and navigation properties of the declaring structured type, and MUST NOT match the name of any navigation property in any of its base types. If a structural property with the same name is defined in any of this type’s base types, then the property’s type MUST be a type derived from the type specified for the property …
> Fix issue #2276: should use for @type for serializing record in CSDL JSON

- src/Microsoft.OData.Core/ODataContextUrlInfo.cs
If the operation returns not resource, the context uri info should support to use type to generate the context Uri.
```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx=http://docs.oasis-open.org/odata/ns/edmx xmlns:ags=http://aggregator.microsoft.com/internal xmlns:odata=http://schemas.microsoft.com/oDataCapabilities>
<edmx:DataServices>
<Schema Namespace="microsoft.management.services.api" xmlns:ags=http://aggregator.microsoft.com/internal xmlns=http://docs.oasis-open.org/odata/ns/edm>
<EntityType Name="managedTenant" ags:AddressUrl="[ServiceEndpoint:MTMAPI]" ags:IsMaster="true" ags:AddressContainsEntitySetSegment="false" OpenType="true">
</EntityType>
<EntityType Name="tenantRelationship" ags:AddressUrl="[ServiceEndpoint:MTMAPI]" ags:IsMaster="true" …
```
> Compute navigation path should return null if navigation source kind is none in context uri info

- src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataEntryMetadataContextTest.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataReaderDerivedTypeConstraintTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.cs
*This pull request fixes #2278*
ODL expects that, if you set SerializationInfo on the resource then you are taking responsibility for providing all of the information necessary for serialization.  
When ODL tries to get key properties in order to append the key segment, it checks to see if the serializationInfo for the resource is null -- if so, it uses the model to determine key properties and all is good. On the other hand, if serializationInfo on the resource is non-null then it looks for properties whose serializationInfo identify them as key properties.  Finding none, it errors.
This change makes ODL more robust by falling back to using the entityType to identify key properties if the resource has serializationInfo but none of the properties have serializationInfo that identifies …
> Default to using entityType for incomplete serializationInfo.

- src/Microsoft.OData.Core/Json/IODataJsonOperationsDeserializerContext.cs
- src/Microsoft.OData.Core/Json/ODataJsonReaderCoreUtils.cs
- src/Microsoft.OData.Core/JsonLight/JsonLightConstants.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceDeserializerTests.cs
This PR implements support for the following 3 classes:
- `ODataJsonLightDeserializer`
- `ODataJsonLightPropertyAndValueDeserializer`
- `ODataJsonLightResourceDeserializer`
It would have been desirable to have separate PRs for the above 3 classes but there exists a dependency that was not that easy to navigate around without risking a breaking change.
Using the synchronous API to illustrate, the `ODataJsonLightDeserializer` expects the `ReadPropertyCustomAnnotationValue` `Func` delegate property to be initialized from the derived classes (`ODataJsonLightPropertyAndValueDeserializer` or `ODataJsonLightResourceDeserializer`). Implementation of asynchronous support `ODataJsonLightDeserializer` involved introducing an asynchronous `Func` delegate …
> Implement asynchronous support in ODataJsonLightDeserializer

- src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/InNode.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes #2270.*
For open types, the <code>TypeReference</code> of the left Node in an InBind Operation is always null. Have therefore put a null check to check for the left Node's TypeReference.  If it is null, then an <code> UnTyped Typerefence </code> is used. 
> fix filter using in operator with open types

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightEntityReferenceLinkDeserializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataEntityReferenceLinkTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataEntityReferenceLinksTests.cs
Implement asynchronous support in **`ODataJsonLightEntityReferenceLinkDeserializer`**.
> Implement asynchronous support in ODataJsonLightEntityReferenceLinkDeserializer

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightErrorDeserializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightErrorDeserializerTests.cs
Implement asynchronous support in `ODataJsonLightErrorDeserializer`.
> Implement asynchronous support in ODataJsonLightErrorDeserializer

- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Annotation/InstanceAnnotationDictWeakKeyComparerTests.cs
A [recent commit](https://github.com/OData/odata.net/commit/7dcad74478debcfe54e93c63f47b7cb57f2d2e67) made the `RemoveRule` method of the `InstanceAnnotationDictWeakKeyComparer` class static. This broke the e2e tests that were still referencing the method as if it were an instance method. This PR fixes that issue and gets the tests building again.
PS: Some tests are still failing locally, and are not running on CI (which is likely why this build error was not caught when the PR that introduced the issue was merged). There are other open issues to tackle those problems:
- https://github.com/OData/odata.net/issues/2295
> Fix e2e tests build error

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterDeserializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterDeserializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
Implement asynchronous support in **`ODataJsonLightParameterDeserializer`**.
> Implement asynchronous support in ODataJsonLightParameterDeserializer

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs
*This pull request fixes #1208.*
*Relative context URI could start with "$metadata". This PR covers the case in addition to the fix of [#2132: Relative URIs for @oData.context are not supported.](https://github.com/OData/odata.net/pull/2216)*
> #1208 Support relative context URI starting with "$metadata"

- src/Microsoft.OData.Core/ODataNotificationReader.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationReaderTests.cs
Implement asynchronous support in **`ODataNotificationReader`**.
> Implement asynchronous support in ODataNotificationReader

- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
*This pull request helps address #2295.*
*When the EdmLibTests project is run locally, there are test failures due to a `NotSupportedException` when looking up resources in the embedded resource table*
*There will be future PRs to address the other test project failures. This PR is scoped specifically to the EdmLibTests project*
> fixed notsupportedexception due to resource table lookup in edmlibtests when run locally

- src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
- src/Microsoft.OData.Core/UriParser/ODataPathInfo.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
*This pull request fixes https://github.com/OData/AspNetCoreOData/issues/445*
In #2160 we added support for the `TypeSegment` after `NavigationPropertySegment`. 
Example: `~/Orders?$expand=Customer/Model.VipCustomer`
This means that we will expand only the Customers that are an instance of Model.VipCustomer.
Note: `Model.VipCustomer` is a derived type of the `Customer`.
Something that was not captured in that PR is scenarios where we have query options affecting properties that are only in the derived type but not in the base type.
Examples: 
`~/Orders?$expand=Customer/Model.VipCustomer($filter=VipCustomerID eq '12345')`
`~/Orders?$expand=Customer/Model.VipCustomer($expand=VipCustomerOrders')`
`~/Orders?$expand=Customer/Model.VipCustomer($orderby=VipEmail)`
This PR fixes that by ensuring …
> Fix cast in expand

- azure-pipelines-nightly.yml
- test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmEntityContainer.cs
- test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmEntitySet.cs
- test/FunctionalTests/Service/Microsoft/OData/Service/Providers/MetadataProviderEdmModel.cs
*This pull request addresses #2295.*
*There are tests that fail locally in `Microsoft.Data.ServerUnitTests1.UnitTests`. They are failing because we generally run local tests in `Debug` configuration and there are failing `Debug.Assert` calls. I have added building and testing some passing projects to the nightly builds so that we can get the use out of the `Debug.Assert` calls. I have also commented out the `Debug.Assert` calls to get this test project passing. Please see the commit description and comments for more details about why the assertion is failing.*
There will be more PRs which continue to address the local test failures.
> addressed local test failures from `Microsoft.Data.ServerUnitTests1.UnitTests`

- azure-pipelines-nightly.yml
- test/FunctionalTests/Tests/DataServices/UnitTests/RegressionUnitTests/Microsoft.Data.Web.RegressionUnitTests.csproj
This pull request fixes #2295.
Adding two more tests projects to run on the nightly builds with debug configuration. One project was previously not running with release configuration either because it lacked the .NET test SDK package reference. 
More projects will be added later.
> adding more tests to run with debug configuration during nightly builds

- src/Microsoft.OData.Edm/PublicApi/net45/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/PublicApi/netstandard1.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/Validation/ValidationRuleSet.cs
- src/Microsoft.OData.Edm/Validation/ValidationRules.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRuleSetTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes #2340.*
Exiting rule for validating that a key is not redefined only checks immediate base type. Fix makes sure that key is only defined once in the hierarchy.
For backward compatibility, this is added as a new rule, not part of the default ruleset, in order to ensure we don't break apps whose current schema validates but violate this rule.  The existing rule is marked as deprecated, and in 8.x. we should remove the old rule and make this rule part of the default ruleset.
Also marked an existing rule as obsolete because it is no longer valid due to a change in protocol. This was already removed from the default ruleset, but I added a comment explaining why and that it should also be removed in 8.x.
- [ x ] *Test cases added*
- [ x ] *Build and test with one-click …
> Validate key not defined multiple times in type hierarchy

- azure-pipelines-nightly.yml
- azure-pipelines-rolling.yml
This pull request addresses #2361.
Moving from `windows-lastest` pool to `windows-2019` pool to mitigate failures while the issue is being investigated. 
More work is necessary, pending discussion on the issue.
> Temporarily moving build pipelines from `windows-latest` to `windows-2019`

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterReader.cs
- src/Microsoft.OData.Core/ODataParameterReader.cs
- src/Microsoft.OData.Core/ODataParameterReaderCore.cs
- src/Microsoft.OData.Core/ODataParameterReaderCoreAsync.cs
- src/Microsoft.OData.Core/PublicAPI.Unshipped.txt
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Implement asynchronous support in **`ODataJsonLightParameterReader`**.
> Implement asynchronous support in ODataJsonLightParameterReader

- src/Microsoft.OData.Core/ODataCollectionReaderCore.cs
**`ODataJsonLightCollectionReader`** improvements to reduce delegate allocations
> ODataJsonLightCollectionReader improvements to reduce delegate allocations

- src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs
- src/Microsoft.OData.Core/ODataCollectionWriterCore.cs
- src/Microsoft.OData.Core/ODataParameterWriterCore.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Fix unnecessary delegate allocations across OData writers.
Also fixes buggy behaviour observed in exception cases where `TaskUtils`'s `FollowOnFaultWith` method is applied.
> Fix unnecessary delegate allocations across OData writers

- src/Microsoft.OData.Client/ALinq/ExpressionWriter.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceQueryProviderTests.cs
*This pull request fixes #2405.*
The `ConvertToUriLiteral` method used previous [does not do any escaping](https://github.com/OData/odata.net/blob/4e263ca4b94d01f2d105d8282c62ec272cfcd1bb/src/Microsoft.OData.Core/Uri/ODataUriUtils.cs#L93) so it's not the best fit for formatting literals.
In addition, `ConvertToUriLiteral` handles `ODataNullValue`, `ODataResourceValue`, `ODataCollectionValue`, `ODataEnumValue`, `ODataResource`, `ODataEntityReferenceLink`, `ODataEntityReferenceLinks`, `ODataResource` collection and primitive values. The only candidates for the "in" operator are primitive values so using this method is an overkill.
The change made in this PR is to use same method used to format values in other `Where` predicates
*If documentation update is needed, please add "Docs Needed" …
> Encode special chars in array elements in Contains expression

- src/Microsoft.OData.Core/Json/DefaultStreamBasedJsonWriterFactory.cs
- src/Microsoft.OData.Core/Json/IStreamBasedJsonWriterFactory.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactory.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactoryWrapper.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Related to #2421 
This PR adds the `CreateAsynchronousJsonWriter` method to the `IStreamBasedJsonWriter` interface that was introduced as part of the `ODataUtf8JsonWriter` work (https://github.com/OData/odata.net/pull/2416).
This method will allow the same interface to also be used to create `IJsonWriterAsync`. This is a change that is being back-ported from the currently pending PR that's implementing the async API for `ODataUtf8JsonWriter` (https://github.com/OData/odata.net/pull/2460).
The goal is to merge this PR before the next release so that when we release the async API for `ODataUtf8JsonWriter`, it will not be a breaking change.
> Add CreateAsynchronousJsonWriter to IStreamBasedJsonWriterFactoryAsync

- src/Microsoft.OData.Core/ODataNotificationReader.cs
- src/Microsoft.OData.Core/ODataNotificationStream.cs
- src/Microsoft.OData.Core/ODataNotificationWriter.cs
- src/Microsoft.OData.Core/ODataStream.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationStreamTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNotificationWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriteStreamTests.cs
Fixes `DisposeAsync` implementation by overriding base .NET Core 3.1 and higher
> Fix DisposeAsync implementation for .NET Core 3.1 and higher

- src/Microsoft.OData.Core/Batch/ODataBatchUtils.cs
- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchReader.cs
- src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs
- src/Microsoft.OData.Core/ODataRawOutputContext.cs
- src/Microsoft.OData.Core/ODataReadStream.cs
- src/Microsoft.OData.Core/ODataStream.cs
- src/Microsoft.OData.Core/ODataWriteStream.cs
- src/Microsoft.OData.Core/RawValueWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMultipartMixedBatchReaderTests.cs
*This pull request fixes https://github.com/OData/AspNetCoreOData/issues/624.*
Fix synchronous operations disallowed error when using Kestrel web server.
`AllowSynchronousIO` option is disabled by default from .NET Core 3.0.0-preview3 in (**Kestrel**, **HttpSys**, **IIS In-Process**, **TestServer**) web servers because these APIs are source of thread starvation and application hangs.
A call to `Dispose` method of `StreamWriter` from `RawValueWriter` was ultimately causing the `Flush` method of `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream` to be triggered.
As a result, a _**System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead**_ is thrown when using Kestrel web server.
What this …
> Fix synchronous operations disallowed error when using Kestrel web server

- benchmarks.yml
- src/Microsoft.OData.Core/Json/DefaultStreamBasedJsonWriterFactory.cs
- src/Microsoft.OData.Core/Json/IStreamBasedJsonWriterFactory.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataMessageWriter.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/AssertExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/DefaultStreamBasedJsonWriterFactoryAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockAsyncOnlyJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriterFactoryAsync.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactory.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockStreamBasedJsonWriterFactoryWrapper.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockSyncOnlyJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonLight/SingletonBatchRoundtripJsonLightTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/DefaultWriterCollection.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/ODataJsonWriterDirectPayloadWriter.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriter.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/Utf8JsonWriterDirectPayloadWriterWithArrayPool.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/WriterHelpers.cs
- test/PerformanceTests/SerializationComparisonsTests/README.md
*This pull request fixes #2421 
This PR adds an implementation of the `IJsonWriterAsync` API to `ODataUtf8JsonWriter`. At the basic level, it adds `Write***Async` methods to the `ODataUtf8JsonWriter` class.
I also had to make some changes to the `ODataJsonLightOutputContext`. This class was tightly coupled to the `JsonWriter` implementation. @gathogojr explained to me the rationale behind this: When writing spatial data we use a class that's part of Microsoft.Spatial library, that library expects an `IJsonWriter` (not the async version) as input. In the async methods we have an `IJsonWriterAsync`. So now we had to make sure that this `IJsonWriterAsync` is actually a JSON writer that implements both `IJsonWriterAsync` and `IJsonWriter`. We had to ensure that it's the same instance of the …
> Implement ODataUtf8JsonWriter async API

- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Semantics/CsdlSemanticsEntityContainerTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Add an officially supported method to get all navigation property bindings.
Retrieving all navigation property bindings requires quite some knowledge of the edm model implementation and casting.
This method encapsulated this logic. 
addresses #2060
> method to get all navigation property bindings

- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyConstants.cs
- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyModel.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes #2467.*
* Support Org.OData.Core.V1.AlternateKeys.
> Issue2467: Support Core.AlternateKeys

- src/Microsoft.OData.Core/BindingPathHelper.cs
- src/Microsoft.OData.Core/EdmExtensionMethods.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
This changes the type of the internal `ODataPath.Segments` property from `IList<ODataPathSegments>` to `IReadOnlyList<ODataPathSegments>` to prevent accidental modifications to the list. This property is really only passed to a single method: `BindingPathHelper.MatchBindingPath`, and it does not modify the list. `ODataPath` is intended to be immutable.
> Make ODataPath.Segments property read-only

- src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathTests.cs
*This pull request fixes #2488 
Creates a new constructor that takes `ODataPath` as input and uses `odataPath.segments` as input to copy the list of segments to the new `ODataPath`. Since we're passing a `List<T>` to a `List<T>`, it uses a faster copy using `Array.Copy` instead of iterating through the `IEnumerable` to add items to the list one at a time, which is less memory and CPU efficient. See [List<T> constructor](https://source.dot.net/#System.Private.CoreLib/List.cs,61) and [InsertRange](https://source.dot.net/#System.Private.CoreLib/List.cs,79de3e39e69a4811) implementations.
I made the new constructor internal to be on the safe side. To me it appears safe enough to be public. But, If I make it public, a different method overload will get called without the user having to opt-in …
> Create optimized ODataPath cloning constructor

- src/Microsoft.OData.Core/Json/DefaultStreamBasedJsonWriterFactory.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/DefaultStreamBasedJsonWriterFactoryAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/DefaultStreamBasedJsonWriterFactoryTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchWriterTests.cs
*This pull request fixes https://github.com/OData/AspNetCoreOData/issues/673
The `ODataJsonLightOutputContext` was passing the wrong stream to the `IStreamBasedJsonWriterFactory` when writing an async message. Normally, it [creates a `BufferedStream` that wraps the message stream](https://github.com/habbes/odata.net/blob/master/src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs#L108), then uses the buffered stream as the output stream for the async writer. But it was passing the message stream directly to the `IStreamBasedJsonWriterFactory`, meaning that the `ODataUtf8JsonWriter` was bypassing the `BufferedStream` and flushing its output to the internal message stream.
The issue arises because in WebAPI, the `DefaultODataBatchHandler` [copies contents from sub-request …
> Pass correct output stream to IStreamBasedJsonWriterFactory

- src/Microsoft.OData.Core/UriParser/Binders/EndPathBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/EndPathBinderTests.cs
This pull request fixes #1529.
In EndPathFinder validate, that a property was resolved, before checking if it is selected and suitable for aggregation.
> Fix #1529 by first checking that a property was found

- src/Microsoft.OData.Core/Evaluation/ODataConventionalIdMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataMetadataContext.cs
- src/Microsoft.OData.Core/JsonLight/JsonFullMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonLightMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonMinimalMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/JsonNoMetadataLevel.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs
- src/Microsoft.OData.Core/ODataContextUrlInfo.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- src/Microsoft.OData.Core/Uri/ODataUriSlim.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataMissingOperationGeneratorTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriterCoreTests.cs
*This pull request fixes #2163 
This PR introduces a new internal struct called `ODataUriSlim` to be used by `ODataWriterCore` instead of cloning `ODataUri` each time it enters a new scope. Now the scope stores a `ODataUriSlim` struct instead of a reference to the cloned `ODataUri`.
Making the type a struct avoids allocating instances to the heap. I have tried to keep the struct small by only storing properties that can be modified from one writer scope to another, namely the `SelectAndExpand` and `Path` properties. The other properties are never changed by the writer, and therefore do not need to be cloned.
To avoid excessive copies of the struct, I passed it by reference to all methods using the `in` keyword. Some copies were inevitable. For example, a copy will be made when assigning …
> ODataUriSlim struct

- src/Microsoft.OData.Client/Materialization/ODataEntityMaterializer.cs
*This pull request fixes #2518.*
Fix for `MaterializerEntry` `Id` property getter getting triggered in no tracking scenarios hence resulting into debug assertion failures. Apply logic similar to the one in `EntryValueMaterializationPolicy` at [this location](https://github.com/OData/odata.net/blob/a2bef7f438d9e936dbf1e3e16f993ee5b2fddad0/src/Microsoft.OData.Client/Materialization/EntryValueMaterializationPolicy.cs#L197)
> Fix MaterializerEntry Id property getter triggered in no tracking scenarios

- azure-pipelines-nightly.yml
- nightly.yml
- tools/CustomMSBuild/Versioning.props
*This pull request fixes #2510 *
Updates the version to 7.12.4. Also fixes the build pipeline so that the debug and release builds are copied to different directories, `Nuget-Debug` and `Nuget-Release` respectively. This avoids the confusion or the builds overwriting each other.
To verify that the write builds were stored in the right folder I ran a nighly pipeline and download the artifacts. The I unzipped the `.nupkg` and opened the the dlls in `ildasm` and followed the [instructions post here](https://www.codeproject.com/articles/1073360/how-to-tell-if-an-assembly-is-debug-or-release#:~:text=Here%27s%20how%20to%20do%20it%3A%201%20Open%20the,JIT%20Optimized%20-%20anything%20else%2C%20it%20is%20not%3A) to tell whether the build is JIT optimized or not:
- Open the `ildasm` (an easy way to …
> Update version 7.12.4

- src/Microsoft.OData.Core/ODataErrorDetail.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsAsyncTests.cs
This pull request fixes the ToJson function of ODataErrorDetail to escape characters that require it in JSON serialization. The calling function in ODataError already uses the GetEscapedJsonString function but the ODataErrorDetail currently does not. (See https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/ODataError.cs#L84)
The ToJson function of ODataErrorDetail does not properly escape characters that require it
N/A
> Change the tojson function of ODataErrorDetail to deal with escaped strings

- src/Microsoft.OData.Edm/Csdl/CsdlXmlWriter.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
*This pull request fixes #2522.*
Ensure `CsdlWriter` `TryWriteCsdl` method triggers flushing of `XmlWriter` buffer before exiting
> Fix issue where CsdlWriter TryWriteCsdl does not trigger flushing of XmlWriter buffer

- src/Microsoft.OData.Client/AtomMaterializerLog.cs
- src/Microsoft.OData.Client/BaseAsyncResult.cs
- src/Microsoft.OData.Client/BatchSaveResult.cs
- src/Microsoft.OData.Client/GroupByProjectionPlanCompiler.cs
- src/Microsoft.OData.Client/ProjectionPlanCompiler.cs
- src/Microsoft.OData.Client/QueryResult.cs
- src/Microsoft.OData.Client/SaveResult.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/CollectionValueMaterializationPolicyTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/EntryMaterializationPolicyForComplexResourceTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/EntryValueMaterializationPolicyUnitTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/FeedAndEntryMaterializerAdapterUnitTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/MaterializerEntryTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/ODataEntityMaterializerUnitTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/ODataEntriesEntityMaterializerUnitTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/PrimitiveValueMaterializationPolicyTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/TestMaterializerContext.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/T4/ODataT4CamelCaseTests.cs
*This pull request fixes #2531 
The `ProjectionPlanCompiler` and `GroupByProjectionCompiler` class call methods of the `ODataEntityMaterializerInvoker` dynamically using reflection/dynamic IL generation. Since the [PR that refactored the `MaterializerCache`](https://github.com/OData/odata.net/pull/2506), many materializer static methods needed to adjusted to accept an `IODataMaterializerContext` as input. 2 methods in `ProjectionPlanCompiler` expect a materializer context as the last argument: `ProjectionCheckValueForPathIsNull` and `ProjectionDynamicValueForPath`. `ProjectionPlanCompiler` calls both methods, but did not pass the materializer context to the `ProjectionCheckValueForPathIsNull`. There was not test covering this method, so we didn't notice. This method is called when there's …
> Fix ArgumentException in ProjectPlanCompiler caused by missing materializerContext argument in dynamic calls

- sln/OData.E2E.md
- sln/odata.md
Please refer to #2550 for more information.
> Update onboarding documentation to note that long repository root paths can cause build failures

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceSerializer.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
*This pull request fixes #2565.*
`odata.id` annotation property should not be written for transient complex resource
> odata.id annotation property should be written for transient complex resource

- src/Microsoft.OData.Core/ODataWriterCore.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
…adata, its key and concurrency-token property values must be provided
*This pull request fixes #2098.*
*Basically, to generate a link for a contained resource we need the id of the containing resource. If the id value wasn’t included in a $select, we don’t have the id so we can’t create the link and throw an exception. We used to catch and silently ignore this exception, which resulted in creating an invalid URL, which was bad.  However, now we throw an exception in cases we didn’t before, which is breaking existing apps.
We could fix this at the webapi level by always making sure the key properties are included (similar to the workaround someone provided), but by the time it gets to ODL it’s too late if the key property isn’t available.  The best we can do is probably to not generate …
> issue #2098: fix the issue ODataException: To compute an entity's metadata, its key and concurrency-token property values must be provided

- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Materialization/CamelCasedTypeMaterializationTests.cs
*This pull request fixes #2557, fixes #2514*
Fix performance regression in `DataServiceContext` `DefaultResolveType` method.
- By searching for the materialization type from the assembly containing the data service context instance **first**
- By searching for the materialization type from the executing assembly **next** - where it's different from the assembly in the first step
- By searching for the materialization type from the other loaded assemblies while skipping framework and OData libraries where the type wouldn't be expected to be
Performance improvements stats
**Before this fix:**
| Run |      Method |     Mean |     Error |    StdDev |
|-----:|------------ |---------:|----------:|----------:|
| 1 | ResolveType | 9.559 ms | 0.2664 ms | 0.7771 ms |
| 2 | ResolveType | 10.82 ms | …
> Fix performance regression in DataServiceContext DefaultResolveType method

- tools/IncrementVersion.ps1
*This pull request fixes #2439.*
Updated the `IncrementVersion.ps1` script to not duplicate the `PublicAPI.*.txt` files but instead concatenate them. Also updated the script to correctly increment minor versions (issue #2439, it currently will increment, for example, from 7.12.5 to 7.13.5 instead of 7.13.0).
> IncrementVersion.ps1 fixes

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs
- src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt
- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/Value/ODataBinaryStreamValue.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
#2596 
Add a capability for an `ODataBinaryStreamValue` to have its `Stream` disposed by ODL.
- This behavior is optional and is disabled by default for backward compatibility.
- Implemented via an internal property (`bool LeaveOpen`) rather than making `ODataBinaryStreamValue` an `IDisposable` in order to avoid a breaking change to the public API.
> Capability to close ODataBinaryStreamValue stream after serialization

- src/Microsoft.OData.Core/ContainerBuilderExtensions.cs
…er layer
*This pull request fixes #2601 .*
* Pass OData version to lower layer in AddDefaultODataServices
> fixes #2601: AddDefaultODataServices should pass OData version to low layer

- src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/VocabularyModelProvider.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
Update to latest OASIS Validation vocabulary
Fixes references to Core vocabulary
Fixes an issue where references to Core.* elements failed because the Core vocabulary was not referenced and Core was not defined as an alias.
Updates to the latest OASIS vocabulary.
Includes the edmx wrapper in order to provide references to other schemas.
Changes how the vocabulary is loaded to read as csdl and not just the schema element.
Updates tests
-should add a test for application of the OpenTypePropertyConstraint, that was broken prior to this fix.
-I removed an annotation for allowed values that is defined in the OASIS vocabulary because it references a type definition that is not defined in our core vocabulary.
> Update Validation Vocabulary

- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
This pull request fixes #2611.
Adds two new vocabulary annotation terms: RequiresExplicitBinding and ExplicitOperationBindings.
> Add vocabulary terms to Require Explicit Binding

- src/Microsoft.OData.Client/ALinq/QueryableResourceExpression.cs
- src/Microsoft.OData.Client/ALinq/ResourceBinder.cs
- src/Microsoft.OData.Client/ClientEdmModel.cs
- src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/ClientEdmModelTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/LinqIntegrationTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/TemplatingIntegrationTests.cs
*This pull request fixes #2598.*
* Fix
*1) DeclareKey on EntityType should be ordered based on the schema
2) Generate the request URL is canonical URL
with these changes:
```C#
var aEntities = container.AEntities.Where(a => a.CId == 8 && a.AId == "a" && a.BId == "b");
var aEntities = container.AEntities.Where(a => a.AId == "a" && a.BId == "b" && a.CId == 8);
var aEntities = container.AEntities.Where(a => a.BId == "b" && a.CId == 8 && a.AId == "a" );
```
Will output the same request URL as:
` ..../odata/AEntities(CId=8,BId='b',AId='a')`
> fixes #2598, Composite key entities PUT,PATCH URIs generated by OData Client do not follow key order

- benchmarks.yml
- src/Microsoft.OData.Core/Json/IJsonWriter.cs
- src/Microsoft.OData.Core/Json/IJsonWriterAsync.cs
- src/Microsoft.OData.Core/Json/JsonWriter.cs
- src/Microsoft.OData.Core/Json/JsonWriterAsync.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs
- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/Value/ODataJsonElementValue.cs
- src/Microsoft.OData.Core/Value/ODataValueUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockAsyncOnlyJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/MockSyncOnlyJsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataValueUtilsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/JsonReaderWriterInjectionTests.cs
- test/PerformanceTests/ComponentTests/Common/ODataMessageHelper.cs
- test/PerformanceTests/ComponentTests/ODataWriter/JsonElementPropertyTests.cs
- test/PerformanceTests/ComponentTests/ODataWriter/ODataWriterFeedTests.cs
- test/PerformanceTests/ComponentTests/ODataWriter/WriteFeedPropertyTypeTests.cs
This PR allows `ODataWriter` to write `JsonElement` values directly. This is useful in cases where then input payload is already in OData JSON format. In such cases you may want to adjust some of the input but keep most of it intact. The problem is that if you parse JSON input, then convert it to `ODataProperty/ODataValue` items, then write them out using `ODataMessageWriter`, you'd end up allocating JSON content multiple times, which can be costly.
Here's what the scenario that this feature enables:
- Assume workload response as a stream of size X bytes. 
- Stream is parsed to `JsonDocument` in `System.Text.Json` lib. 
- This new object is an index on top of memory stream. So extra X bytes are not allocated. 
- From this `JsonDocument`, `ODataEntry`/`ODataProperty` is created and sent to …
> Add support for writing JsonElement values in ODataWriter

- src/Microsoft.OData.Client/ProjectionPlanCompiler.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
*This pull request fixes #2617 .*
This was a regression caused by changes made in #2506, we fixed a similar issue in #2535.
In #2506 I added the `MaterializerContext` as a parameter to many existing methods, including methods in the `ProjectionPlanCompiler`. The problem is, the `ProjectionPlanCompiler` generates many method calls using reflection, and argument mismatch errors can only be caught at runtime. I went through all cases where the plan compiler generates method calls with reflection to ensure the materializer context argument is passed where needed. Hopefully I haven't missed any more cases this time.
> Fix ArgumentException regression in ProjectPlanCompiler

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightContextUriParser.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/ODataConstants.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightContextUriParserTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/ContextUriParserJsonLightTests.cs
This PR adds support for reading payloads with relative context URLs.  Currently we support `@context` with absolute URLS:  
EXA of a payload with a relative context URL that will be supported by these changes:
```json
{
"@context": "#$delta",
"value": [
{
"displayName": "Big cat",
"percentageWeight": 100
}
]
}
```
```json
{
"@context": "Products",
"value": [
{
"displayName": "Big cat",
"percentageWeight": 100
}
]
}
```
```json
{
"@context": "$metadata#Products",
"value": [
{
"displayName": "Big cat",
"percentageWeight": 100
}
]
}
```
> support reading relative context urls with bulk updates

- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
- tools/CustomMSBuild/Versioning.props
Update version to 7.15.0 for the next Release.
> Update version to 7.15.0

- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/PathSegmentValidator.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
ODataUriParser.Validate() throws Unable to cast object of type 'Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsActionImport' to type 'Microsoft.OData.Edm.IEdmOperation'.
if validating path to FunctionImport
> Fix function path validation

- src/Microsoft.OData.Core/TypeNameOracle.cs
- src/Microsoft.OData.Core/ValidationUtils.cs
- src/Microsoft.OData.Core/WriterValidator.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedSerializerUndecalredTests.cs
…g ODataPrimitiveValue, etc
*This pull request fixes #2659.*
* Enable use other OData value to serialize declared untyped property
> fixes #2659: Support declared Edm.Untyped property serialization using ODataPrimitiveValue, etc

- src/Microsoft.OData.Client/Materialization/MaterializerCache.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/BulkUpdateE2ETests.cs
This PR fixes the nightly build hang issue. So there are some tests that were added with the bulk updates changes that raised some `Debug.Asset` exceptions within the code. One of the tests was doing something that is not allowed ~ updating the entity descriptor's entity instance. The other test was looping through an empty for-loop which in turn led to hitting the `Debug.Assert` assertions within the code causing the hang-up. This is also the reason why the build hang only occurs in the `Debug` task and not the `Release` task. 
> fix nightly hang issue

- src/Microsoft.OData.Core/EdmExtensionMethods.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
*This pull request fixes #2689.*
When the OData path ends with a type segment and the `$expand` expression starts with a non-contained navigation property, the `ExpandedNavigationSelectItem` item in the `SelectExpandClause` has `Microsoft.OData.UnknownEntitySet` as the navigation source.
Detailed description of the issue can be found here #2689.
**Be noted:** A minor consequence of this change is that by making the additional call to `IEdmNavigationSource.FindNavigationTarget(IEdmNavigationProperty)` in the attempt to resolve the navigation target, that method returns a `Microsoft.OData.Edm.EdmUnknownEntitySet` if it fails to find the navigation target, as opposed to `Microsoft.OData.UnknownEntitySet` returned from `EdmExtensionMethods.FindNavigationTarget(IEdmNavigationSource, …
> Fix issue in finding navigation target for type segment present in OData path

- test/PerformanceTests/SerializationComparisonsTests/Lib/NoopJsonWriter.cs
The benchmark project could not compile because the `NoopJsonWriter` class did not implement the `IJsonWriter.Write(JsonElement)` method.
> Fix compiler error in SerializationComparisonsTests benchmarks

- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/JsonValueUtilsAsync.cs
- src/Microsoft.OData.Core/Json/NonIndentedTextWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonValueUtilsAsyncTests.cs
*This pull request fixes #2704 .*
The following async helper methods from `JsonValueUtils` had cases of synchronous I/O:
- `WriteEscapedJsonStringAsync`
- `WriteEscapedCharArrayAsync`
- `WriteValueAsync(byte[])`
Part of the reason was because the methods called other helper methods that performed synchronous `TextWriter.Write` calls. In such cases, I created true async versions of the affected methods.
The other reason was that the `NonIndentedTextWriter` did not override the async `WriteAsync(char[] buffer, int index, int count)` method. And the default implementation of `TextWriter.WriteAsync(char[], int, int)` calls the synchronous version. So I added an async override to the class.
Something else what pointing out is that because the internal `StreamWriter` is buffered, it would take …
> Remove sync I/O from JsonValueUtils async write methods

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
*This pull request fixes #2728 *
This PR adds support for `double.NaN`, `double.PositiveInfinity` and `double.NegativeInfinity` by serializing them as the strings `"NaN"`, `"INF"` and `"-INF"` respectively, to match the behaviour of the default `JsonWriter`.
> Add support for NaN and infinity to ODataUtf8JsonWriter

- src/Microsoft.OData.Core/UriParser/SemanticAst/EntitySetSegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/KeySegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/OperationSegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/SingletonSegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/TypeSegment.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/EntitySetSegmentTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/KeySegmentTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/SingletonSegmentTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/TypeSegmentTests.cs
Most of segments have set the identifier. But Some doesn't. Identifier is used to generate Id, it cannot be 'null'.
*This pull request fixes #2774.*
for example:
```C#
public class Foo
{
public IList<Base> BaseProperties {get;set;}
}
public class Base { }
public class Dervied : Base 
{
[Contained]
[AutoExpand]
public IList<EntityType> Entities {get;set;}
}
```
'Entities ' is a contained navigation property in a derived type. 
So, if we query "~/foos/1/BaseProperties", ODL will 'auto-expand' 'Entities' if the instance of BaseProperties item is a 'Derived'.
ODL will try to build the 'Id' for each item of 'Entities' in 'full' metadata. ODL will generate 'extra' segment to build the Url to access each item in 'Entities', So, ODL creates a 'TypeSegment' and uses "identifier" of the segment to …
> Fixes #2774: set the identifier for segments

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
This pull request fixes #2771 
https://github.com/OData/odata.net/issues/2771
I have applied small change in method InBinder.ProcessSingleQuotedStringItem
- I have updated test FilterAndOrderByFunctionalTests.FilterWithInOperationWithParensStringCollection_EscapedSingleQuote
> fix issue #2771 : fix method InBinder.ProcessSingleQuotedStringItem

- src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
- src/Microsoft.OData.Core/GlobalSuppressions.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
- src/Microsoft.Spatial/Microsoft.Spatial.csproj
- test/Common/Microsoft.Test.OData.DependencyInjection/Microsoft.Test.OData.DependencyInjection.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
*This pull request fixes #2780.*
Upgrade **Microsoft.Bcl.AsyncInterfaces** dependency to 7.0.0. We reference the Microsoft.Bcl.AsyncInterfaces package conditionally against .NetStandard2.0 framework. It should be safe to upgrade the dependency from 5.0.0 to 7.0.0 to since .NetStandard2.0 is one of the supported frameworks https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/7.0.0#supportedframeworks-body-tab
> Upgrade Microsoft.Bcl.AsyncInterfaces dependency to 7.0.0

- src/Microsoft.OData.Edm/Vocabularies/AlternateKeysVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/AuthorizationVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/MeasuresVocabularies.xml
- src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/AlternateKeysVocabularyTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/AuthorizationVocabularyTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CapabilitiesVocabularyTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
*This pull request fixes #2246.*
When trying to parse the OData core vocabulary CSDL (https://raw.githubusercontent.com/oasis-tcs/odata-vocabularies/main/vocabularies/Org.OData.Core.V1.xml) using the `CsdlReader`, an exception with the following message is thrown:
```
UnexpectedXmlAttribute : The attribute 'MaxLength' was not expected in the given context. : (523, 75)
```
The error in parsing the core vocabulary (Org.OData.Core.V1.xml) is caused by `SimpleIdentifier` type definition that has a `MaxLength` property:
```xml
<TypeDefinition Name="SimpleIdentifier" UnderlyingType="Edm.String" MaxLength="128">
<Annotation Term="Core.Description" String="A [simple identifier](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_SimpleIdentifier)" />
<Annotation …
```
> Fix issue in parsing OData core vocabulary

- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
This pull request upgrades **Microsoft.Bcl.AsyncInterfaces** dependency to 8.0.0 due to reported vulnerabilities in 7.0.0
> Upgrade Microsoft.Bcl.AsyncInterfaces dependency to 8.0.0

- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
The default `JsonWriter` and `Utf8JsonWriter`, while both use ISO8601 format to write `DateTimeOffset`, they differ in the specific case when the time zone offset is 0.
`JsonWriter` uses `Z` to indicate the offset: `2022-11-09T09:42:30Z`
`Utf8JsonWriter` uses `+00:00`, i.e.: `2022-11-09T09:42:30+00:00`
This PR changes `ODataUtf8JsonWriter` to make it consistent with `JsonWriter` when emitting 0-offset DateTimeOffset values.
In the `WriteValue(DateTimeOffset value)` method, we check if the offset is 0. If the offset is 0, then it uses the DateTimeOffset string formatting utility in `JsonValueUtils` to convert it to a string first.
You may be wondering, why not just convert all `DateTimeOffset` values to string and not just those with 0 offsets? Well it turns out that if you convert the …
> Use same format as JsonWriter when serializing DateTimeOffset with ODataUtf8JsonWriter

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/Json/PooledByteBufferWriter.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/ODataConstants.cs
- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- src/Microsoft.OData.Core/ODataMetadataOutputContext.cs
- src/Microsoft.OData.Core/ODataRawOutputContext.cs
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/PooledByteBufferWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterSettingsTests.cs
- test/PerformanceTests/SerializationComparisonsTests/JsonWriterBenchmarks/Benchmarks.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterAsyncPayloadWriter.cs
- test/PerformanceTests/SerializationComparisonsTests/Lib/ODataMessageWriterPayloadWriter.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes #2790 .*
This PR reduces allocations of buffer used by ODL's internal JSON writer:
- When using `JsonWriter`:
- made the buffer size of `BufferedStream` configurable using `ODataMessageWriterSettings.BufferSize`
- When using the `ODataUtf8JsonWriter`:
- we do not wrap the stream in a `BufferedStream` since `ODataUtf8JsonWriter` handles its own buffering
- replaces the `ArrayBufferWriter` used by `ODataUtf8JsonWriter` with a custom `PooledByteBufferWriter` that rents buffers from the Array pool
The `PooledByteBufferWriter` was adapted from .NET's implementation: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Text/Json/PooledByteBufferWriter.cs
**Update**: Instead of hardcoding the default size to a lower value, I made it configurable by …
> Reduce buffer allocations

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsEntitySet.cs
- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsSingleton.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
*This pull request fixes #2805 
This PR slightly reduces the cost of calling `IEdmNavigationSource.EntityType()` extension method. Firstly, it simplifies the method implementation by referring to the `IEdmNavigationSource.Type` directly instead of casting the interface to different sub-types and calling `.Type` on them.
This method works because for all code paths in the original code, the `Type` property was used to retrieve the `IEdmType` then cast to `IEdmEntityType`. Since `IEdmNavigationSource` has the `Type` property, we don't need the casts to access it. In the original code, `IEntitySetBase` was treated differently because its type is expected to be a collection type, in which case, the `ElementType` is called. This is now handled by the call to `AsElementType()`.
The current …
> Slight performance improvement for `IEdmNavigationSource.EntityType()`

- src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes #2804*
This PR adds an indexer to `ODataPath` to make random-access of segments in the path possible. This will help us simplify and optimize operations where we rely on Linq, `ToList()` or `PathHandler`s in hot paths.
With this PR, `ODataPath` would statisfy all the requirements of an `IReadOnlyList`, in that case, would it be harmful to explicitly implement that interface (even if in a future release)?
Once (if) this PR is merged, we can go ahead and make improvements to some path operations both in ODL and AspNetCoreOData (e.g. `path.NavigationSource()` extension method in AspNetCoreOData)
> Add index-based access to ODataPath

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReaderNestedPropertyInfo.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceDeserializer.cs
- src/Microsoft.OData.Core/PropertyAndAnnotationCollector.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceDeserializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Streaming/ODataJsonLightStreamReadingTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Streaming/ODataJsonLightStreamWritingTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/StreamReferenceValueReaderJsonLightTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Reader/AssociationLinkReaderTests.cs
- test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/Reader/PropertyReaderTests.cs
*This pull request fixes #2785.*
1) Can write property instance annotations without property value.
2) Can read property instance annotations without property value.
> fixes #2785: support property instance annotation without property value

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
- src/Microsoft.OData.Edm/Csdl/SerializationExtensionMethods.cs
- src/Microsoft.OData.Edm/EdmUtil.cs
- src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
- src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.txt
- src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs
- src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/Schema/EdmTargetPath.cs
- src/Microsoft.OData.Edm/Schema/Interfaces/IEdmTargetPath.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.TargetPath.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.TargetPath.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/EdmUtilTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/TargetHelperTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Schema/EdmTargetPathTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes #2070 .*
We define a new interface 
```csharp
public interface IEdmTargetPath: IEdmVocabularyAnnotatable
{
IEnumerable<IEdmElement> Segments { get; }
}
```
and a class that implements the interface
```csharp
public class EdmTargetPath : IEdmTargetPath
{
}
```
`EdmTargetPath` is used to handle the path to the model element that starts with `IEdmEntityContainer`. The `Segments` will contains the `IEdmElement`s in the target path.
e.g
```
MySchema.MyEntityContainer/MyEntitySet/MyProperty 
MySchema.MyEntityContainer/MyEntitySet/MyNavigationProperty 
MySchema.MyEntityContainer/MyEntitySet/MySchema.MyEntityType/MyProperty 
MySchema.MyEntityContainer/MyEntitySet/MySchema.MyEntityType/MyNavProperty
MySchema.MyEntityContainer/MyEntitySet/MyComplexProperty/MyProperty …
```
> Feature IEdmTargetPath to support path to a model element

- src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs
*This pull request fixes #2806
This PR improves the performance of creating an `ODataPrimitiveValue` instance for arguably the most common types (int, bool, string, dates, Guid). It does this by refactoring `IsPrimitiveType`. In the existing implementation, `IsPrimitiveType` checks whether the type is in the `PrimitveTypeReferenceMap` dictionary. This lookup is relatively costly. For most common types, I compare the type directly with the input CLR type using a compound `||` expression. Initially I had tried to put all the types in a long `||` expression, but what I found while benchmarking is that testing for types that were in the last predicates of the expression would take longer than looking them in the dictionary. So I tried to strike a balance by limiting the number of types I …
> Micro-optimization for `IsPrimitiveType`

- src/Microsoft.OData.Core/DuplicatePropertyNameChecker.cs
- src/Microsoft.OData.Core/Evaluation/ODataResourceMetadataContext.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/WriterValidator.cs
*This pull request fixes #2813 
This PR fixes a couple of "low-hanging" excessive memory allocaitons.
The `#if` flags we used to conditionally compile object-pooling for the `DuplicatePropertyNameChecker` only applied to .NET Standard 2.0. I've extended them to also cover .NET Core 3.1. The regression was probably introduced when we added `.netcoreapp3.1` as an explicit framework target.
I also made `NullDuplicatePropertyChecker` a "global" singleton instead of creating per request/WriterValidator. The impact here is low, but it doesn't hurt. In any case, I'd argue it makes the code cleaner anyway.
Found a case of `Func<T,bool>` lurking on a hot path from calling `resource.NonComputedProperties.SingleOrDefault(r => r.Name == propertyName)`. I reduced the allocation by implementing …
> Fix memory regression in DuplicatePropertyNameChecker

- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FullUriFunctionalTests.cs
Add test case to verify built-in function in $orderby
*This pull request fixes #2829.*
Let's verify built-in function supported in ODL>
> Fixes #2829: support built-in function in $orderby.

- src/Microsoft.OData.Core/ODataResource.cs
- src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataResourceTests.cs
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl
- test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes #2803*
This PR adds a `SkipPropertyVerification` property to `ODataResource` which skips property verification. By default, `ODataResource` will verify the property values when the `Properties` property is set. The aim of the of the verification is to ensure that properties `ODataResourceValue`s are not included in the properties. I.e. the property values should either primitive types or collections of primitive types (`ODataResourceValue` is intended for use in annotations).
However, in scenarios like AspNetCoreOData, where the library already creates `ODataResource` that already match this expectation, it's an unnecessary cost to still go ahead and perform this verification. This flag can be used in AspNetCoreOData to avoid paying this cost for every resource …
> Add flag to skip property verification in `ODataResource`

- README.md
- azure-pipelines-nightly.yml
- azure-pipelines-rolling.yml
- benchmarks.yml
- tools/Release/CreateAndPushBranch.ps1
Since we renamed the default branch from `master` to `main`. This PR updates our docs, pipelines and scripts accordingly.
> Rename master to main

- README.md
- azure-pipelines-nightly.yml
- azure-pipelines-rolling.yml
This PR adds `dev-8.x` branch to the build pipeline triggers so that checks are triggered when a PR is made against the `dev-8.x` branch.
I also added a note in the README about the `dev-8.x` branch.
> Add dev-8.x branch to pipeline trigger

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
*This pull request fixes #2845.*
This pull request introduces functionality to handle the writing of large string and byte array values. It accomplishes this by breaking down oversized strings and bytes into smaller chunks and directly writing them to the buffer.
The process involves first checking if the size of the string or byte array exceeds the buffer's capacity. If it does, the program iterates through the large string, dividing it into chunks of a predefined size. Each chunk is then written to the buffer until the entire string is successfully written.
Furthermore, special characters within the string are properly escaped to ensure accurate representation during the writing process.
Methods added: 
1. WriteStringValueInChunks(ReadOnlySpan<char> value)
2. …
> Support writing large json base64 and string values

- src/Microsoft.OData.Core/Json/IJsonWriter.cs
- src/Microsoft.OData.Core/Json/IJsonWriterAsync.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
- src/Microsoft.OData.Core/JsonLight/ODataJsonLightSerializer.cs
- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsAsyncTests.cs
*This pull request fixes #2478.*
Deprecate support for JsonPCallback
We currently wrap a response will a callback function if the callback function is specified using the `JsonPCallback` property of `ODataMessageWriterSettings` class. Owing to the decision to ensure that in 8.x customers can still write the same payload they did in 7.x, I opted for decorating the `JsonPCallback` property with `Obsolete("This will be dropped in 9.x release")` attribute. No additional value would be derived from introducing a compatibility flag for the customer to toggle since they can express that intention by initializing the `JsonPCallback` property or leaving it uninitialized.
This pull request also marks as obsolete the following methods defined in `IJsonWriter` and `IJsonWriterAsync`:
- …
> ODL 8.x - Deprecate support for JsonPCallback

- src/Microsoft.OData.Client/DataServiceContext.cs
- test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/DataServiceContextTests.cs
Partially addresses #2208 
- Marks the `DataServiceContext.KeyComparisonGeneratesFilterQuery` property as deprecated for removal in the next major release. This property was added to avoid breaking changes when we made Where clause generate a `$filter` query even when the predicate was only a key lookup.
- Changes the default value of the property from `false` to `true`.
> [ODL 8]: Deprecate `KeyComparisonGeneratesFilterQuery` and set default to `true`.

- src/Microsoft.OData.Core/Value/ODataBinaryStreamValue.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedSerializerUndecalredTests.cs
*This pull request fixes https://github.com/OData/odata.net/issues/2599*
> Default leaveOpen to false in ODataBinaryStreamValue constructor

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
* support writing large string values in utf8jsonwriter
porting this change from main branch 
> Support writing large json base64 and string values (#2846)

- test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests/HttpClientRequestMessage.cs
- test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests/RequestMessageArgsTests.cs
This pull request removes `Credentials` and `ReadWriteTimeout` deprecated overrides
This pull request removes `Credentials` and `ReadWriteTimeout` deprecated overrides inadvertently forgotten in a previous pull request
> Remove Credentials and ReadWriteTimeout deprecated overrides

- src/Microsoft.OData.Core/Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/Microsoft.OData.Core.txt
- src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
- src/Microsoft.OData.Core/TypeUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/TypeUtilsTests.cs
Cherry-pick [Throw an ODataException with helpful message when type name in context URL is not qualified](https://github.com/OData/odata.net/pull/2892) into dev-8.x
> Throw an ODataException with helpful message when type name in context URL is not qualified

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.Stream.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.TextWriter.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonTextWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterStreamTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
This PR contains the following changes: 
1.  I structured the ODataUtfJsonWriter as a partial class to mitigate the accumulation of excessive code within this class related to supporting streaming APIs. With this restructuring, I added two new partial classes: `ODataUtf8JsonWriter.Stream.cs` and `ODataUtf8JsonWriter.TextWriter.cs`
2. The `ODataUtf8JsonWriter.Stream.cs` class offers a stream for writing streaming data using the ODataUtf8JsonWriter.  
3. The ODataUtf8JsonWriter.TextWriter.cs class offers a TextWriter for writing streaming data using the ODataUtf8JsonWriter.
4. I enabled the tests: `WriteStreamValue_UsingODataUtf8JsonWriter` and `WriteBinaryValueToStream_WithODataUtf8JsonWriter_Async` that had been disabled. 
5. I'm handling the incoming data …
> Implement streaming API in ODataUtf8JsonWriter

- src/Microsoft.OData.Core/GlobalSuppressions.cs
- src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/UrlValidation/ODataUrlValidationContext.cs
- src/Microsoft.OData.Core/UrlValidation/Rules/DeprecationRules.cs
- src/Microsoft.OData.Core/UrlValidation/Rules/RequireSelectRules.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/ODataUrlValidatorTests.cs
*This pull request fixes #[2789](https://github.com/OData/odata.net/issues/2789).*
`ODataUrlValidationContext` public sealed class is used to store context when validating an OData URL.
The class has an internal constructor and currently the only means to instantiate the class is by calling `ODataUrlValidator.ValidateUrl` method.
The class has a `AddMessage` public message that should be the means through which `ODataUrlValidationMessage` should be added to the collection of validation messages.
However, the `Messages` collection property is exposed as a `List<ODataUrlValidationMessage>` and this makes it possible to circumvent the `AddMessage` method and add items to the collection directly.
This violates validation rule [CA1002: Do not expose generic …
> Fix CA1002 violiation on ODataUrlValidationContext class

- test/FunctionalTests/Microsoft.OData.Client.Tests/Serialization/HttpClientRequestMessageTests.cs
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/MediaStreaming.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/StateChange.vb
- test/FunctionalTests/Tests/DataServices/UnitTests/ClientUnitTests/UpdateTests.vb
Fix ODL-8 E2E solution build failures. Some references in test code were not refactored.
> Fix ODL-8 E2E solution build failures

- src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/UriParser/SemanticAst/EntitySetSegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/INavigationSourceSegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/NavigationPropertySegment.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/SingletonSegment.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/EntitySetSegmentTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/NavigationPropertySegmentTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/SingletonSegmentTests.cs
*This pull request fixes #2528.*
Adds `INavigationSourceSegment` interface that `EntitySetSegment`, `SingletonSegment` and `NavigationPropertySegment` implement so that there is a consistent way to retrieve the "navigation source" from those segments.
> Add INavigationSourceSegment interface for navigation source segments

- src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
- src/Microsoft.Spatial/Microsoft.Spatial.csproj
- test/Common/Microsoft.Test.OData.DependencyInjection/Microsoft.Test.OData.DependencyInjection.csproj
- test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
- test/FunctionalTests/Microsoft.OData.TestCommon/Microsoft.OData.TestCommon.csproj
- test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
We are not planning to support .NET Framework in the first preview release. This PR therefore removes .net48 from target frameworks. This removes support, but it would be easy to add support again if we change our plan before the final release
Note that as a result of this change the **E2E test projects will not compile**.
> Remove .NET Framework 4.8 target framework

- buildandtest.yml
- tools/CustomMSBuild/Versioning.props
Sets the version to `8.0.0-preview.1`.
Added .NET Core App 2.1 to the build pipeline because it's required by the ESRP codesigning task. We should consider updating the task.
> Set the version to 8.0.0-preview.1

- src/Microsoft.OData.Core/ODataMessageWriter.cs
- src/Microsoft.OData.Core/ODataMessageWriterSettings.cs
- src/Microsoft.OData.Core/PublicAPI/net48/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/JsonLight/ODataJsonLightWriterComplexIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredAnnotationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightOutputContextTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataEntityReferenceLinkTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataEntityReferenceLinksTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterSettingsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Streaming/ODataJsonLightStreamWritingTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/ODataJsonLightSingletonWriterTests.cs
*This pull request fixes #2844 
This PR adds a `ShouldIncludeAnnotation` property to the `ODataMessageWriterSettings` that allows developers to force a custom instance annotation to be written even if it was not included in the preference header annotation filters (`odata.include-annotations:`)
It works as follows:
- The property is a `Func<string, bool>` that receives an annotation name and returns true if the annotation should be written
- If the writer was going to skip a certain annotation (e.g. because it was not part of the annotations filter), it will check this delegate before skipping the annotation. If the delegate returns true, then the annotation will not be skipped.
Note that if the writer was going to write an annotation (e.g. because of it's part of the annotation filters), …
> Add public ShouldIncludeAnnotation property

- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
*This pull request fixes #2950*
Adds the `Microsoft.Extension.ObjectPool` dependency to the NuGet config so that it can get installed on the customer's machine when they install our libraries.
> Add ObjectPool dependency to nuget config

- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
- tools/CustomMSBuild/Versioning.props
Fixes #2950 for ODL 8.
Without this fix, the Microsoft.Extensions.ObjectPool package is not installed automatically when you add OData library packages to your project. Without that package, a `TypeLoadException` will be raised when you try to write a resource with duplicate name checker validation enabled (which is the default).
And upgrades the version to `8.0.0-preview.2`.
Note: This fix has already been shipped in `7.21.1`. See: https://github.com/OData/odata.net/pull/2954
> Fix nuget config and update to preview.2

- src/Microsoft.OData.Client/BaseEntityType.cs
- src/Microsoft.OData.Client/IBaseEntityType.cs
- src/Microsoft.OData.Client/Materialization/EntryValueMaterializationPolicy.cs
- src/Microsoft.OData.Client/MaterializeFromAtom.cs
- src/Microsoft.OData.Client/PublicAPI/net8.0/PublicAPI.Unshipped.txt
*This pull request fixes #2593 and fixes #2291 
This PR renames the `IBaseEntityType.Context` property to `DataServiceContext`. The name `Context` is a relatively common property name in customer schemas and this is therefore a common source of naming conflicts which result in compilation or runtime errors. We expect `DataServiceContext` to be less susceptible to conflicts, it's also more specific, so this doesn't hurt readability of the code.
The issue could be resolved by the customers by changing the generated property name manually to remove the conflict. But this would means they would have to make that change each time the regenerate the code (e.g. after an update to the CSDL). This leads to unfavorable developer experience.
We may also make changes to the code generation logic in …
> Rename IBaseEntityType.Context to DataServiceContext

- src/Microsoft.OData.Core/UriParser/ODataPathInfo.cs
*This pull request fixes #2796*
Avoid calling .Current on an empty enumerator.  Calling Current is not valid unless MoveNext() has returned true and in net8.0 this was enforced.
> Support net8.0 - Avoid evaluating Current on an empty enumerator

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs
- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaXmlWriter.cs
- src/Microsoft.OData.Edm/PublicAPI/net48/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/Vocabularies/Annotations/EdmVocabularyAnnotation.cs
- src/Microsoft.OData.Edm/Vocabularies/Annotations/IEdmTermExtensions.cs
- src/Microsoft.OData.Edm/Vocabularies/Annotations/IEdmVocabularyAnnotation.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.VocabularyAnnotation.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ConstructibleModelErrorCases.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/ConstructibleVocabularyTestsUsingConverter.cs
- test/FunctionalTests/Tests/DataEdmLib/FunctionalUtilities/InterfaceCriticalModelBuilder.cs
- test/FunctionalTests/Tests/DataEdmLib/VocabularyStubs/StubVocabularyAnnotation.cs
This PR fixes https://github.com/OData/odata.net/issues/2228
This PR adds the `UsesDefault` property to `IEdmVocabularyAnnotation`.  
We do not write an `EdmVocabularyAnnotation's` value if it has a default value. 
That's why we do the check and set the `UsesDefault` value to either true or false. 
When creating an `EdmVocabularyAnnotation` if the value is not provided, we check whether the EdmTerm has a default value or not. If the term has a default value and no value was provided, we set the `UsesDefault` to true, otherwise false. 
This PR already has this logic and tests. The only change that I made was: 
1. I added a new extension method for creating an `EdmVocabularyAnnotation` when a value is provided as we already have an extension method for creating an `EdmVocabularyAnnotation` …
> Add UseDefault property to IEdmVocabularyAnnotation

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs
Fix async wrapper over sync API in reading nested property info - prevent inadvertent sync IO
This is why/how the sync method was being called:
https://github.com/OData/odata.net/blob/383e29f3cb96eda22e76d19df7bdab11459377b8/src/Microsoft.OData.Core/ODataReaderCoreAsync.cs#L88-L91
The async methods are declared in the `ODataReaderCoreAsync` base class and their default implementation is to wrap the sync method.
If they're not overridden in the derived class, they'll do sync IO. The `ReadAtNestedPropertyInfoImplementationAsync` was inadvertently not overridden in `ODataJsonLightReader` class.
> Fix async wrapper over sync API in reading nested property info

- src/Microsoft.OData.Core/Json/JsonValueUtils.cs
- src/Microsoft.OData.Core/Json/ODataJsonOutputContext.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriterFactory.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.Stream.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.TextWriter.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- src/Microsoft.OData.Core/ODataServiceCollectionExtensions.cs
- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/Json/ODataJsonWriterShortSpanIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/Json/PropertyAndValueJsonWriterIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonOutputContextTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonServiceDocumentSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterFactoryAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterFactoryTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
*This pull request fixes #2822*
This PR:
- Sets `ODataUtf8JsonWriter` as the default `IJsonWriter` used in `ODataMessageWriter`.
- Sets `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` as the default `JavaScriptEncoder` for `ODataUtf8JsonWriter`.
- Fixes some bugs with `ODataUtf8JsonWriter` streaming (see details at the end)
- Normalizes JSON output for some edge cases for better consistency with `JsonWriter` (see details at the end).
Both of these changes aim to improve _default_ serialization performance. `ODataUtf8JsonWriter` has demonstrated better performance and memory efficiency over the current default `JsonWriter` in benchmarks and in production workloads. One of the major blockers to it becoming the default was lack of support for streaming, but that has been addressed by #2880 …
> Set `ODataUtf8JsonWriter` as default `JsonWriter`

- src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Metadata/ClientTypeUtilTests.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextQueryTests.cs
*This pull request fixes #2964.*
*This change involves adding functionality to support the use of `enumeration types` as `keys`.*
Currently, attempting to query entities with `enums as keys` through `OData Client`, results in an error stating that the operation is not valid for non-generic types. 
**Exception**:
`This operation is only valid on generic types.`
**Change**:
This modification will address this issue, allowing `enums` as keys without causing exceptions.
For example, the below `Employee` `object` has `EmpType` which is a key of `Type Enum` and `NullableEmpType` which is `nullable generic Type with Enum as generic argument`.
```cs
public class Employee
{
[System.ComponentModel.DataAnnotations.Key]
public int EmpNumber { get; set; }
// Enum - Employee Type Key …
```
> Support Enums as Keys in OData Client

- src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
- src/Microsoft.OData.Core/EdmExtensionMethods.cs
- src/Microsoft.OData.Core/UriParser/Binders/MetadataBindingUtils.cs
- src/Microsoft.OData.Core/UriParser/TypePromotionUtils.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Metadata/ClientTypeUtilTests.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextQueryTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/MetadataBindingUtilsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/TypePromotionUtilsTests.cs
Cherry-pick https://github.com/OData/odata.net/commit/c313eae66a2cb42a1b8e4e5bed1a6b3b9a448068 and https://github.com/OData/odata.net/commit/3080ebc49f97c71c4a0642e25af986f73c6011f6 into dev-8.x branch
> Add support for Enums as Key in OData Client and Allow $filter with integer value in squote and without squote

- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CollectionTests/Server/CollectionNullableFacetTestController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CollectionTests/Tests/CollectionNullableFacetTest.cs
This PR ports collection tests from depending on WCF services to use `Microsoft.AspNetCore.OData` APIs. 
Here are the tests being ported: https://github.com/OData/odata.net/blob/main/test/EndToEndTests/Tests/Client/Build.Desktop/CollectionTests/CollectionNullableFacetTest.cs
These tests verify the behavior of a collection property in a structural entity specifically focussing on the nullable facet of the collection.  For instance, the test checks that a collection structural property with the nullable facet set to false cannot have a null element.  It also verifies that the collection can be empty. 
> Port collection tests

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/EnumFilterFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes #2371.*
This change is to fix the issue raised where the `in` operator does not allow using a `string` or `integer` literal as left operand when comparing against a collection of enums.
The change involves:
- Checking if the` left operand` is either an `integral` or a `string` type and the `right operand` is a collection of enums. 
- If this is true, it calls `MetadataBindingUtils.ConvertToTypeIfNeeded()` method to try convert the left operand to the same enum type if possible. 
- If this is not possible, exception is thrown.
Assume you have the following entity:
```cs
public class Employee 
{
public int Id { get; set; }
public string Name { get; set; }
public List<WeekDay> WorkingDays { get; set; }
}
public enum WeekDay
{
Monday = 1,
Tuesday = 2,
Wednesday = 3, …
```
> Fix for Error occurs when you check whether a string or integer literal is in an enum collection

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/EnumFilterFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
Cherry-pick https://github.com/OData/odata.net/commit/7d5c6c553f0229522e3520109604263691769525
> Cherry-pick (7d5c6c5): Fix for Error occurs when you check whether a string or integer literal is in an enum collection

- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ActionOverloadingTests/Server/PeopleController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ActionOverloadingTests/Tests/ActionOverloadingEndToEndTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ActionOverloadingTests/Tests/ActionOverloadingQueryTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CollectionTests/Server/CollectionNullableFacetTestController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CollectionTests/Tests/CollectionNullableFacetTest.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/Default/DefaultContainer.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/Default/DefaultServiceCsdl.xml
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/EndToEnd/DefaultContainer.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/EndToEnd/EndToEndServiceCsdl.xml
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/OpenTypes/OpenTypeServicesContainer.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/OpenTypes/OpenTypesODataServiceCsdl.xml
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/Default/DefaultDataModel.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/Default/DefaultDataSource.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/Default/DefaultEdmModel.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/EndToEnd/CommonEndToEndDataModel.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/EndToEnd/CommonEndToEndDataSource.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/EndToEnd/CommonEndToEndEdmModel.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/OpenTypes/OpenTypesServiceDataSource.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Server/OpenTypes/OpenTypesServiceEdmModel.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Microsoft.OData.Client.E2E.Tests.csproj
This PR contains some of the common data sources, Edm models and model classes used by the various E2E tests. 
The ported sources and models can be found here:  
https://github.com/OData/odata.net/blob/release-7.x/test/EndToEndTests/Services/Astoria/OpenTypes/DefaultContainer.cs
https://github.com/OData/odata.net/blob/release-7.x/test/EndToEndTests/Services/Astoria/Default/DefaultContainer.cs
https://github.com/OData/odata.net/blob/release-7.x/test/EndToEndTests/Services/Astoria/Default/Entities.cs
> Update common models and data sources

- test/EndToEndTests/Common/Microsoft.OData.Client.E2E.TestCommon/TestStartupBase.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Server/ClientQueryTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Server/ClientTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Server/ClientUpdateTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Server/OpenTypesTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Tests/ClientDeleteTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Tests/ClientEntityDescriptorTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Tests/ClientOpenTypeUpdateTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Tests/ClientQueryTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Tests/ClientUpdateTests.cs
This PR ports E2E client tests from depending on WCF services to use Microsoft.AspNetCore.OData. Here is a link to the tests that need porting: 
These tests test different OData Client features like: the different query options like `$filter`, `$top`, `$expand`, `$skip`, the various methods used to delete, add and update objects from OData Client.  
https://github.com/OData/odata.net/tree/main/test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests
> Port client tests

- test/EndToEndTests/Common/Microsoft.OData.Client.E2E.TestCommon/Common/HttpClientRequestMessage.cs
- test/EndToEndTests/Common/Microsoft.OData.Client.E2E.TestCommon/Common/HttpClientResponseMessage.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/Default/DefaultContainer.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Common/Client/Default/DefaultServiceCsdl.xml
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ComplexTypeTests/Server/ComplexTypeTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ComplexTypeTests/Tests/ComplexTypeTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ODataItemWrapper.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ODataNestedResourceInfoWrapper.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ODataResourceSetWrapper.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ODataResourceWrapper.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ODataWriterHelper.cs
This PR ports E2E client tests from depending on WCF services to use Microsoft.AspNetCore.OData. Here is a link to the tests that need porting: https://github.com/OData/odata.net/blob/release-7.x/test/EndToEndTests/Tests/Client/Build.Desktop/ComplexTypeTests/ComplexTypeTests.cs
These tests test complex types in ODataNet. How they are read, written, how they work with the different OData query  options. How they work in open types, derived types etc. 
> Port complex tests

- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataPathInfoTests.cs
Related to #2978. Add `ODataPathInfo` tests for .NET 8.0
> Add ODataPathInfo tests

- src/Microsoft.OData.Client/ALinq/DataServiceQueryProvider.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/SequenceMethodsTests.cs
*This pull request fixes #1996.*
This PR implmements `Any` method support. (Internally it fakes a `Count` request and transforms numeric response into boolean value).
It also adds support for the following sequence methods:
`AnyPredicate`, `CountPredicate`, `LongCountPredicate`, `FirstPredicate`, `FirstOrDefaultPredicate`, `SinglePredicate`, `SingleOrDefaultPredicate`
E.g.:
```csharp
var ctx = new DataServiceContext(new Uri(...));
var dataSet = ctx.CreateQuery<Customer>("Customers");
// The following lines will work fine without throwing Exception now:
bool exists1 = dataSet.Any();
bool exists2 = dataSet.Any(c => c.Name.Contains("ab"));
int count1 = dataSet.Count(c => c.Name.Contains("ab"));
long count2 = dataSet.LongCount(c => c.Name.Contains("ab"));
Customer c1 =  dataSet.First(c => …
```
> Add support for "Any" and Predicates method call expressions

- src/Microsoft.OData.Client/ALinq/DataServiceQueryProvider.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/SequenceMethodsTests.cs
This PR cherry picks #2863 to port support for LINQ's `Any()` method, which was added to the 7.x branch to 8.x.
Fixes #1996
> Port to 8.x: Add support for "Any" and Predicates method call expressions (#2863)

- test/EndToEndTests/Common/Microsoft.OData.Client.E2E.TestCommon/Common/TestHttpClientRequestMessage.cs
- test/EndToEndTests/Common/Microsoft.OData.Client.E2E.TestCommon/Common/TestHttpClientResponseMessage.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ComplexTypeTests/Tests/ComplexTypeTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ContainmentTests/Tests/ContainmentTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/EdmDateAndTimeOfDayTests/Server/EdmDateAndTimeOfDayTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/EdmDateAndTimeOfDayTests/Tests/EdmDateAndTimeOfDayTests.cs
This PR ports E2E client tests from depending on WCF services to use Microsoft.AspNetCore.OData. Here is a link to the tests that need porting: https://github.com/OData/odata.net/tree/release-7.x/test/EndToEndTests/Tests/Client/Build.Desktop/EdmDateAndTimeOfDay
These tests test the usage of Edm.Date and TimeOfDay in OData.Net
> Port EdmDateAndTimeOfDayTests

- buildandtest.yml
- nightly.yml
- src/Microsoft.OData.Core/ODataMessageReader.cs
- src/Microsoft.OData.Core/ODataMessageWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/MessageWriterConcurrencyTests.cs
Removes calls to GetRequiredService<ODataMessageInfo> as these instances are overwritten immediately.
Simplifies their creation to call stacks where they are needed.
> Update message writer and reader to ignore Message info from DI 

- src/Microsoft.OData.Core/ODataMessageReader.cs
- src/Microsoft.OData.Core/ODataMessageWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/MessageWritterConcurrencyTests.cs
Ports the changes to Update message writer and reader to ignore Message info from DI (#3058) to ODL 7x
> Port Update message writer and reader to ignore Message info from DI (#3058) to ODL 7x

- src/Microsoft.OData.Core/ODataServiceCollectionExtensions.cs
- src/Microsoft.OData.Core/UriParser/ODataUriParserSettings.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataServiceCollectionExtensionTests.cs
*This pull request fixes #3070 *
Clones the reader, writer and URI parser settings when registering them as scoped services in `AddDefaultODataServices()` to ensure that different request scopes get different copies that can be independently modified.
> Isolate scoped settings in default OData services

- .gitignore
- buildandtest.yml
- test.runsettings
- test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
- test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
- test/FunctionalTests/Tests/DataOData/Tests/OData.PluggableFormat/Microsoft.Test.OData.PluggableFormat.csproj
- test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeepInsertE2ETests.cs
- test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj
Fix code coverage analysis
Restrict code coverage analysis to only the ODL libraries:
> Fix code coverage analysis

- src/Microsoft.OData.Client/Serialization/PrimitiveType.cs
- src/Microsoft.OData.Client/Serialization/PrimitiveXmlConverter.cs
- src/Microsoft.OData.Core/Evaluation/EdmValueUtils.cs
- src/Microsoft.OData.Core/Evaluation/LiteralFormatter.cs
- src/Microsoft.OData.Core/Json/JsonWriterExtensions.Async.cs
- src/Microsoft.OData.Core/Json/JsonWriterExtensions.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriterUtils.cs
- src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs
- src/Microsoft.OData.Core/ODataPayloadValueConverter.cs
- src/Microsoft.OData.Core/ODataRawValueUtils.cs
- src/Microsoft.OData.Core/Uri/ODataUriConversionUtils.cs
- src/Microsoft.OData.Edm/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Edm/Schema/Date.cs
- src/Microsoft.OData.Edm/Schema/TimeOfDay.cs
- src/PlatformHelper.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonValueSerializerAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Metadata/EdmLibraryExtensionsTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageReaderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Evaluation/KeyGenerationPinningTest.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/Json/BinaryValueEncodingTests.cs
*This pull request fixes #2293.*
OData.Spec defines the following two primitive types:
From OData model perspective, it only knows `Edm.Date` and `Edm.TimeOfDay`. 
We'd resolve the mapping between the Edm types and C# types from the real value.
OData library maps 'Edm.Date' to '[Microsoft.OData.Edm.Date](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Schema/Date.cs)' struct and 'Edm.TimeOfDay' to '[Microsoft.OData.Edm.TimeOfDay](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Schema/TimeOfDay.cs)' struct. 
However, neither 'Date' type nor 'TimeOfDay' is supported in database side.
Now since .NET 6, two new primitive types have introduced into the 'System" namespace as:
They are widely used in modern database side and EF core supports them. See …
> Fixes #2293: Enable DateOnly and TimeOnly

- src/Microsoft.OData.Edm/Csdl/SchemaWriter.cs
- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSerializationVisitor.cs
- src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelSchemaSeparationSerializationVisitor.cs
- src/Microsoft.OData.Edm/EdmModelVisitor.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/AsyncYieldStream.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.Async.cs
*This pull request fixes [#1320](https://github.com/OData/AspNetCoreOData/issues/1320).*
Refactors the code to use the asynchronous method `VisitCollectionAsync` instead of the synchronous `VisitCollection`. The **VisitCollectionAsync** method has the second parameter as `Func<T, Task>` as opposed to **VisitCollection** which has the second parameter as `Action<T>`.  This change ensures that the method is awaited properly, maintaining the correct order of execution in an asynchronous context.
The `ProcessEntityContainerAsync` passed as argument to `VisitCollectionAsync` is an asynchronous method that processes the entity container and at the end `WriteEndElementAsync` is called to write the end element. Using **VisitCollectionAsync** …
> Fix issue #1320 metadata async issue

- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriterValidationTests.cs
This pulls adds OData writer validation tests for unhappy paths that were mostly untested. Step 1 of 2 towards improving OData writer validation error messages relevant to this reported issue https://github.com/OData/odata.net/issues/2960
> Add OData writer validation tests for unhappy paths

- src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs
- src/Microsoft.OData.Core/UriParser/CustomUriLiteralPrefixes.cs
- src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs
- src/Microsoft.OData.Core/UriParser/ExpressionLexerLiteralExtensions.cs
- src/Microsoft.OData.Core/UriParser/ExpressionLexerUtils.cs
- src/Microsoft.OData.Core/UriParser/ExpressionToken.cs
- src/Microsoft.OData.Core/UriParser/Parsers/CountSegmentParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/FunctionCallParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/FunctionParameterParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/IdentifierTokenizer.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SearchParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandOptionParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandTermParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs
- src/Microsoft.OData.Core/UriParser/Parsers/UriTemplateParser.cs
- src/Microsoft.OData.Core/UriParser/SearchLexer.cs
- src/Microsoft.OData.Core/UriUtils.cs
- src/PlatformHelper.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ExpressionLexerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SearchLexerTests.cs
Use ExpressionLexer to do ReadOnlySpan investigation and seek feebacks to move forward to all other ODL parts.
1) the ReadOnlySpan<char> doesn't override the operator == and != for string. Remember to use 'Equals(...)' to replace them.
```C#
ReadOnlySpan<char> s1 = "nav/$ref".AsSpan().Slice(4,4);
Console.WriteLine(s1.ToString());
Console.WriteLine(s1 == "$ref");
Console.WriteLine(s1 != "$ref");
Console.WriteLine(s1.Equals("$ref", StringComparison.Ordinal));
```
It outputs
```cmd
$ref
False
True
True
```
2) Anytime to call 'ToString()' on ReadOnlySpan<char> will do the 'new string(...)', so be noted, not to call it multiple times until you need the string and remember to cache it.
See the allocated, using 'ReadOnlySpan<char>' is 1/3 memory allocation comparing to the 'new string(...)'. …
> Use ReadOnlySpan<char> to replace the 'new string(...)' to reduce memory allocation

- src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs
- src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
- test/FunctionalTests/Microsoft.OData.Client.Tests/Metadata/ClientTypeUtilTests.cs
I found an issue where the Conventional Id fields are not recognized as key fields.  As the Property Name Ends with Id, rather than "ID".  The result is that the EdmModel is properly defining the key property, however on the client the EntityType is resolved as "ComplexType" and failures in tracking occur later on in the pipeline.
https://github.com/OData/odata.net/issues/3052
This change finds Id properties using Case Insensitivity for cases where the [Key()] attribute is not defined.
> Update ODataTypeInfo.cs not correctly identifying entity keys by "Id" property

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.Stream.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.TextWriter.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
*This pull request fixes #3099 .*
This PR is for v7.x. I will create an 8.x port once this is merged.
This PR removes the "Flush()" call from the `FlushIfBufferThresholdReached` method and renames the method to `DrainBufferIfThresholdReached`. This method no longer forces a flush of the underlying stream, instead it only writes to the stream but leaves the stream to decide whether/when to flush. The user can still force a flush by explicitly calling the `Flush()` method.
> Write stream instead of flush (for v7.x)

- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.Stream.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.TextWriter.cs
- src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
This pull request fixes #3099  .
This PR is an 8.x port of the following 7.x PR: https://github.com/OData/odata.net/pull/3101
This PR removes the "Flush()" call from the `FlushIfBufferThresholdReached` method and renames the method to `DrainBufferIfThresholdReached`. This method no longer forces a flush of the underlying stream, instead it only writes to the stream but leaves the stream to decide whether/when to flush. The user can still force a flush by explicitly calling the `Flush()` method.
> Do not force flush when ODataUtf8JsonWriter buffer threshold is reached

- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/CollectionOpenPropertyAccessNode.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/SingleValueOpenPropertyAccessNode.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/EndPathBinderTests.cs
*This pull request fixes #3090.*
Allows open property access nodes to be created with a type when the type can be inferred from the context.
Supports creating an In expression with a CollectionOpenPropertyAccessNode as the right-hand operand, using the type of the left-hand operand
None
> Improve handling of dynamic properties in expressions

- src/Microsoft.OData.Edm/Csdl/CsdlReader.cs
- src/Microsoft.OData.Edm/Csdl/Parsing/Common/XmlDocumentParser.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
*This pull request fixes #3105 .*
As mentioned in the linked issue, the `CsdlReader` does not report correct line numbers when reading CSDL XML documents with element tags with attributes spanning multiple lines.
Take the following excerpt of a schema (`Edmx` and `DataServices` omitted for brevity). Assuming the snippet starts at Line 1, the `description` property should be line 7. However, if you parse the document using `CsdlReader` and check the `CsdlLocation` of the corresponding `IEdmProperty` element, it will report the line number 4. This is the bug that this PR fixes.
```xml
<Schema Namespace="ns.example" />
<ComplexType Name="item" />
<Property
Name="name"
Type="Edm.String'
/>
<Property Name="description" Type="Edm.String" />
</ComplexType>
</Schema>
```
This `CsdlReader` uses an …
> Report line numbers correctly for multi-line elements

- src/Microsoft.OData.Edm/Csdl/CsdlReader.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
*This pull request fixes #3105*
This is a follow up to the PR #3115. I found another case where we're using `ReadOuterXml` when parsing the `edmx:Reference` element, which means we'll get incorrect line number reporting for its children if there are new lines in between the attributes.
I've applied a fix similar to PR #3115
> Fix line number reporting when parsing csdl with multiline reference element

- src/Microsoft.OData.Core/HttpHeaderValueLexer.cs
- src/Microsoft.OData.Core/HttpUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataConventionalEntityMetadataBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/HttpUtilsTests.cs
Add the test cases for HttpUtils
*This pull request fixes #3094.*
* This PR focuses on HttpHeaderValueLexer, try to replace 'substring' using ReadOnlyMemory<char> to save the memory allocatioin.
* Add test cases for httpUtils
> Fixes #3094: continue to replace substring in HttpHeaderValueLexer

- src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsNavigationProperty.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.BigCsdl.cs
- test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
Fixes #3114: Fix the StackOverflow exception when retrieve Partner on navigation property from big CSDL model
Example.Database.Use has lots of navigation properties.When retrieving the partner on any navigation property, it recursively calls 'ComputePartner' again and again, finially, it throws StackOverflow Exception.
The PR is to cache the Partners for navigation properties when using. And use the cache to build the partner when retrieving the parter.
> Fixes #3114: Fix the StackOverflow exception when retrieve Partner on navigation property from big CSDL model

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/MetadataBinder.cs
- src/Microsoft.OData.Core/UriParser/Binders/MetadataBindingUtils.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/UriBuilderTestBase.cs
… 
*This pull request fixes #3120.*
* Should throw exception if the non-defined enum member used in 'in' operator.
* Make sure it's the same behavior comparing to the binary operator.
> Fixes #3120: Throws exception if non defined enum member used in `in` operator

- src/Microsoft.OData.Client/ConventionalODataEntityMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataConventionalEntityMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataConventionalIdMetadataBuilder.cs
- src/Microsoft.OData.Core/Evaluation/ODataMetadataContext.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriter.cs
- src/Microsoft.OData.Core/ODataContextUriBuilder.cs
- src/Microsoft.OData.Core/ODataContextUrlInfo.cs
- src/Microsoft.OData.Core/ODataResourceTypeContext.cs
- src/Microsoft.OData.Core/ODataWriterCore.cs
- src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/Json/ODataJsonWriterIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/Json/ODataJsonWriterShortSpanIntegrationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonResourceSerializerTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataContextUriBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataNavigationLinkTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataOperationTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataReaderDerivedTypeConstraintTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataResourceTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataResourceTypeContextTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ODataStreamReferenceValueTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/Json/ODataJsonInheritComplexCollectionWriterTests.cs
Enables writing responses without specifying an entityset.
UnknownEntitySet is treated as containment -- path becomes path through parent
Id of entities in unknown entity set is path if known, otherwise null
ContextUrl is path, if known, otherwise type
-Might be able to get rid of ThrowIfMissingTypeInfo (or validate that it relates only to type info, not entity set info)
> Don't require entityset when writing responses

- src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
- src/Microsoft.Spatial/Microsoft.Spatial.csproj
This PR update `csproj` files by adding `README.md` as the package readme file. This is to ensure README.md is package when generating NuGet package.
https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/ 
https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile
1. `<PackageReadmeFile>README.md</PackageReadmeFile>`:
- This line specifies that the README.md file should be included as the readme file in the NuGet package. When someone views your package on NuGet.org, this README file will be displayed.
2. `<None Include="README.md" Pack="true" PackagePath="\"/>`:
- This line includes the README.md file in the package. The `Include` attribute specifies the file to include.
- The `Pack="true"` attribute ensures that …
> Add README to NuGet package

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/ClientTests/Tests/ClientQueryTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes [#3092 ](https://github.com/OData/odata.net/issues/3092)*
This PR addresses an issue where the OData URI parser throws an `ArgumentNullException` when encountering a list with empty string in `square brackets`.
For example, the following query will throw an ArgumentNullException:
- `/People?$filter=Name in ['']`
- `/People?$filter=Name in [ ' ' ]`
- `/People?$filter=Name in [ \"\", ' ' ]`
- `/People?$filter=Name in [ \"\", '' ]`
- `/People?$filter=Name in [\"\"]`
- `/People?$filter=Name in [ \"\", \" \" ]`
- `/People?$filter=Name in [ \"\" ]`
- `/People?$filter=Name in [  '' , ' ' ]`
```
System.InvalidOperationException : An error occurred while processing this request.
---- Microsoft.OData.Client.DataServiceTransportException : System.ArgumentNullException: Value …
```
> Fix ArgumentNullException for: $filter=property in ['']

- test/FunctionalTests/Microsoft.OData.Core.Tests/AssertExtensions.cs
- test/FunctionalTests/Microsoft.OData.Core.Tests/Query/ODataUriUtilsTests.cs
Fixes #534: Add test cases to verify the Error messages for DataTimeOffset validation
> Fixes #534: Add test cases to verify the Error messages for DataTimeOffset validation

- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CancellationTokenTests/Server/CancellationTokenTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CancellationTokenTests/Tests/CancellationTokenTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/QueryCountTests/Server/QueryCountTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/QueryCountTests/Tests/QueryCountTests.cs
Port `Batch Request Tests` from [`WCF`](https://learn.microsoft.com/en-us/dotnet/framework/wcf/whats-wcf) to use `AspNetCoreOData`
- [test/EndToEndTests/Tests/Client/Build.Desktop/QueryCountTests](https://github.com/OData/odata.net/blob/main/test/EndToEndTests/Tests/Client/Build.Desktop/QueryCountTests.cs)
- [test/EndToEndTests/Tests/Client/Build.Desktop/CancellationTokenTests](https://github.com/OData/odata.net/blob/main/test/EndToEndTests/Tests/Client/Build.Desktop/CancellationTokenTests.cs)
> Port QueryCount and CancellationToken tests

- src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec
- src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec
- src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
- tools/CustomMSBuild/Versioning.props
*This pull request fixes https://github.com/OData/odata.net/issues/2390, fixes https://github.com/OData/odata.net/issues/1971.*
Currently, the changelog URL on the NuGet package release notes returns a 404:
This pull requests updates the URL to the correct location:
It also supplements the obsolete message for `KeyComparisonGeneratesFilterQuery` flag.
> Update nuget release notes changelog URL

- src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
- src/Microsoft.OData.Client/Serialization/HttpClientRequestMessage.cs
- src/Microsoft.OData.Client/ShippingAssemblyAttributes.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Microsoft.OData.Client.E2E.Tests.csproj
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/TransportLayerTests/HttpClientTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/TransportLayerTests/RequestMessageArgsTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/TransportLayerTests/Server/HttpClientController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/TransportLayerTests/Server/RequestMessageArgsTestsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/TransportLayerTests/Server/TransportLayerErrorController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/TransportLayerTests/TransportLayerErrorTests.cs
This Pr ports these tests: (https://github.com/OData/odata.net/tree/main/test/EndToEndTests/Tests/Client/Build.Desktop/TransportLayerTests)from using WCF services to using Microsoft.AspNetCore.OData services.
> Port transport layer tests

- src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes #3098, fixes #2875 *
This PR (https://github.com/OData/odata.net/pull/2711) introduced a fix to support `$filter=dynamicProperty in ('')`. However, the changes in this PR inadvertently broke the handling of `$filter=dynamicProperty in (primitive collections)`, such as `$filter=dynamicProperty in (1,2,3)`.
To address this, I've added a private method, `IsCollectionContentEmptyOrSpaces`, which checks whether a collection of `Edm.Untyped` is either empty or contains only spaces before further processing. If the collection meets this condition, the logic for ensuring a string collection gets properly formatted gets called. 
Previously, this string formatting logic was executed without verifying whether the `Edm.Untyped` collection contained empty spaces or not. As a …
> Fix $filter in (collectionofdynamicprimitivevalues)

- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/net9.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/SRResources.Designer.cs
- src/Microsoft.OData.Core/SRResources.resx
- src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs
- src/Microsoft.OData.Core/UriParser/Parsers/SelectExpandTermParser.cs
- src/Microsoft.OData.Core/UriParser/SemanticAst/PathCountSelectItem.cs
- src/Microsoft.OData.Core/UriParser/Visitors/SelectItemHandler.cs
- src/Microsoft.OData.Core/UriParser/Visitors/SelectItemTranslator.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
Fixes #3174: Enable $select=colProperty/$count query option parser
See details in #3174 
See related OASIS tc issues at: [Should ABNF support /$count in $Select · Issue #2046 · oasis-tcs/odata-specs](https://github.com/oasis-tcs/odata-specs/issues/2046)
> Fixes #3174: Enable $select=colProperty/$count query option parser

- .github/ISSUE_TEMPLATE/config.yml
Because the repo already contains a SECURITY.md file, the item for "Report a security vulnerability" is added automatically hence there's no need for "Security Issue Reporting".
In addition, due to previously having full path to the bug and feature request templates, the two items didn't appear. Fixing that in this pull request
> Reconfigure issue templates

- src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
This pull request fixes [issue](https://github.com/OData/odata.net/issues/3165) where the problem was that during the parsing of average aggregation function the parser could throw an exception saying that it does not support int16. (Or Byte and SByte for that matter)
Easy fix that required just adding few cases into a switch.
None
> Fixes #3165: UriParser - Aggregation method Average doesn't support Int16

- src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Binders/FunctionCallBinderTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
… 
*This pull request fixes #3224.*
> Fixes #3224: FunctionCallBinder returning SingleValueFunctionCallNode for complex types

- .github/PULL_REQUEST_TEMPLATE.md
- azure-pipelines-rolling.yml
For security reasons, the CI build does not run automatically for PRs within this repository. The build can be triggered by a team member commenting `/AzurePipelines run` on the PR. I have added these instructions to the PR template so that we can remind ourselves of this mechanism. I have also updated the YAML to not "auto cancel", which, described [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#multiple-pr-updates) current cancels running builds whenever a new commit is pushed to the PR. 
The intent is to make CI builds easier to run and not interfere with the general workflow of the individual developer.
> updating build pipeline and PR template to reflect CI build instructions

- src/Microsoft.OData.Core/Json/ODataJsonResourceDeserializer.cs
- src/Microsoft.OData.Core/Json/ODataJsonResourceSerializer.cs
- src/Microsoft.OData.Core/Json/ODataJsonWriter.cs
- src/Microsoft.OData.Core/ODataNestedResourceInfo.cs
- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonEntryAndFeedSerializerTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonResourceSerializerTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/Json/FullPayloadValidateTests.cs
Fixes #3154: Enable serialize/deserialize navigation property with count without content
> Fixes #3154: Enable serialize/deserialize navigation property with count without content

- src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertyAndValueDeserializer.cs
*This pull request addresses #3264 in ODL 7.x*
If this PR is approved, I'll port the fix to ODL 8.x
To fix the performance issue caused by excessively running property verification each time the reader adds a property to the resource being deserialized, I update the `resource.Properties` in-place in `ODataJsonLightPropertyAndValueDeserializer.AddResourceProperty()` without invoking the setter each time since the verification logic runs in the setter.
In lieu of running the verification logic, I use `Debug.Assert` statements to perform the equivalent verification during debug builds only, to avoid any runtime impact from the verification. I could have implemented the verification using logic that's executed also in prod builds that would also thrown an exception, this would still improve …
> Avoid excessive property verifications when adding resource properties in OData reader

- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/ODataUrlValidator.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriTemplateParserTests.cs
*This pull request fixes #3275*
Handles a null segment type when checking for properties of a structural type during validation.
None.
> Handle null segment type in Validation

- src/Microsoft.OData.Core/Json/ODataJsonDeserializer.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonDeserializerTests.cs
This pull request fixes #2977. It is similar to PRs #1208 and #2132
SAP's OData V4 APIs will return context URI annotations like `"@odata.context": "../$metadata#Customers(1)/Name"` and `"@odata.context": "../../$metadata#Customers(1)/Name"` for certain requests. These are currently unsupported and result in an exception.
The code changes in this PR cover these scenarios.
`build.cmd` did not work for me... I think I'm missing some build tools, or maybe it's because I don't have VS 2019 Enterprise. However, all tests that I ran in the test explorer passed (21,066 passed, 8 were skipped).
> #2977 Support more kinds of relative context URIs

- src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Binders/FunctionCallBinderTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs
Cherry-pick: 00d4c772d048573d6b3b9ffd85836e217979a4e5
> Cherry-pick: (PR 3234) FunctionCallBinder returning SingleValueFunctionCallNode for complex types

- src/Microsoft.OData.Client/Serialization/ODataPropertyConverter.cs
- src/Microsoft.OData.Core/Json/ODataJsonReader.cs
- src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/PublicAPI/net9.0/PublicAPI.Unshipped.txt
- src/Microsoft.OData.Core/Uri/ODataUriUtils.cs
- src/Microsoft.OData.Core/UriParser/ExpressionLexerLiteralExtensions.cs
- src/Microsoft.OData.Core/Value/ODataNullValue.cs
- src/Microsoft.OData.Core/Value/ODataValueUtils.cs
- test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Helpers/ODataValueAssertEqualHelper.cs
- test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/SingletonTests/Tests/SingletonODataValueAssertEqualHelper.cs
- test/UnitTests/Microsoft.OData.Core.Tests/IntegrationTests/Writer/Json/ODataJsonWriterShortSpanIntegrationTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/JsonInstanceAnnotationWriterAsyncTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/JsonInstanceAnnotationWriterTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonDeserializerTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonEntryAndFeedSerializerUndecalredTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsAsyncTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataJsonWriterUtilsTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ODataErrorTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ODataInstanceAnnotationTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ODataNullValueTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/Json/CustomInstanceAnnotationRoundtripJsonTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/TestUtils.cs
…s singleton instance
*This pull request fixes #3266.*
This change introduces a singleton pattern for the `ODataNullValue` object to optimize its allocations. By implementing a single, shared instance of `ODataNullValue`, we can reduce the number of unnecessary object creations and improve overall performance.
The change involves:
- creating a singleton instance of `ODataNullValue`
```cs
public static readonly ODataNullValue Instance = new ODataNullValue();
```
- replacing all instances of `new ODataNullValue()` with `ODataNullValue.Instance`
This is meant to reduce memory allocations by reusing a single instance of `ODataNullValue` and hence, improve perfomance by minimizing GC overhead.
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details …
> Optimize ODataNullValue Allocations with Singleton Implementation

- src/Microsoft.OData.Client/BaseSaveResult.cs
- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/EntityTracker.cs
- src/Microsoft.OData.Client/ObjectMaterializerLog.cs
- test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/EndToEnd/CommonEndToEndDataSource.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Batch/AsyncMethodTests.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Batch/Server/Backend.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Batch/Server/BankAccountsController.cs
- test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/Batch/Server/BanksController.cs
Cherry-pick: 5fcdd1188009585c7d8c80afa1ad42637cfc4e69
> Cherry-pick: Track DependsOnIds when UseJsonBatch flag is applied to batch requests

- src/Microsoft.OData.Core/UriParser/Parsers/SegmentArgumentParser.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Cherry-pick: 089572d33aebaa686ca31a358f01d67ca85c1e20
> Cherry-pick: Support parameter aliases in key segments (#3278)

- src/Microsoft.OData.Core/UrlValidation/ValidationEngine/ODataUrlValidator.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriTemplateParserTests.cs
Handles a null segment type when checking for properties of a structural type during validation.
Cherry-pick: 46b2f7e747376881009e665f6222187e3f125e42
Team members should **not** trigger a build this way for pull requests coming from forked repositories. They should instead trigger the build manually by setting the "branch" to `refs/pull/{prId}/merge` where `{prId}` is the ID of …
> Cherry-pick: Handle null segment type in Validation

- src/Microsoft.OData.Client/DataServiceContext.cs
- src/Microsoft.OData.Client/ODataRequestMessageWrapper.cs
- src/Microsoft.OData.Client/PublicAPI/net10.0/PublicAPI.Shipped.txt
- src/Microsoft.OData.Client/RequestInfo.cs
- test/EndToEndTests/Tests/Edm/Microsoft.OData.Edm.E2E.Tests/FunctionalTests/ConstructibleModelTests.cs
- test/UnitTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextQueryTests.cs
*This pull request fixes #3182.*
Related to PR: https://github.com/OData/odata.net/pull/3135
In ODL 8, the `DataserviceContext.Timeout` property was marked as `Obsolete` and recommended using IHttpClientFactory to configure the timeout as outlined in [Configuring HttpClient with IHttpClientFactory in Microsoft.OData.Client](https://learn.microsoft.com/en-us/odata/client/using-dataservice-ihttpclientfactory)
This PR is to remove the DataserviceContext.Timeout property.
Team members can start a CI build by adding a comment with the text `/AzurePipelines run` to a PR. A bot may respond indicating that there is no pipeline associated with the …
> Remove Obsolete DataserviceContext.Timeout property

- azure-pipelines-nightly.yml
- azure-pipelines-rolling.yml
Troubleshoot nuget.org access failures. Network isolation changes applied to 1ES pipelines caused builds to start failing.
> Troubleshoot nuget.org access failures

- src/Microsoft.OData.Client/Microsoft.OData.Client.csproj
- src/Microsoft.OData.Core/Microsoft.OData.Core.csproj
- src/Microsoft.OData.Core/PublicAPI/net9.0/PublicAPI.Unshipped.txt
- test/UnitTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj
- test/UnitTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj
- test/UnitTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj
- test/UnitTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
This pull request removes the following pruned references to get rid of existing build warnings:
- System.Het.Http
- System.ValueTuple
- System.ComponentModel
- System.ComponentModel.Annotations
- System.Text.RegularExpressions
- System.Buffers
The pull request also updates 9.0 public API
> Remove pruned references

- src/Microsoft.OData.Edm/Schema/Interfaces/IEdmOperation.cs
*This pull request fixes #3085.*
In version **7.x**, [`IEdmOperationReturn`](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Schema/Interfaces/IEdmOperationReturn.cs) was introduced to represent return types without modifying [`IEdmOperation`](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Schema/Interfaces/IEdmOperation.cs), in order to avoid breaking changes.
Introduced by PR: https://github.com/OData/odata.net/pull/1414
Mark `IEdmOperation.ReturnType` as `[Obsolete]` and provide guidance to use the [`GetReturn()`](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs#L2722) extension method instead. This method returns an `IEdmOperationReturn` instance
Change `IEdmOperation` to expose …
> Deprecate IEdmOperation.ReturnType in v8.x; recommend using GetReturn() extension method

- src/Microsoft.OData.Client/DataServiceActionQuerySingleOfT.cs
- test/UnitTests/Microsoft.OData.Client.Tests/DataServiceActionQuerySingleTests.cs
*This pull request fixes #2727.*
This PR replaces `Single()` with `SingleOrDefault()` within the `GetValue` and `EndGetValue` methods of `DataServiceActionQuerySingleOfT` to improve runtime safety and prevent potential `InvalidOperationException` when no matching elements are found.
Team members should **not** trigger a build this way for pull requests coming from forked repositories. They should instead …
> Replace Single() with SingleOrDefault() in DataServiceActionQuerySingleOfT GetValue and EndGetValue Methods

- src/Microsoft.OData.Client/DataServiceClientException.cs
- src/Microsoft.OData.Client/DataServiceQueryException.cs
- src/Microsoft.OData.Client/DataServiceRequestException.cs
- src/Microsoft.OData.Client/DataServiceWebException.cs
- src/Microsoft.OData.Client/PublicAPI/net10.0/PublicAPI.Shipped.txt
*This pull request fixes #3181.*
The following kinds of APIs are obsolete, starting in .NET 8. Calling them in code generates warning [SYSLIB0051](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0051) at compile time.
All public or protected serialization constructors that follow the pattern .ctor(SerializationInfo, StreamingContext). An example of such a constructor is [Exception(SerializationInfo, StreamingContext)](https://learn.microsoft.com/en-us/dotnet/api/system.exception.-ctor#system-exception-ctor(system-runtime-serialization-serializationinfo-system-runtime-serialization-streamingcontext)).
All implicit implementations of the [ISerializable.GetObjectData(SerializationInfo, StreamingContext)](https://learn.microsoft.com/en-us/dotnet/api/system.runtim …
> Address obsoletion warning

- src/Microsoft.OData.Core/SRResources.Designer.cs
- src/Microsoft.OData.Core/SRResources.resx
- src/Microsoft.OData.Core/UriParser/Parsers/UriPathParser.cs
- src/Microsoft.OData.Core/UriUtils.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ODataUtilsTests.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriPathParserTests.cs
Cherry-pick https://github.com/OData/odata.net/pull/3340 into dev-9.x branch
> Treat unencoded `/` inside quoted literals as data (not separators) (#3340)

- src/Microsoft.OData.Core/UriUtils.cs
*This pull request fixes `UriInvariantInsensitiveIsBaseOf_DoubleSlashesTreatedLiterally` test.* The recent refactor of `UriPathParser.ParsePathIntoSegments` together with it's helper methods in `UriUtils` broke the test.
The test `UriInvariantInsensitiveIsBaseOf_DoubleSlashesTreatedLiterally` verifies that the base‑of logic treats consecutive slashes in the path as significant (i.e. it does NOT collapse “//” to “/”). Concretely:
- Base URI:  http://x//odata (path segments: ["", "odata"])
- Candidate1: http://x//odata/Products (segments: ["", "odata", "Products"]) -> should match (True)
- Candidate2: http://x/odata/Products  (segments: ["odata", "Products"]) -> should NOT match (False)
So it asserts:
1. Empty path segments created by a double slash are preserved.
2. Segment comparison is …
> UriUtils.UriInvariantInsensitiveIsBaseOf should be preserve double slashes in base URI - RFC 3986

- src/Microsoft.OData.Core/UriUtils.cs
- test/UnitTests/Microsoft.OData.Core.Tests/ODataUtilsTests.cs
Cherry-pick: UriUtils.UriInvariantInsensitiveIsBaseOf should be preserve double slashes in base URI - RFC 3986
> Cherry-pick: UriUtils.UriInvariantInsensitiveIsBaseOf should be preserve double slashes in base URI - RFC 3986

- src/Microsoft.OData.Core/UriParser/ODataUriParser.cs
- test/UnitTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
*This pull request fixes #3357.*
> Fixes #3357: Regression when parsing query option with no =
