README.md
Addresses https://github.com/OData/odata.net/issues/159
=> Updated README.md to explain SQLExpress requirement for Full and E2E testing

src/Microsoft.OData.Client/DataServiceContext.cs, src/Microsoft.OData.Client/Materialization/CollectionValueMaterializationPolicy.cs, src/Microsoft.OData.Client/Materialization/ComplexValueMaterializationPolicy.cs, src/Microsoft.OData.Client/Materialization/EntryValueMaterializationPolicy.cs, src/Microsoft.OData.Client/Materialization/ODataEntityMaterializer.cs, src/Microsoft.OData.Client/Materialization/StructuralValueMaterializationPolicy.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl, test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/Annotation/ClientAnnotationTests.cs
Allow user to disable instance annotation materialization on client side.
=> Support to disable instance annotation materialization

_posts/release notes/2015-06-19-ODL-6.13.0.md
Add pull request contributors.
=> Add contributors to 6.13 release notes

.gitignore
Ignore files under folder: sln/.vs/
=> Ignore sln/.vs/ #386

test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/DumpPublicApi.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
Resolve https://github.com/OData/odata.net/issues/402, and update public api baseline.
=> Trim CompilerGeneratedAttribute from PublicApi.bsl

test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/PipelineEventsTests/PipelineEventsCrossPlatformAsyncTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/PipelineEventsTests/PipelineEventsTests.cs
=> QueryEntityInstance etc. test cases work in VS2015

build.ps1, test/EndToEndTests/Services/Astoria/Microsoft.Test.OData.Services.Astoria.csproj, test/EndToEndTests/Tests/Client/Build.Desktop/App.config, test/FunctionalTests/Framework/AstoriaTestFramework.csproj, test/FunctionalTests/Tests/DataServices/Models/EFFK/Astoria.EFFKModel.csproj, test/FunctionalTests/Tests/DataServices/ddbasics/Microsoft.Test.Data.Services.DDBasics.csproj
App.config is default to .\SqlExpress DB.
=> Move VS version check after Build.props

src/Microsoft.OData.Core/UriParser/Parsers/KeyFinder.cs, src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs, src/Microsoft.OData.Core/UriParser/Parsers/SegmentArgumentParser.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/SegmentKeyHandlerTests.cs
This PR is for fixing issue #441
=> Fix key parse logic for composite key

src/Microsoft.OData.Client/Metadata/ClientPropertyAnnotation.cs
=> Allow query to set value on the readonly property (set method is not public)

src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj, src/Microsoft.OData.Core/Microsoft.OData.Core.Net45.csproj, src/Microsoft.OData.Core/Microsoft.OData.Core.Portable45.csproj, src/Microsoft.OData.Core/Microsoft.OData.Core.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Core/Microsoft.OData.Core.txt, src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs, src/Microsoft.OData.Core/UriBuilder/NodeToStringBuilder.cs, src/Microsoft.OData.Core/UriParser/Binders/EndPathBinder.cs, src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/CollectionCountNode.cs, src/Microsoft.OData.Core/UriParser/TreeNodeKinds/QueryNodeKind.cs, src/Microsoft.OData.Core/UriParser/Visitors/QueryNodeVisitor.cs, test/EndToEndTests/Services/ODataWCFLibrary/NodeToExpressionTranslator.cs, test/EndToEndTests/Tests/Client/Build.Desktop/Microsoft.Test.OData.Tests.Client.csproj, test/EndToEndTests/Tests/Client/Build.Desktop/QueryOptionTests/FilterQueryTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/NodeAssertions.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
=> Fix complex collection type cast

_posts/client/2014-12-24-04-02-query-options.md
Update document for new features added
=> Add document for new features supported by OData .Net Client

src/Microsoft.OData.Core/UriParser/Visitors/SelectPropertyVisitor.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs
Make complex collection with type cast can be selected.
Part fix issue #457
=> Add support of complex collection cast in select

v6/_posts/release notes/2017-02-06-ODL-5.8.2.md
Release notes for ODataLib 5.8.2
=> Add relnotes for 5.8.2 ODL.

src/Microsoft.OData.Core/ODataContextUrlInfo.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs
*This pull request fixes WebAPI issue #917 (https://github.com/OData/WebApi/issues/917)*  
*ContextUrl for containment relationships were not being serialized as expected.*
- [ x ] Test cases added (in WebAPI E2E)
*None needed.*
=> Fixes for invalid ContextUrls

src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs
*This pull request fixes issue #xxx.*  
=> Fix trailing whitespace on empty line

src/Microsoft.OData.Core/Metadata/ODataMetadataReaderUtils.cs, src/Microsoft.OData.Edm/Csdl/CsdlReader.cs, src/Microsoft.OData.Edm/Csdl/Parsing/Common/EdmXmlDocumentParser.cs, src/Microsoft.OData.Edm/Validation/ValidationHelper.cs, src/Microsoft.OData.Edm/Vocabularies/AlternateKeysVocabularyModel.cs, src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularyModel.cs, src/Microsoft.OData.Edm/Vocabularies/CoreVocabularyModel.cs
Fix suppression for CA3053 to reference proper category and checkid.
=> Fix suppression for CA3053 to reference proper category and checkid. 

v7/_posts/release notes/2017-03-31-ODL-7.1.0.md
N/A
Release notes for ODL 7.1.0 release.
N/A
N/A
=> ODL 7.1.0 Release Notes

src/Microsoft.OData.Core/ODataCollectionReaderCore.cs, src/Microsoft.OData.Core/ODataCollectionStart.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/MessageToObjectModelReader.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/ReaderTestConfiguration.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/ReaderTestConfigurationProvider.cs
*Update test coverage for ODataCollectionReader.*  
*Improve coverage by adding test case and remove dead code.*
=> Update test coverage for ODataCollectionReader.

test/FunctionalTests/Microsoft.OData.Core.Tests/Evaluation/ODataEntryMetadataContextTest.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/InstanceAnnotationsReaderIntegrationTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/ODataJsonLightReaderIntegrationTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Reader/JsonLight/UriParameterReaderIntegrationTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterWriterTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightServiceDocumentDeserializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataUtilsInternalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Roundtrip/ContextUrlWriterReaderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/EntityReferenceFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FullUriFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SelectExpandFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/SemanticTreeFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/FullPayloadValidateTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/SelectPathSegmentTokenBinderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/CaseInsensitiveResolverTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/ExpandOptionParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriPathParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriPrimitiveTypeParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathExtensionsTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/ValidationRulesTests.cs
Skipped tests have been resolved by:
1.) Unskipping the test
2.) Modifying the test to match current product behavior
3.) Commenting out the test where matching product work is not complete, add the matching GitHiub issue
4.) Removing the test
=> Cleanup skipped tests in Microsoft.OData.Core.Tests.

src/Microsoft.OData.Client/Build.NetStandard/Microsoft.OData.Client.NetStandard.csproj, src/Microsoft.OData.Client/Build.Portable/Microsoft.OData.Client.Portable.csproj, src/Microsoft.OData.Client/Microsoft.OData.Client.csproj, src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj, src/Microsoft.OData.Core/Build.NetStandard/Microsoft.OData.Core.NetStandard.csproj, src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Core/Uri/ExpressionConstants.cs, src/Microsoft.OData.Core/UriParser/Binders/ComputeBinder.cs, src/Microsoft.OData.Core/UriParser/Binders/ExpandTreeNormalizer.cs, src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs, src/Microsoft.OData.Core/UriParser/ODataQueryOptionParser.cs, src/Microsoft.OData.Core/UriParser/ODataUriParser.cs, src/Microsoft.OData.Core/UriParser/Parsers/ExpandOptionParser.cs, src/Microsoft.OData.Core/UriParser/Parsers/UriQueryExpressionParser.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ComputeClause.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ComputeExpression.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ExpandedNavigationSelectItem.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ExpandedReferenceSelectItem.cs, src/Microsoft.OData.Core/UriParser/SyntacticAst/ComputeExpressionToken.cs, src/Microsoft.OData.Core/UriParser/SyntacticAst/ComputeToken.cs, src/Microsoft.OData.Core/UriParser/SyntacticAst/ExpandTermToken.cs, src/Microsoft.OData.Core/UriParser/SyntacticAst/QueryTokenKind.cs, src/Microsoft.OData.Core/UriParser/UriQueryConstants.cs, src/Microsoft.OData.Core/UriParser/Visitors/SyntacticTreeVisitor.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataQueryOptionParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriQueryExpressionParserTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Visitors/SyntacticTreeVisitorTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
This pull request fixes issue #799 .
Adding support to ODL parser for the $compute query option.
=> Implementation of $compute

src/Microsoft.OData.Core/UriParser/SyntacticAst/ExpandTermToken.cs
This pull request fixes issue #827 .
Fix style cop warning in previous check-in.
No docs needed.
=> Fixing Build Cop warning

src/Microsoft.OData.Core/UriParser/Binders/DottedIdentifierBinder.cs
This is correcting an FxCop not caught during buddy build or local build.
=> Fix FxCop issue in build

src/Microsoft.OData.Client/DataServiceContext.cs, src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs, src/Microsoft.OData.Edm/GlobalSuppressions.cs, src/Microsoft.OData.Edm/Validation/ValidationRules.cs, src/Microsoft.Spatial/GeoJsonWriterBase.cs, src/Microsoft.Spatial/WellKnownTextSqlReader.cs
*This pull request is for cleaning up CA13xx (Globalization) warning category.*
*Examine and remove the CA13xx warning if it doesn't make sense.*
=> CA13xx(Globalization) warning message cleanup for Odata.net

build.ps1, sln/.nuget/packages.config, test/EndToEndTests/Services/Astoria/Microsoft.Test.OData.Services.Astoria.csproj, test/EndToEndTests/Services/CSDSCReferences/Microsoft.Test.OData.Services.CSDSCReferences.csproj, test/EndToEndTests/Services/TestServices/Microsoft.Test.OData.Services.TestServices.csproj, test/EndToEndTests/Tests/Client/Build.Desktop/CodeGenerationTests/T4CodeGenerationTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/Microsoft.Test.OData.Tests.Client.csproj, test/EndToEndTests/Tests/Client/Build.Desktop/ODataWCFServiceTestsBase.cs, test/EndToEndTests/Tests/Client/EndToEndTestBase.cs, test/FunctionalTests/Tests/DataServices/UnitTests/ServerUnitTests/Stubs/DataServiceProvider/DSPUnitTestServiceDefinition.cs
Standardize on EntityFramework 4.3.1 for tests to reduce race conditions
for EntityFramework dependent tests.
=> Standardize on EntityFramework 4.3.1 for tests to reduce race conditions

README.md
*This pull request enables build badge for latest build status of ODL on master branch.*
*Adds the build badge for master branch  build of ODL on visualstudio.com.*
=> Add build badge to show latest build status of odata.net/master.

README.md
*This pull request adds build badge for maintenance-6.x branch.*
*Add build badge url from Rolling build of maintenance-6.x branch.*
=> Add build badge for build status odata.net/maintenance-6.x branch

README.md
*This pull request adds nightly build badge for ODL master branch.*
*Add nightly build badge from VSTS nightly build.*
=> Add nightly build badge

PerformanceBuild.ps1
We change the performance solution file name. It also need to change the performance script
change the performance script to let the local performance running
=> Change the performance script to make local build, PR #915

README.md
Update nightly feed details in Readme.md.
=> Update nightly feed details.

test/Common/Microsoft.Test.OData.DependencyInjection/Build.NetFramework/Microsoft.Test.OData.DependencyInjection.csproj, test/EndToEndTests/Services/ODataWCFLibrary/ODataSamples.Services.Core.csproj, test/PerformanceTests/ComponentTests/Microsoft.OData.Performance.ComponentTests.csproj, test/PerformanceTests/Framework/PerfServiceCore/Microsoft.Test.OData.Services.PerfService.csproj, test/PerformanceTests/ServiceTests/Microsoft.OData.Performance.ServiceTests.csproj
Change the performance official package reference.
7.3 has changed the version number. for example: 7.3.0.10724. 
It can't work with the previous script. So, have to change.
- [  ] Build and test with one-click build and test script passed
=> Change the performance official project reference

tools/perf/PerfRegression.ps1
Add a performance running scripts
Add a performance running scripts
- [  ] Build and test with one-click build and test script passed
=> Add a performance running scripts

tools/ExecutePerf.ps1
It will improve frequently.
add a script to run the performance on VSTS
add a script to run the performance on VSTS
- [  ] Build and test with one-click build and test script passed
=> add a script to run the performance on VSTS

test/FunctionalTests/Framework/Net/XmlHttpRequestSender.cs, test/FunctionalTests/Framework/Workspaces/EdmWorkspaces/EdmWorkspace.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Scenario.Tests/app.config
Remove passwords from source and test code.
=> Remove passwords from source and test code.

src/Microsoft.OData.Core/UriParser/Parsers/CustomUriLiteralParsers.cs
This pull request fixes a performance issue where a global lock was being taken inside of CustomUriLiteralParsers when parsing, causing a high degree of contention when multiple threads were trying to parse URIs at the same time.
Makes the parser collections immutable arrays and acquires the lock only when acquiring a reference to the current collection, or when replacing the collection.
No new test cases were added because the change does not impact functional correctness. Existing tests should have sufficient coverage.
Needs to be ported to the maintenance-6.x branch after commit to master.
=> Avoid parsing inside a lock in CustomUriLiteralParsers

src/CodeGen/VSIX/[Content_Types].xml, src/CodeGen/VSIX/ap-pl.txt, src/CodeGen/VSIX/extension.vsixmanifestCfg
Adding files that are part of the VSIX package.
N/A
=> Adding files that are part of the VSIX package.

src/Microsoft.OData.Core/Uri/ODataUri.cs, src/Microsoft.OData.Core/UriParser/ODataUriParser.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FullUriFunctionalTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
Adding $compute fix to release branch.
=> Add Compute to ParseUri.

tools/CustomMSBuild/Versioning.props
Update the version of the product to 7.3.1
=> Update Version for Release

v7/_posts/release notes/2017-08-14-ODL-7.3.1.md
Adding Release Notes for 7.3.1
=> Adding rel notes for 7.3.1

src/CodeGen/ODataT4CodeGenerator.tt
- Fixing some tab formatting
- Updating namespace template value to use # instead of $ to be consistent with other files
N/A
=> Update namespace for ODataT4CodeGenerator.tt

v7/_posts/odata features/2016-09-02-06-13-support-untyped-json.md, v7/_posts/odata features/2017-07-12-06-23-optional-parameters.md, v7/_posts/release notes/2017-07-12-ODL-7.3.0.md
*Added documentation and release notes for reading/writing untyped as structured values*
=> Add documentation for reading/writing Untyped as structured values

README.md
Update rolling build badge to use new build definition id.
=> Update rolling build badge to use new build definition id.

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, test/EndToEndTests/Services/ServiceWrapperApp/ServiceWrapperApp.cs
Issue #731
- Updating Nuget package for OData Client to remove NetFx45 binaries.
- Fixing bug in ServiceWrapperApp where exception is ignored.
N/A
=> Updating Nuget package for OData Client to remove NetFx45 binaries

src/Microsoft.OData.Core/Build.Net35/Microsoft.OData.Core.NetFX35.csproj, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.Net35/Microsoft.OData.Edm.NetFX35.csproj, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.Spatial/Build.Net35/Microsoft.Spatial.NetFX35.csproj, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec
Add V7 suffix to Net35 binaries.
- [ x ] *Build and test with one-click build and test script passed*
=> Add V7 suffix to Net35 binaries.

src/Microsoft.OData.Core/UriParser/Binders/MetadataBindingUtils.cs, src/Microsoft.OData.Core/UriParser/TypePromotionUtils.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/TypePromotionUtilsTests.cs
Support string to Enum conversion in filters
- [ X] *Test cases added*
No
=> Support enum to string comparision

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
*This pull request fixes issue of missing copyright information in nuspec.*
*Add Microsoft copyright information.*
=> Updating CopyRight info in nuspec files.

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
*This pull request fixes issue of missing copyright information in nuspec.*
*Add Microsoft copyright information.*
=> Updating CopyRight info in nuspec files

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
*This pull request fixes issue of missing copyright information in nuspec.*
*Add Microsoft copyright information.*
=> Copyright fixes for nuspec.

src/Microsoft.OData.Core/ODataObjectModelExtensions.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes WebAPI OData issue https://github.com/OData/WebApi/issues/1193.*
*In refactoring the code for Delta support we moved an extension method from a derived class to a new base class.  No code changes for newly compiled apps, but existing apps break because the resolver doesn't find the old signature (and doesn't resolve it to the new method on the base class).*
- [n/a ] *Test cases added*
- [ x ] *Build and test with one-click build and test script passed*
None.
=> Fix Issue 1193; add back extension function to derived class.

src/Microsoft.OData.Core/ODataObjectModelExtensions.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs, src/Microsoft.OData.Edm/Microsoft.OData.Edm.cs, src/Microsoft.OData.Edm/Microsoft.OData.Edm.txt, src/Microsoft.OData.Edm/Parameterized.Microsoft.OData.Edm.cs, src/Microsoft.OData.Edm/Validation/EdmErrorCode.cs, src/Microsoft.OData.Edm/Validation/ExpressionTypeChecker.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataContextUriBuilderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/ContextUrlPathStringTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/ScenarioTests/OasisRelationshipChangesAcceptanceTests.cs, test/FunctionalTests/Tests/DataEdmLib/FunctionalTests/VocabularyParsingTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl, tools/CustomMSBuild/Versioning.props
Merge master branch to release branch and update the version to beta3
=> Merge master branch to release branch and update the version to beta3

v7/_posts/release notes/2018-01-11-ODL-7.4.0.md
=> Add 7.4.0 release notes.

tools/CustomMSBuild/Versioning.props
N/A
Update version number to 7.4.1.
N/A
=> Update version number to 7.4.1

src/Microsoft.OData.Core/UriParser/Visitors/PathSegmentHandler.cs, src/Microsoft.OData.Core/UriParser/Visitors/SplitEndingSegmentOfTypeHandler.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
Add support for AnnotationSegment to PathSegmentHandler
=> Add support for AnnotationSegment to PathSegmentHandler.

test/PackageTests/Microsoft.OData.Tests.Nuget.Edm/Schema.xml
Fix Policheck issue for package tests.
=> Fix Policheck issue for package tests.

v6/_posts/core libraries/2015-04-12-03-02-create-spatial-instances.md, v7/_posts/core libraries/2015-04-12-03-02-create-spatial-instances.md
This pull request fixes issue #1090 
Fix links in spatial documentation.
=> Fix links in spatial documentation.

src/Microsoft.OData.Edm/Vocabularies/AuthorizationVocabularies.xml
No.
*A small xml error in Authorization vocabulary xml. 
=> Fix the authorization xml error

src/CodeGen/ODataT4CodeGenerator.cs
*This pull request fixes poli check issue introduced ~1 week ago .*
*Updated the rogue string.*
=> Fixed rogue string detected by PoliCheck.

tools/CustomMSBuild/Versioning.props
=> Update version for 7.4.3

src/Microsoft.OData.Core/JsonLight/JsonFullMetadataTypeNameOracle.cs, src/Microsoft.OData.Core/JsonLight/JsonLightTypeNameOracle.cs, src/Microsoft.OData.Core/JsonLight/JsonMinimalMetadataTypeNameOracle.cs, src/Microsoft.OData.Core/JsonLight/JsonNoMetadataTypeNameOracle.cs, src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceSerializer.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/JsonFullMetadataTypeNameOracleTests.cs
Merge writing type annotations on collections in full metadata to release.
=> Enable writing type annotation for collections in full metadata (#1087)

v7/_posts/release notes/2018-03-21-ODL-7.4.3.md
Added release notes for 7.4.3.
=> Added release notes for 7.4.3.

v7/_posts/release notes/2018-03-30-ODL-7.4.4.md
Added release notes for ODL 7.4.4.
=> Add 7.4.4 release notes.

src/Microsoft.OData.Core/PropertyCacheHandler.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/PropertyCacheHandlerTests.cs
*This pull request fixes issue #1172.*
*Fixed assertion failure in Debug build.*
- [] *Test cases added*
=> Fix Debug.Assert error in PropertyCacheHandler

test/PackageTests/Microsoft.OData.Tests.Nuget.Core/CoreLibTest.cs
*This pull request fixes ODL nightly build failures in the past couple weeks.*
*Update the trippin reference service url to use the https endpoint to get correct response.*
=> Update trippin service url to use https endpoint.

src/Microsoft.OData.Core/ODataConstants.cs, src/Microsoft.OData.Core/ODataMessageQuotas.cs
Fix typo with default batch size
=> Fix typo with default batch size

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
* Modify Nuget spec file to meet the new compliance validation check
1 | The author must be just   “Microsoft” without quotes. | <authors>Microsoft</authors>
-- | -- | --
2 | The copyright must be “©   Microsoft Corporation. All rights reserved.” without quotes. | <copyright>©   Microsoft Corporation. All rights reserved.</copyright>
3 | projectUrl must not be null | <projectUrl>This   must be a valid team or product URL. This must be a permalink that will never   be deprecated. It can be an FWLink.</projectUrl>
4 | licenseUrl must not be null. | <licenseUrl>This   must be a valid product license URL. While FWLinks are not prohibited, customers   prefer for these URLs to be transparent rather than being FWLinks.   </licenseUrl>
5 | the …
=> Modify Nuget spec file to meet the new compliance validation check

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Core/ODataConstants.cs, src/Microsoft.OData.Core/ODataMessageQuotas.cs, src/Microsoft.OData.Core/ODataParameterReaderCore.cs, src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.OData.Edm/Schema/Interfaces/IEdmOptionalParameter.cs, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightParameterReaderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/UriQueryExpressionParserTests.cs, test/PackageTests/Microsoft.OData.Tests.Nuget.Core/CoreLibTest.cs, tools/CustomMSBuild/Versioning.props
* This pull request is for preparation of ODL v7.5.1 release.
* Cherry-pick the changes in master to release branch.
=> Release 7.5.1

v6/_posts/release notes/2018-09-11-ODL-5.8.4.md
*This pull request is for release note Microsoft.Data.OData v5.8.4.*
*Add the release note for [Microsoft.Data.OData v5.8.4](https://www.nuget.org/packages/Microsoft.Data.OData/5.8.4) .*
=> Add release notes for ODL-5.8.4

test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Parsers/ExpandOptionParserTests.cs
* Fix the poli-check problem, that's from the PR: https://github.com/OData/odata.net/pull/1277
* Change the string "Country" to "CountryRegion" to meet the poli-check.
=> fix the poli-check problem for country/region

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Net35.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Net35.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Net35.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
*This pull request fixes issue #1276.*
* Remove the localization from package description
=> Fix issue #1276: remove the localization from package description

test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs
*This pull request fixes issue related to the policheck.
* "FooBar" doesn't meet the policheck requirement. Change it to "MyTerm".
=> Change foobar with MyTerm to let policheck happy

src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
Continue to update the Core vocabulary model.
1. Update the Core vocabulary xml
2. Update the existing Core vocabulary tests
3. Add three new test cases to cover the type and term definition in Core vocabulary
=> Update the Core vocabulary xml

v7/_posts/design/2018-09-26-$expandForV4.01.md
*This pull request is to create design doc related to issue #1265 .*
*Design doc: $expand for context url in V4.01.*
=> Design doc for expanded entity

src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
*This pull request updates the `DerivedTypeConstraint` appliesTo.*
* Update the `DerivedTypeConstraint` appliesTo
a. Remove "Function Action"
b. Add "ReturnType"
- [] *Test cases added*
=> Update DerivedTypeConstraint appliesTo

v7/_posts/release notes/2018-11-19-ODL-7.5.2.md
*This pull request is for release note of ODL-7.5.2.*
*NA*
=> Release Note for ODL-7.5.2

src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs, src/Microsoft.OData.Core/Metadata/MetadataUtilsCommon.cs, src/Microsoft.OData.Core/ODataPayloadValueConverter.cs, src/Microsoft.OData.Core/ODataRawValueUtils.cs, src/Microsoft.OData.Core/ReaderValidationUtils.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/IntegrationTests/Evaluation/AutoComputePayloadMetadataInJsonIntegrationTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeserializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Metadata/EdmLibraryExtensionsTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/Writer/JsonLight/ODataJsonLightSingletonWriterTests.cs
*This pull request fixes issue #1341.*
Make read and write the abstract type (Edm.PrimitiveType, Edm.ComplexType, Edm.EntityType) work
=> issue #1341, support read and write the abstract type

src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml, src/Microsoft.OData.Edm/Vocabularies/ValidationVocabularies.xml, src/Microsoft.OData.Edm/Vocabularies/VocabularyModelProvider.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CapabilitiesVocabularyTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/ValidationVocabularyTests.cs
*This pull request is to update the capabilities and validation vocabularies.*
*This pull request is to update the capabilities and validation vocabularies.*
=> Update the capabilites & Validation vocabulary

src/CodeGen/ODataT4CodeGenerator.cs, src/CodeGen/ODataT4CodeGenerator.ttinclude, src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
* Add the Example Term into Core vocabulary
* Add the Example Term into Core vocabulary
=> Add the Example Term into Core vocabulary

src/Microsoft.OData.Core/Microsoft.OData.Core.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.txt, src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs
*make the resource template and generated code align
*make the resource template and generated code align
=> make the resource template and generated code align

src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs, src/Microsoft.OData.Core/ODataWriterCore.cs, src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs, test/FunctionalTests/Taupo/Source/Taupo.Astoria/Client/ClientResponseQueryValueBuilder.cs, test/FunctionalTests/Taupo/Source/Taupo.Astoria/Contracts/OData/EntitySetInstance.cs, test/FunctionalTests/Taupo/Source/Taupo.Astoria/OData/JsonToPayloadElementConverter.cs, test/FunctionalTests/Taupo/Source/Taupo.Astoria/OData/ODataPayloadElementComparer.cs, test/FunctionalTests/Taupo/Source/Taupo.Astoria/StreamServices.cs, test/FunctionalTests/Tests/DataOData/Common/OData/Common/ModelBuilder.cs, test/FunctionalTests/Tests/DataOData/Common/OData/Common/ODataFeedEntriesObjectModelAnnotation.cs, test/FunctionalTests/Tests/DataOData/Common/OData/Common/ODataObjectModelVisitor.cs, test/FunctionalTests/Tests/DataOData/Common/OData/Common/ODataObjectModelVisitor`T.cs, test/FunctionalTests/Tests/DataOData/Common/OData/Common/ObjectModelExtensions.cs, test/FunctionalTests/Tests/DataOData/Common/OData/Common/PayloadBuilder.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/FeedReaderJsonLightTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/StreamReferenceValueReaderJsonLightTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/MessageToObjectModelReader.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/ODataFeedPayloadOrderObjectModelAnnotation.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/ObjectModelToPayloadElementConverter.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/PayloadReaderTestDescriptor.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Scenario.Tests/Streaming/ObjectModelWriteReadStreamer.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Writer.Tests/ObjectModelToMessageWriter.cs
Teach Taupo to read primitives and collections within collections.
*This pull request fixes issue #1427*
Fix tests disabled for streaming check-in.
=> Fix disabled tests.

v7/_posts/release notes/2019-06-04-ODL-7.6.0.md
=> Release notes 76

tools/CustomMSBuild/Versioning.props
=> Version update on the master

_layouts/post.html, v6/index.html, v7/index.html
adding redirect since the docs now live on https://docs.microsoft.com/odata
=> adding redirect for ghpages

_layouts/post.html, index.html, v6/index.html, v7/index.html
Redirecting all content to the new platform at https://docs.microsoft.com/odata
=> adding redirects for content.

src/Microsoft.OData.Edm/Vocabularies/AuthorizationVocabularies.xml, src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml, src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/AuthorizationVocabularyTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CapabilitiesVocabularyTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
*OASIS TC updates the Authorization, Core, Capabilities vocabularies annotations. This PR is updating the related docs used in OData.Edm library.
=> Update Authorization, Core, Capabilities vocabularies annotation

Build.props, src/Build.props, tools/CustomMSBuild/Build.props, tools/CustomMSBuild/Versioning.props
=> Sreejithpin patch 1

src/Microsoft.OData.Core/BindingPathHelper.cs, src/Microsoft.OData.Core/EdmExtensionMethods.cs, src/Microsoft.OData.Core/ODataWriterCore.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs
This pull request fixes the issues that were reported in CRM Profiling. 
Unnecessary ToList calls were replaced by List property. Since the function consuming this property was public, the signature of the function could not be changed and therefore a concrete List was added to the class as a workaround.
=> Fix CrmProfile performance issues

tools/CustomMSBuild/Versioning.props
=> Update release on master

tools/CustomMSBuild/Versioning.props
Instead of using [System.Convert]::ToInt16, [System.Convert]::ToUInt16 can be used.
Related commit: https://github.com/OData/odata.net/commit/3e30e05190dbb38f5ce54e175ee10174d7391349
=> Change conversion of Int16 to UInt16.

src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
…ator with double quote fails
*This pull request fixes issue https://github.com/OData/WebApi/issues/2136.*
IN operator can not pass the double quote. This PR try to fix it in single quote string and double quote string.
=> Fix WebApi issue https://github.com/OData/WebApi/issues/2136: IN operator with double quote fails

src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaWriter.cs, src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs
*This pull request fixes issue #832.*
*Add null check.*
=> CSDL Serialization: NullReferenceException when serializing 1:n NavigationProperties

src/Microsoft.OData.Edm/Validation/EdmError.cs, src/Microsoft.OData.Edm/Validation/Severity.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Validation/EdmErrorTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl
*This pull request fixes issue #1748 .*
Added a public property ErrorLevel to EdmError  with the default value "error"
=> Added Error Level to EdmError

src/Build.props
PR for Pending changes used in release but not in master
=> PR for Pending changes used in release but not in master

azure-pipelines-nightly.yml
Update azure-pipelines-nightly.yml to fix ESRP
=> Update azure-pipelines-nightly.yml to fix ESRP

azure-pipelines-rolling.yml, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl, test/PublicApiTests/Microsoft.OData.PublicApi.Tests.csproj, test/PublicApiTests/PublicApiTests.cs
=> Add public api test into pipeline

src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
commit b604c7a0ffa69379c36cef57fafa0e7cd6db2caa
Author: Kimyen Ladia <kiladia@microsoft.com>
Date:   Mon Oct 7 21:25:51 2019 +0000
fix empty collections in IN expression
commit c9bd538e07634dc865b7f69452e7cbb98e44a677
Author: Kimyen Ladia <kiladia@microsoft.com>
Date:   Wed Oct 2 22:42:47 2019 +0000
add tests
=> Validate and throw exception for invalid (empty) collections

src/Microsoft.OData.Edm/Csdl/CsdlReader.Json.cs, src/Microsoft.OData.Edm/Csdl/CsdlWriter.cs, src/Microsoft.OData.Edm/Csdl/Parsing/SchemaJsonParser.cs, src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs, src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaJsonWriter.cs, src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaWriter.cs, src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSchemaXmlWriter.cs, src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelReferenceElementsXmlVisitor.cs, src/Microsoft.OData.Edm/Csdl/Utf8JsonWriterExtensions.cs, src/Microsoft.OData.Edm/Schema/EdmNavigationProperty.cs, src/Microsoft.OData.Edm/Schema/EdmNavigationSource.cs, src/Microsoft.OData.Edm/ShippingAssemblyAttributes.cs, src/Microsoft.OData.Edm/Validation/Severity.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/AddNewEndingTokenVisitorTests.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/RemoveWildcardVisitorTests.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/SelectExpandPathBuilderTests.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/SelectExpandPathToStringVisitorTests.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj, test/FunctionalTests/Microsoft.OData.Client.Tests/Tracking/DataServiceContextNoTrackingStreamsTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Parsing/CsdlJsonParserTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSchemaWriterTests.cs
=> Fix build warning, remove FluentAssert

test/EndToEndTests/Services/ServiceWrapperApp/ServiceWrapperApp.csproj, test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousDelayQueryTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/ActionOverloadingTests/ActionOverloadingEndToEndTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/ClientWithoutTypeResolverTests/OpenTypesWithoutTypeResolverTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/Microsoft.Test.OData.Tests.Client.csproj, test/EndToEndTests/Tests/Client/Build.Desktop/ODataSimplifiedServiceTests/ODataSimplifiedServiceTests.cs, test/EndToEndTests/Tests/Client/Build.Desktop/PriorityOrderer.cs, test/EndToEndTests/Tests/Client/Build.Desktop/Properties/AssemblyInfo.cs, test/EndToEndTests/Tests/Client/Build.Desktop/TestPriorityAttribute.cs, test/EndToEndTests/Tests/Client/Build.Desktop/TripPinServiceTests/TripPinServiceTests.cs, test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Microsoft.OData.Client.TDDUnitTests.csproj
=> update client E2E xunit tests

src/Microsoft.OData.Core/UriParser/TypePromotionUtils.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/EnumFilterFunctionalTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Metadata/ODataUriResolverTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/NodeAssertions.cs
Fix Enum as string used with Has Issue
=> Fix Enum as string used with Has Issue

src/Microsoft.OData.Core/BindingPathHelper.cs, src/Microsoft.OData.Core/Evaluation/ODataConventionalEntityMetadataBuilder.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPath.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/ODataPathTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/SemanticAst/ODataPathTests.cs
*This pull request fixes issue #1725.*
Updates the way OData Path and OData path extensions work to reduce the impact they have on the OData reader.
N/A
=> OData path fixes

azure-pipelines-nightly.yml, src/Microsoft.Spatial/Microsoft.Spatial.csproj
=> pipeline update test

src/Microsoft.OData.Core/Microsoft.OData.Core.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.txt, src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs, src/Microsoft.OData.Core/UriParser/ODataUriParser.cs, src/Microsoft.OData.Core/UrlValidation/Rules/DeprecationRules.cs, src/Microsoft.OData.Core/UrlValidation/ValidationEngine/ODataUrlValidator.cs, src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs, src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularyModel.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UrlValidation/ODataUrlValidatorTests.cs
*This pull request improves performance of UrlValidation*
Optimize how UrlValidator eliminates necessary tests.
Make ODataUrlValidator public in order to support caching/re-use of detected optimizations
=> Improve UrlValidation Performance

test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request updates the public API baseline*
This pull request updates the public API baseline
=> Update public API baseline

src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj
=> Add System.Text.Json dependency into the Nuspec

src/Microsoft.OData.Client/BaseSaveResult.cs, src/Microsoft.OData.Client/HeaderCollection.cs
*This pull request fixes issue #1927 .*
=> fix location header missing for preflight requests

src/Microsoft.OData.Client/BaseSaveResult.cs
None
During synchronous operations like "SaveChanges" an OData error was not successfully unmarshalled when .NET Core or .NET 5 is used. If the server returns 400 and an OData error, the excepetion message is simply "Bad Request".
This PR fixes this problem. The problem did not occur at async operations or when .NET Framework was used.
The method to read OData erros needs to read the response stream twice. This was not a problem during async operations or using .NET Framework, because the response was copied to a MemoryStream so that the stream is seekable. However during synchronous operations using .NET Core or .NET 5, the response stream is not buffered. The method was not able to read the stream twice. This is because .NET Framework seems to handle HttpWebResponse streams internally a …
=> Fix reading OData error at synchronous operations for .NET Core.

src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs, src/Microsoft.OData.Core/ODataWriterCore.cs, src/Microsoft.OData.Core/UriParser/SemanticAst/ODataPathExtensions.cs, src/Microsoft.OData.Edm/Validation/ValidationRules.cs
*This pull request fixes issue #1538*
Creates a new ODatPath rather than repeatedly adding redundant cast segments to the existing path.
=> Address perf issue with Appending Cast Segment

tools/CustomMSBuild/Build.props
*This pull request fixes issue #1956 .*
=> Remove reference to ODataRuleSets file

src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs, src/Microsoft.OData.Edm/Schema/EdmEntitySet.cs, src/Microsoft.OData.Edm/Schema/EdmSingleton.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaReaderTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/ExtensionMethodTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Schema/EdmEntityContainerTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Reader.Tests/JsonLight/FeedReaderJsonLightTests.cs
*This pull request fixes issue #1938.*
=> Fix the navigation property binding target path issue

src/Microsoft.OData.Client/Microsoft.OData.Client.csproj, src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Edm/Microsoft.OData.Edm.csproj, src/Microsoft.Spatial/Microsoft.Spatial.csproj, tools/CustomMSBuild/Versioning.props
=> Updates for ODL 7.8 release

Build.props
Remove pdb only from root build.props
=> remove pdbonly

tools/CustomMSBuild/Versioning.props
Update Versioning.props for 7.8.1
=> Update Versioning.props for 7.8.1

src/Microsoft.OData.Edm/Schema/CoreModel/EdmCoreModel.cs, src/Microsoft.OData.Edm/Schema/EdmUntypedTypeReference.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Schema/EdmCoreModelTests.cs, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
*This pull request fixes issue https://github.com/OData/odata.net/issues/1983.*
* Enable nullable for EdmUntypedTypeReference.
=> Enable nullable setting for EdmUntypedTypeReference, Update the public API

test/EndToEndTests/Tests/Client/AsynchronousTests/AsynchronousQueryTests.cs
This test had been ignored because it was failing ADO build. It had a todo of re-enabling it..So i just fixed it and re-enabled it. 
=> re-enable the CancelBatchRequest test

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec, tools/CustomMSBuild/Versioning.props
Fix release notes
Fixing the release notes for ODL in nuget, also fixing the doc location
=> Fix release notes

src/Microsoft.OData.Core/Uri/NodeToStringBuilder.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/FilterAndOrderByBuilderTests.cs
This pull request fixes issue #2003.
Fixed translate uri recursive binary operators.
- [ x] *Test cases added*
=> Fix ODataUriExtensions.BuildUri produce invalid uri

tools/CustomMSBuild/Versioning.props
=> Update version to 7.8.3

src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriterUtils.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterUtilsTests.cs
- Implement asynchronous support in ODataJsonLightWriterUtils
- Tests for the changes
=> Implement asynchronous support in ODataJsonLightWriterUtils

src/Microsoft.OData.Core/JsonLight/JsonLightODataAnnotationWriter.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/JsonLightODataAnnotationWriterTests.cs
- Implement asynchronous support in JsonLightODataAnnotationWriter
- Tests for the changes
=> Implement asynchronous support in JsonLightODataAnnotationWriter

src/Microsoft.OData.Core/JsonLight/ODataJsonLightServiceDocumentSerializer.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightServiceDocumentSerializerTests.cs
Implement asynchronous support in **`ODataJsonLightServiceDocumentSerializer`**
=> Implement asynchronous support in ODataJsonLightServiceDocumentSerializer

src/Microsoft.OData.Core/JsonLight/ODataJsonLightResourceSerializer.cs, src/Microsoft.OData.Core/ODataResourceSetBase.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonLightInstanceAnnotationWriterAsyncTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionSerializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntityReferenceLinkSerializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightSerializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerAsyncTests.cs
Implement asynchronous support in **`ODataJsonLightResourceSerializer`**
=> Implement asynchronous support in ODataJsonLightResourceSerializer

src/Microsoft.OData.Client/BaseEntityType.cs, src/Microsoft.OData.Client/IBaseEntityType.cs, src/Microsoft.OData.Client/Materialization/EntryValueMaterializationPolicy.cs, src/Microsoft.OData.Client/MaterializeFromAtom.cs
=> Convert BaseEntityType to interface

src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs, src/Microsoft.OData.Client/Metadata/ODataTypeInfo.cs
improvement for client performance
This creates a OdataTypeInfo which will cache some property and type infos to be reused
=> Client Perf improvement

tools/CustomMSBuild/Versioning.props
=> Update version to 7.9.0

src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionWriter.cs, src/Microsoft.OData.Core/ODataCollectionWriterCore.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
Implement asynchronous support in **`ODataJsonLightCollectionWriter`**
=> Implement asynchronous support in ODataJsonLightCollectionWriter

src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs, src/Microsoft.OData.Core/ODataWriterCore.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightResourceSerializerTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataWriterCoreTests.cs
Affects **`ODataWriterCore`** and **`ODataJsonLightWriter`**
=> Implement asynchronous support in ODataJsonLightWriter

src/Microsoft.OData.Core/ODataRawOutputContext.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataRawOutputContextTests.cs
Implement asynchronous support in **`ODataRawOutputContext`**
=> Implement asynchronous support in ODataRawOutputContext

src/Microsoft.OData.Core/Batch/ODataBatchWriter.cs, src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriter.cs, src/Microsoft.OData.Core/MultipartMixed/ODataMultipartMixedBatchWriterUtils.cs, src/Microsoft.OData.Core/ODataWriteStream.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMultipartMixedBatchWriterTests.cs
Implement asynchronous support in **`ODataMultipartMixedBatchWriter`**.
=> Implement asynchronous support in ODataMultipartMixedBatchWriter

src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsNavigationSource.cs
*This pull request fixes issue #2122*
*Fixed the issue and minor refactoring to comply with the other caches (used EdmUtil.DictionaryGetOrUpdate).*
=> Fixed issue with caching of enumerable instead of list.

src/Microsoft.OData.Edm/EdmUtil.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/EdmUtilTests.cs
This pull request fixes issue #2147 .
Fixing string allocation and perf isue
=> Fix string allocation performance issue for IsQualifiedName

src/Microsoft.OData.Core/Json/IJsonReaderAsync.cs, src/Microsoft.OData.Core/Json/IJsonReaderFactoryAsync.cs, src/Microsoft.OData.Core/Json/IJsonStreamReaderAsync.cs, src/Microsoft.OData.Core/ODataBinaryStreamReader.cs
*This pull request is in partial fulfilment of #2019 .*
Implement interfaces in support of asynchronous reading of OData message payloads
=> Implement interfaces in support of asynchronous reading of OData message payloads

src/Microsoft.OData.Core/UriParser/Binders/SelectPathSegmentTokenBinder.cs, src/Microsoft.OData.Core/UriParser/Resolver/UnqualifiedODataUriResolver.cs, src/Microsoft.OData.Edm/ExtensionMethods/ExtensionMethods.cs, src/Microsoft.OData.Edm/Schema/EdmModelBase.cs
*This pull request fixes #2186 *
Performance improvement for finding operations inmodel
attached benchmark results
=> Performance fix for FindAcrossModels

tools/CustomMSBuild/Versioning.props
=> Update version to 7.9.4

src/Microsoft.OData.Client/ALinq/ExpressionWriter.cs, test/EndToEndTests/Tests/Client/Build.Desktop/ClientTests/ClientQueryTests.cs, test/FunctionalTests/Microsoft.OData.Client.Tests/ALinq/DollarFilterWithCastTests.cs, test/FunctionalTests/Service/Microsoft/OData/Service/Parsing/FunctionExpressionBinder.cs, test/FunctionalTests/Tests/DataServices/UnitTests/TDDUnitTests/Tests/Server/Parsing/NodeToExpressionTranslatorTests.cs
*This pull request fixes #1366 .*
=> remove single quotes from the type in a cast function

src/Microsoft.OData.Core/Json/ODataJsonReaderCoreUtils.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataJsonReaderCoreUtilsTests.cs
Implement asynchronous support in **`ODataJsonReaderCoreUtils`**
=> Implement asynchronous support in ODataJsonReaderCoreUtils

src/Microsoft.OData.Core/ODataReaderCore.cs
Currently, each time we need to get the parent scope we use a LINQ expression to find the parent in the scope stack. This is an expensive way to get the parent when we do it frequently.
With this change, when we add the scope to the scope stack (through EnterScope) we set its parent. Then, whenever we need the parent we get it from the current scope.
An added Debug.Assert ensures that, when returning the parent scope, the parentscope property of the current scope doesn't get out of sync with the stack.
None
=> Cache Parent Scope

src/Microsoft.OData.Core/JsonLight/ODataJsonLightPayloadKindDetectionDeserializer.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPayloadKindDetectionDeserializerTests.cs
Implement asynchronous support in `ODataJsonLightPayloadKindDetectionDeserializer`.
=> Implement asynchronous support in ODataJsonLightPayloadKindDetectionDeserializer

src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionDeserializer.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionDeserializerTests.cs
Implement asynchronous support in **`ODataJsonLightCollectionDeserializer`**.
=> Implement asynchronous support ODataJsonLightCollectionDeserializer

test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs
=> Add decimal key segment tests

src/Microsoft.OData.Core/JsonLight/ODataJsonLightParameterDeserializer.cs, src/Microsoft.OData.Core/JsonLight/ReorderingJsonReader.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ReorderingJsonReaderTests.cs
Implement asynchronous support in **`ReorderingJsonReader`**.
=> Implement asynchronous support in ReorderingJsonReader

src/Microsoft.OData.Core/JsonLight/ODataJsonLightServiceDocumentDeserializer.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightServiceDocumentDeserializerTests.cs
Implement asynchronous support in **`ODataJsonLightServiceDocumentDeserializer`**.
=> Implement asynchronous support in ODataJsonLightServiceDocumentDeserializer

src/Microsoft.OData.Core/JsonLight/ODataJsonLightCollectionReader.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionReaderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightCollectionWriterTests.cs
Implement asynchronous support in **`ODataJsonLightCollectionReader`**.
=> Implement asynchronous support in ODataJsonLightCollectionReader

src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs, src/Microsoft.OData.Core/ODataReaderCore.cs, src/Microsoft.OData.Core/ODataReaderCoreAsync.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Implement asynchronous support in **`ODataJsonLightReader`**.
=> Implement asynchronous support in ODataJsonLightReader

src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaReader.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaReaderTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightReaderTests.cs
Implement asynchronous support in **`ODataJsonLightDeltaReader`**.
=> Implement asynchronous support in ODataJsonLightDeltaReader

src/Microsoft.OData.Core/Json/BufferingJsonReader.cs, src/Microsoft.OData.Core/JsonLight/ReorderingJsonReader.cs, src/Microsoft.OData.Core/ODataBinaryStreamReader.cs, src/Microsoft.OData.Core/ODataBinaryStreamWriter.cs
This pull request addresses issue with zero-length array allocations
=> Avoid zero-length array allocations

src/Microsoft.OData.Core/Batch/ODataBatchReader.cs, src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchBodyContentReaderStream.cs, src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchPayloadItemPropertiesCache.cs, src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchReader.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.txt, src/Microsoft.OData.Core/Parameterized.Microsoft.OData.Core.cs, src/Microsoft.OData.Core/PublicAPI.Unshipped.txt, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightBatchReaderTests.cs, test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.net45.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard1.1.bsl, test/PublicApiTests/BaseLine/Microsoft.OData.PublicApi.netstandard2.0.bsl
Implement asynchronous support in **`ODataJsonLightBatchReader`**.
=> Implement asynchronous support in ODataJsonLightBatchReader

src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Core/ODataAsynchronousReader.cs, src/Microsoft.OData.Core/ODataRawInputContext.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataRawInputContextTests.cs
Implement asynchronous support in **`ODataRawInputContext`**.
=> Implement asynchronous support in ODataRawInputContext

tools/IncrementVersion.cmd, tools/IncrementVersion.ps1
=> adding comments and parameterization to IncrementVersion release script

tools/CustomMSBuild/Versioning.props
=> Update version to 7.12.1

tools/CustomMSBuild/Versioning.props
=> Update version to 7.12.2

tools/CustomMSBuild/Versioning.props
=> Update version to 7.12.3

tools/CustomMSBuild/Versioning.props
=> Bump version to 7.12.5

src/Microsoft.OData.Core/ODataWriterCore.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightDeltaWriterTests.cs
*This pull request fixes #2482 .*
=> shouldn't require id to write a deleted resource

test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/PathFunctionalTests.cs
=> Add test for throwing exception for multiple unnamed keys

docs/release.md
Adding more detail to the release instructions for easier onboarding.
=> Flush out release process documentation

src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Increment version number and update public api txt files

src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Core/ODataWriterCore.cs, src/Microsoft.OData.Core/TelemetryContants.cs, src/Microsoft.OData.Core/TelemetryHelper.cs
Apply tracing to OData write APIs
=> Apply tracing to OData write APIs

src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs, src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Core/ODataWriterCore.cs, src/Microsoft.OData.Core/Telemetry.cs
This PR logs exception events that occur in the `ODataWriter` and attaches them to the current trace activity.
=> Telemetry to log exception events

src/Microsoft.OData.Core/ODataWriterCore.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedSerializerUndecalredTests.cs
…llection
*This pull request fixes #2661.*
=> fixes #2661. Write the nested resource within nested collection in collection

buildandtest.yml
There is an issue with nuget reported here: https://github.com/microsoft/azure-pipelines-tasks/issues/18313 that is currently affecting the nightly build. I've set the version to `6.5.0`. This will be changed once the issue with nuget gets resolved. 
=> fix nuget installer issue

src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Bump version to 7.17.0

src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs
*This pull request fixes #2539 .*
=> Support $filter=dynamicProperty in ('')

docs/release.md
=> Rename AAD to Entra ID

src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Update version to 7.18.0

src/Microsoft.OData.Core/Json/BufferingJsonReader.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/BufferingJsonReaderTests.cs
*This pull request fixes #2261.*
Support deserialization of OData error with multiple items in the error details collection.
=> Support deserialization of OData error with multiple items in the error details collection

src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Client/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Client/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Edm/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Edm/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Edm/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Bump version to 7.19.0

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec, src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Nightly.Release.nuspec, src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Nightly.Release.nuspec, src/Microsoft.Spatial/Build.NuGet/Microsoft.Spatial.Release.nuspec
*This pull request fixes #2913 .*
Specifies a license expression rather than url on the nuget packages
n/a
=> #2913 switch to license expression

src/Microsoft.OData.Client/DeepInsertSaveResult.cs, test/FunctionalTests/Tests/DataServices/UnitTests/Client.TDD.Tests/Tests/DeepInsertE2ETests.cs
Cherry-pick [Fix DeepInsert issue with matching RelatedDescriptors to NestedItems](https://github.com/OData/odata.net/pull/2782) into dev-8.x
=> Fix DeepInsert issue with matching RelatedDescriptors to NestedItems

src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.TargetPath.cs
*This pull request fixes #2921 .*
=> Fix EdmTargetPath property collections

src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.Stream.cs, src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.TextWriter.cs, src/Microsoft.OData.Core/Json/ODataUtf8JsonWriter.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterAsyncBaseTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonTextWriterTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterAsyncTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterStreamTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/Json/ODataUtf8JsonWriterTests.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightWriterTests.cs
Porting this change from dev-8.x to main branch..  It's not a breaking change. 
=> implement streaming api in ODataUtf8JsonWriter (#2880)

src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Update version to 7.21.0

src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.TargetPath.cs
*This pull request fixes #2921.*
Fix `EdmTargetPath` property collections (#2922)
=> Fix EdmTargetPath property collections (#2922)

tools/CustomMSBuild/Versioning.props
Updates version to 7.21.1. This release includes a dependency configuration change that fixes a regression #2954
=> Bump version to 7.21.1

test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs
Fix test that fails intermittently on AzDO pipeline
=> Fix test that fails intermittently on AzDO pipeline

src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs, src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/TargetHelperTests.cs
*This pull request fixes #2969 *
Fixes TargetPathHelper to correctly handle collection-valued navigation properties and provides a test.
=> FIx #2969 targetPath with collection nav props and add test.

tools/CustomMSBuild/Versioning.props
=> Bump version to 7.21.2

src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsVocabularyAnnotation.cs, src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/ExtensionMethods/TargetHelperTests.cs
Fixes #2969 
This PR ports the fix made by #2970 to ODL 8 from ODL 7.
=> FIx #2969 targetPath with collection nav props and add test. (#2970)

src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
This PR cherry picks #2971 into ODL 8
=> Fix grouping by nested dynamic property to behave like grouping by nested standard property

src/Microsoft.OData.Core/UriParser/ODataPathInfo.cs
This PR cherry-picks the fixes from #2974 into ODL 8
=> Support net8.0 - Avoid evaluating Current on an empty enumerator (#2974)

tools/CustomMSBuild/Versioning.props
=> Bump version 8.0.0-preview.3

tools/CustomMSBuild/Versioning.props
Update version to `8.0.0-rc.1` release candidate
=> Update version to `8.0.0-rc.1` release candidate

src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Nightly.Release.nuspec, src/Microsoft.OData.Client/Build.NuGet/Microsoft.OData.Client.Release.nuspec
Add Microsoft.Extensions.Http to NuSpec to avoid dependency errors.
=> Add Microsoft.Extensions.Http to NuSpec

tools/CustomMSBuild/Versioning.props
=> Bump version to 8.0.1

src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
Cherry-picked commit https://github.com/OData/odata.net/commit/3a51fa0a3c434c56f243623aa5a766df39996aad (#2879).
=> (Cherry pick 8.0) Support type cast in group by

tools/CustomMSBuild/Versioning.props
=> Bump version to 8.0.2

tools/CustomMSBuild/Versioning.props
=> Bump version to 7.21.4

src/Microsoft.OData.Edm/PublicAPI/net8.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Edm/PublicAPI/net8.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Bump version to 8.1.0

src/Microsoft.OData.Edm/Csdl/SchemaWriter.cs, src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelCsdlSerializationVisitor.cs, src/Microsoft.OData.Edm/Csdl/Serialization/EdmModelSchemaSeparationSerializationVisitor.cs, src/Microsoft.OData.Edm/EdmModelVisitor.cs, src/Microsoft.OData.Edm/Helpers/TaskUtils.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/AsyncYieldStream.cs, test/FunctionalTests/Microsoft.OData.Core.Tests/ODataMessageWriterTests.cs, test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/Serialization/EdmModelCsdlSerializationVisitorTests.Async.cs
- Cherry-pick 17840516e3eba4c670f46d715dce9f811415898c from 8.x to 7.x
- Ensure compatibility with older .NET versions.
=> Port to 7.x: Fix issue #1320 - write metadata async issue

tools/CustomMSBuild/Versioning.props
=> Bump version to 7.21.5

src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/net8.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Bump version to 8.2.0

tools/CustomMSBuild/Versioning.props
=> Bump version to 7.21.6

tools/CustomMSBuild/Versioning.props
=> Bump version to 8.2.1

test/FunctionalTests/Microsoft.OData.Client.Tests/Microsoft.OData.Client.Tests.csproj, test/FunctionalTests/Microsoft.OData.Core.Tests/Microsoft.OData.Core.Tests.csproj, test/FunctionalTests/Microsoft.OData.Edm.Tests/Microsoft.OData.Edm.Tests.csproj, test/FunctionalTests/Microsoft.Spatial.Tests/Microsoft.Spatial.Tests.csproj
Update the package version to fix the vulnerable issue
Part of #https://github.com/OData/odata.net/issues/3132
=> Update the package version to fix the vulnerable issue

tools/CustomMSBuild/Versioning.props
* Let's have a new version to unblock one workload for latest fix.
=> Bump version to 8.2.3

azure-pipelines-nightly.yml, nightly.yml
Migrate code signing to ESRPv5
=> Migrate Code Signing to ESRPv5

azure-pipelines-nightly.yml, nightly.yml
Migrate code signing to ESRP v5
=> Migrate 7.x pipeline to ESRP v5

src/Microsoft.OData.Core/Microsoft.OData.Core.csproj, src/Microsoft.OData.Core/ShippingAssemblyAttributes.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/JsonLightConstants.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/TestStreamRequestMessage.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/TestStreamResponseMessage.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/EndToEndTestBaseOfT.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/Microsoft.OData.Core.E2E.Tests.csproj, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/WriteJsonPayloadTests/SerializationInfoEdgeTests.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/WriteJsonPayloadTests/WritePayloadHelper.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/WriteJsonPayloadTests/WritePayloadTests.cs
This Pr ports these tests: [odata.net/test/EndToEndTests/Tests/Client/Build.Desktop/WriteJsonPayloadTests at main · OData/odata.net (github.com)](https://github.com/OData/odata.net/tree/main/test/EndToEndTests/Tests/Client/Build.Desktop/WriteJsonPayloadTests) from using WCF services to using Microsoft.AspNetCore.OData services. 
=> Port WriteJsonPayloadTests

src/Microsoft.OData.Core/UriParser/Aggregation/ApplyBinder.cs, test/UnitTests/Microsoft.OData.Core.Tests/UriParser/Extensions/Binders/ApplyBinderTests.cs
=> pulling in a forked repo to make modifications

test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/DeltaTests/DeltaTests.cs
This PR ports the delta tests: https://github.com/OData/odata.net/blob/release-7.x/test/EndToEndTests/Tests/Client/Build.Desktop/DeltaTests/DeltaTests.cs
=> Port delta tests

.github/ISSUE_TEMPLATE/1_BUG_REPORT.md, .github/ISSUE_TEMPLATE/2_FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/config.yml
=> Configure issue templates

.github/ISSUE_TEMPLATE/1_BUG_REPORT.md, .github/ISSUE_TEMPLATE/2_FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/config.yml
Move templates metadata to template files
=> Move templates metadata to template files

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/config.yml
Rename issue templates to fix ordering
=> Rename issue templates to fix ordering

src/Microsoft.OData.Core/Json/ODataJsonPropertyAndValueDeserializer.cs
*This pull request fixes #3264 in 8.x.*
This is a port of the PR https://github.com/OData/odata.net/pull/3267 to 8.x. It applies the same logic and reasoning adjusted to 8.x (e.g. use of `ReadOnlyEnumerable<ODataPropertyInfo>` instead of `ReadOnlyEnumerable<ODataProperty>`)
Team members should **not** trigger a build this way for pull requests coming from forked repositories. They should instead trigger the …
=> Avoid redundant verifications when appending new resource properties

src/Microsoft.OData.Edm/Csdl/Parsing/Common/EdmXmlDocumentParser.cs, test/UnitTests/Microsoft.OData.Edm.Tests/Csdl/CsdlReaderTests.cs
*This pull request fixes #2894.*
This pull request improves the validation of type names in CSDL parsing to ensure that only valid type names are accepted. The changes add comprehensive checks for invalid type name formats and ensure that clear, consistent error messages are produced for each invalid case.
**Details:**
- Enhanced type name validation logic to reject malformed or unsupported type names, such as:
- Unmatched or misplaced parentheses (e.g., `ns.myType)`, `Collection(ns.myType`, `(ns.myType)`, `(ns.myType`)
- Unsupported type prefixes (e.g., `Enumerable(ns.myType)`)
- Invalid suffixes or extra characters (e.g., `Collection(ns.myType)s`, `Collection)ns.myType(`)
- Empty or whitespace-only type names
- Invalid use of Collection or Ref (e.g., `Collection()`, `Ref`, `Ref()`)
- …
=> Fix CSDL typename validation

tools/CustomMSBuild/Versioning.props
=> Bump version to 8.2.4

test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Annotations/InstanceAnnotationTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/CustomInstanceAnnotations/CustomInstanceAnnotationTestsController.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CustomInstanceAnnotationsTests/ClientInstanceAnnotationsTests.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/CustomInstanceAnnotationsTests/CustomInstanceAnnotationsSerializer.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/AnnotationTests/CustomResourceSerializer.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/AnnotationTests/InstanceAnnotationTests.cs
* Port InstanceAnnotationTests and ClientInstanceAnnotationsTests
Cherry-pick: db683f280f19194d4a11311946950e1471963dd4
=> Cherry-pick: Port annotations tests

test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/TypeDefinition/TypeDefinitionDataModel.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/TypeDefinition/TypeDefinitionDataSource.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/TypeDefinition/TypeDefinitionEdmModel.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/TypeDefinition/TypeDefinitionTestsController.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/TypeDefinition/TypeDefinitionBinders.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/TypeDefinition/TypeDefinitionDeserializer.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/TypeDefinition/TypeDefinitionSerializer.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/TypeDefinition/TypeDefinitionTests.cs
* Port TypeDefinitionTests
Cherry-pick: 2cf124231f3a804a55f2ad04339fa96ac815ac17
=> Cherry-Pick: Port TypeDefinition Tests (#3210)

test/UnitTests/Microsoft.OData.Core.Tests/UriParser/HardCodedTestModel.cs, test/UnitTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Cherry-pick: 93794371871badbf7b51c15b8e33373c44951d99
=> Cherry-pick: (PR 3225) adding uri parser tests for the newly supported average overloads

test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/AsyncRequestTests/AsyncRequestTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Asynchronous/AsyncMethodTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Asynchronous/AsynchronousDelayQueryTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Asynchronous/AsynchronousQueryTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Asynchronous/AsynchronousSingletonClientTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Asynchronous/AsynchronousUpdateTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/Server/Asynchronous/BindingTestsController.cs, test/EndToEndTests/Common/Microsoft.OData.E2E.TestCommon/Common/TestHttpClientRequestMessage.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsyncMethodTests.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsynchronousDelayQueryTests.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsynchronousEndToEndTestBase.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsynchronousQueryTests.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsynchronousSingletonClientTest.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsynchronousTestsExtensionMethods.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/AsynchronousUpdateTests.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/BindingTests.cs, test/EndToEndTests/Tests/Client/Microsoft.OData.Client.E2E.Tests/AsynchronousTests/CustomODataResourceSerializer.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/AsyncRequestTests/AsyncRequestTests.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/AsyncRequestTests/AsyncTask.cs, test/EndToEndTests/Tests/Core/Microsoft.OData.Core.E2E.Tests/AsyncRequestTests/CustomHttpClientRequestMessage.cs
* Port AsyncRequest Tests
Cherry-pick: 652cd440766f9a46a13061a47525ca098a71412b
=> Cherry-pick: Port AsyncRequest Tests (#3220)

src/Microsoft.OData.Core/UriParser/Binders/SelectExpandBinder.cs, test/UnitTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs
Cherry-pick: a4fc1703a6f670a5c0860717905b7cd68deef533
=> Cherry-pick: #3238 Fix - set elementTypeReference from curNavigationProp

src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/net45/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard1.1/PublicAPI.Unshipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.OData.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, tools/CustomMSBuild/Versioning.props
=> Bump version to 7.22.0

azure-pipelines-nightly.yml, azure-pipelines-rolling.yml
Cherry-pick: db347aa06670e37a6f9a5f6d393d3bc19cc3c8b3
=> Cherry-pick: Update pipeline agent image (#3320)

azure-pipelines-nightly.yml, azure-pipelines-rolling.yml
Apply 'Preferred,Nuget.org' network isolation setting to fix failing build
=> Apply 'Preferred,Nuget.org' network isolation setting (#3337)
